package ssl

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"math/big"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"testing"
	"time"
)

// writeFile creates p (and its parents) with content.
func writeFile(t *testing.T, p, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// writeLeafPEM writes a self-signed certificate for names, expiring at
// notAfter, to p and returns its path.
func writeLeafPEM(t *testing.T, p string, notAfter time.Time, names ...string) string {
	t.Helper()
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		t.Fatal(err)
	}
	tmpl := &x509.Certificate{
		SerialNumber: big.NewInt(time.Now().UnixNano()),
		Subject:      pkix.Name{CommonName: names[0]},
		DNSNames:     names,
		NotBefore:    time.Now().Add(-time.Hour),
		NotAfter:     notAfter,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		t.Fatal(err)
	}
	writeFile(t, p, string(pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})))
	return p
}

// TestServedHosts pins which names count as served hosts and which
// ssl_certificate each maps to.
func TestServedHosts(t *testing.T) {
	nginx := t.TempDir()
	writeFile(t, filepath.Join(nginx, "sites", "a.conf"), `
# Generated by nself build
server {
    listen 80;
    server_name plain.example.com;
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name api.example.com "Auth.Example.com" *.wild.example.com localhost 10.0.0.1 [::1] _ foo.local foo.localhost foo.test .dot.example.com ~^re$;
    ssl_certificate /etc/nginx/ssl/certificates/example-com/fullchain.pem;  # base-domain cert dir
    ssl_certificate_key /etc/nginx/ssl/certificates/example-com/privkey.pem;
    location / {
        ssl_certificate /etc/nginx/ssl/certificates/nested/fullchain.pem;
        proxy_pass http://x;
    }
}
server {
    listen 0.0.0.0:443 ssl;
    server_name nocert.example.com;
}
`)
	writeFile(t, filepath.Join(nginx, "sites", "z.conf"), `
server { listen 443 ssl; server_name api.example.com dup.example.com; ssl_certificate /etc/nginx/ssl/other.pem; }
`)
	writeFile(t, filepath.Join(nginx, "conf.d", "hand.conf"), `
http {
    server { listen 443 ssl http2; server_name hand.example.com; ssl_certificate /etc/nginx/ssl/hand/fullchain.pem; }
}
`)
	writeFile(t, filepath.Join(nginx, "conf.d", "ignored.conf.bak"), `server { listen 443; server_name bak.example.com; ssl_certificate /x; }`)
	writeFile(t, filepath.Join(nginx, "nginx.conf"), `server { listen 443; server_name top.example.com; ssl_certificate /x; }`)

	got, err := ServedHosts(nginx)
	if err != nil {
		t.Fatal(err)
	}
	want := map[string]string{
		"api.example.com":  "/etc/nginx/ssl/certificates/example-com/fullchain.pem",
		"auth.example.com": "/etc/nginx/ssl/certificates/example-com/fullchain.pem",
		"dup.example.com":  "/etc/nginx/ssl/other.pem",
		"hand.example.com": "/etc/nginx/ssl/hand/fullchain.pem",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("ServedHosts = %v\nwant %v", got, want)
	}

	empty, err := ServedHosts(filepath.Join(nginx, "missing"))
	if err != nil || len(empty) != 0 {
		t.Fatalf("missing dir: %v, %v", empty, err)
	}
}

// TestServedHostsMalformed pins that broken confs never panic.
func TestServedHostsMalformed(t *testing.T) {
	nginx := t.TempDir()
	writeFile(t, filepath.Join(nginx, "sites", "bad.conf"), "}}} server { listen 443; server_name a.example.com; ssl_certificate /etc/nginx/ssl/a.pem")
	got, err := ServedHosts(nginx)
	if err != nil || got["a.example.com"] != "/etc/nginx/ssl/a.pem" {
		t.Fatalf("got %v, %v", got, err)
	}
}

// TestDiskCertFor pins the container-prefix mapping.
func TestDiskCertFor(t *testing.T) {
	ssl := filepath.Join(t.TempDir(), "ssl")
	got, ok := DiskCertFor(ssl, "/etc/nginx/ssl/certificates/example-com/fullchain.pem")
	if want := filepath.Join(ssl, "certificates", "example-com", "fullchain.pem"); !ok || got != want {
		t.Fatalf("got %q %v, want %q", got, ok, want)
	}
	for _, bad := range []string{
		"/certificates/example-com/fullchain.pem", // missing mount prefix
		"/etc/nginx/ssl/../../x/y.pem",            // escapes the mount
		"/etc/nginx/ssl/$ssl_server_name/f.pem",   // resolved by nginx at runtime
		"/etc/nginx/sslx/f.pem",                   // sibling prefix
		"relative/f.pem",
	} {
		if p, ok := DiskCertFor(ssl, bad); ok {
			t.Errorf("DiskCertFor(%q) = %q, want not mapped", bad, p)
		}
	}
}

// TestNewestKnownCert pins the scan of the ACME store and certbot lineages.
func TestNewestKnownCert(t *testing.T) {
	ssl, le := filepath.Join(t.TempDir(), "ssl"), filepath.Join(t.TempDir(), "le")
	now := time.Now()
	acme := filepath.Join(ssl, ".acme", "certificates")
	writeLeafPEM(t, filepath.Join(acme, "api.example.com.crt"), now.Add(60*24*time.Hour), "api.example.com")
	writeLeafPEM(t, filepath.Join(acme, "api.example.com.issuer.crt"), now.Add(900*24*time.Hour), "api.example.com")
	writeLeafPEM(t, filepath.Join(acme, "other.example.com.crt"), now.Add(800*24*time.Hour), "other.example.com")
	writeLeafPEM(t, filepath.Join(le, "live", "wild", "cert.pem"), now.Add(80*24*time.Hour), "*.example.com")
	writeFile(t, filepath.Join(le, "live", "junk", "cert.pem"), "not a certificate")

	got, ok := NewestKnownCert(ssl, "api.example.com", le)
	if !ok || filepath.Base(filepath.Dir(got.Path)) != "wild" {
		t.Fatalf("want the wildcard lineage (newest covering cert), got %+v ok=%v", got, ok)
	}
	got, ok = NewestKnownCert(ssl, "api.example.com", filepath.Join(t.TempDir(), "none"))
	if !ok || filepath.Base(got.Path) != "api.example.com.crt" {
		t.Fatalf("want the ACME store cert (issuer cert and other hosts ignored), got %+v ok=%v", got, ok)
	}
	if _, ok := NewestKnownCert(ssl, "nobody.example.org", le); ok {
		t.Fatal("no certificate covers nobody.example.org")
	}

	if runtime.GOOS != "windows" && os.Getuid() != 0 {
		unreadable := filepath.Join(le, "live", "wild", "cert.pem")
		if err := os.Chmod(unreadable, 0); err != nil {
			t.Fatal(err)
		}
		got, ok = NewestKnownCert(ssl, "api.example.com", le)
		if !ok || filepath.Base(got.Path) != "api.example.com.crt" {
			t.Fatalf("an unreadable lineage must be skipped, got %+v ok=%v", got, ok)
		}
	}
}

// TestServedEnvAndAddr pins env layering, the process-env guarantee and the
// dial-address rules.
func TestServedEnvAndAddr(t *testing.T) {
	root := t.TempDir()
	writeFile(t, filepath.Join(root, ".env"), "ENV=prod\nNGINX_HTTPS_PORT=8443\nNGINX_BIND_IP=0.0.0.0\n")
	writeFile(t, filepath.Join(root, ".env.prod"), "NGINX_HTTPS_PORT=9443\nNGINX_BIND_IP=10.1.2.3\n")
	writeFile(t, filepath.Join(root, ".env.dev"), "NGINX_HTTPS_PORT=1111\n")

	env, err := ServedEnv(root, "dev")
	if err != nil {
		t.Fatal(err)
	}
	if got := ServedAddr(env); got != "10.1.2.3:9443" {
		t.Fatalf("addr = %s, want .env.prod to win (ENV from .env beats the fallback)", got)
	}
	if v, ok := os.LookupEnv("NGINX_HTTPS_PORT"); ok && v == "9443" {
		t.Fatal("ServedEnv leaked the served stack's env into this process")
	}

	bare := t.TempDir()
	writeFile(t, filepath.Join(bare, ".env"), "NGINX_SSL_PORT=7443\n")
	writeFile(t, filepath.Join(bare, ".env.dev"), "NGINX_BIND_IP=0.0.0.0\n")
	env, err = ServedEnv(bare, "dev")
	if err != nil || ServedAddr(env) != "127.0.0.1:7443" {
		t.Fatalf("fallback env + NGINX_SSL_PORT + wildcard bind: %v %v", ServedAddr(env), err)
	}
	if env, err = ServedEnv(t.TempDir(), "dev"); err != nil || ServedAddr(env) != "127.0.0.1:443" {
		t.Fatalf("no env files: %v %v", ServedAddr(env), err)
	}
	if got := ServedAddr(map[string]string{"NGINX_BIND_IP": "::", "NGINX_HTTPS_PORT": " 8443 "}); got != "127.0.0.1:8443" {
		t.Fatalf("got %s", got)
	}
}
