#!/usr/bin/env bash

# headers.sh - Comprehensive security headers management
# POSIX-compliant, no Bash 4+ features

# Get the directory where this script is located
SECURITY_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

set -euo pipefail

LIB_ROOT="$(dirname "$SECURITY_LIB_DIR")"

# Source dependencies
source "$LIB_ROOT/utils/display.sh" 2>/dev/null || true
source "$SECURITY_LIB_DIR/csp.sh" 2>/dev/null || true

# Security header configuration
SECURITY_HEADERS_MODE="${SECURITY_HEADERS_MODE:-strict}"
HSTS_MAX_AGE="${HSTS_MAX_AGE:-31536000}" # 1 year
HSTS_INCLUDE_SUBDOMAINS="${HSTS_INCLUDE_SUBDOMAINS:-true}"
HSTS_PRELOAD="${HSTS_PRELOAD:-false}"

# X-Frame-Options
X_FRAME_OPTIONS="${X_FRAME_OPTIONS:-DENY}" # DENY, SAMEORIGIN, or ALLOW-FROM

# Referrer-Policy
REFERRER_POLICY="${REFERRER_POLICY:-strict-origin-when-cross-origin}"

# Permissions-Policy (formerly Feature-Policy)
PERMISSIONS_POLICY_CAMERA="${PERMISSIONS_POLICY_CAMERA:-()}"
PERMISSIONS_POLICY_MICROPHONE="${PERMISSIONS_POLICY_MICROPHONE:-()}"
PERMISSIONS_POLICY_GEOLOCATION="${PERMISSIONS_POLICY_GEOLOCATION:-()}"
PERMISSIONS_POLICY_PAYMENT="${PERMISSIONS_POLICY_PAYMENT:-()}"
PERMISSIONS_POLICY_USB="${PERMISSIONS_POLICY_USB:-()}"

# Generate all security headers
headers::generate_all() {
  local mode="${1:-$SECURITY_HEADERS_MODE}"
  local ssl_enabled="${2:-true}"

  # Create headers array (using indexed arrays for Bash 3.2 compatibility)
  local header_names=()
  local header_values=()

  # Content-Security-Policy
  local csp
  csp=$(csp::generate "${CSP_MODE:-strict}")
  header_names+=("Content-Security-Policy")
  header_values+=("$csp")

  # X-Frame-Options
  header_names+=("X-Frame-Options")
  header_values+=("$X_FRAME_OPTIONS")

  # X-Content-Type-Options
  header_names+=("X-Content-Type-Options")
  header_values+=("nosniff")

  # X-XSS-Protection (legacy, but still useful for older browsers)
  header_names+=("X-XSS-Protection")
  header_values+=("1; mode=block")

  # Referrer-Policy
  header_names+=("Referrer-Policy")
  header_values+=("$REFERRER_POLICY")

  # Permissions-Policy
  local permissions_policy
  permissions_policy=$(headers::generate_permissions_policy)
  if [[ -n "$permissions_policy" ]]; then
    header_names+=("Permissions-Policy")
    header_values+=("$permissions_policy")
  fi

  # Strict-Transport-Security (only if SSL enabled)
  if [[ "$ssl_enabled" == "true" ]]; then
    local hsts
    hsts=$(headers::generate_hsts)
    header_names+=("Strict-Transport-Security")
    header_values+=("$hsts")
  fi

  # X-Permitted-Cross-Domain-Policies
  header_names+=("X-Permitted-Cross-Domain-Policies")
  header_values+=("none")

  # Output headers
  local i=0
  local count=${#header_names[@]}
  while [[ $i -lt $count ]]; do
    printf "%s: %s\n" "${header_names[$i]}" "${header_values[$i]}"
    i=$((i + 1))
  done
}

# Generate HSTS header
headers::generate_hsts() {
  local hsts="max-age=$HSTS_MAX_AGE"

  if [[ "$HSTS_INCLUDE_SUBDOMAINS" == "true" ]]; then
    hsts="$hsts; includeSubDomains"
  fi

  if [[ "$HSTS_PRELOAD" == "true" ]]; then
    hsts="$hsts; preload"
  fi

  printf "%s" "$hsts"
}

# Generate Permissions-Policy header
headers::generate_permissions_policy() {
  local policies=()

  # Camera
  if [[ -n "$PERMISSIONS_POLICY_CAMERA" ]]; then
    policies+=("camera=$PERMISSIONS_POLICY_CAMERA")
  fi

  # Microphone
  if [[ -n "$PERMISSIONS_POLICY_MICROPHONE" ]]; then
    policies+=("microphone=$PERMISSIONS_POLICY_MICROPHONE")
  fi

  # Geolocation
  if [[ -n "$PERMISSIONS_POLICY_GEOLOCATION" ]]; then
    policies+=("geolocation=$PERMISSIONS_POLICY_GEOLOCATION")
  fi

  # Payment
  if [[ -n "$PERMISSIONS_POLICY_PAYMENT" ]]; then
    policies+=("payment=$PERMISSIONS_POLICY_PAYMENT")
  fi

  # USB
  if [[ -n "$PERMISSIONS_POLICY_USB" ]]; then
    policies+=("usb=$PERMISSIONS_POLICY_USB")
  fi

  # Interest cohort (FLoC)
  policies+=("interest-cohort=()")

  # Join policies
  local result=""
  for policy in "${policies[@]}"; do
    if [[ -z "$result" ]]; then
      result="$policy"
    else
      result="$result, $policy"
    fi
  done

  printf "%s" "$result"
}

# Export headers to nginx format
headers::export_nginx() {
  local output_file="${1:-nginx/includes/security-headers.conf}"
  local ssl_enabled="${2:-true}"

  # Create directory if needed
  mkdir -p "$(dirname "$output_file")" 2>/dev/null || true

  # Generate headers
  cat >"$output_file" <<'EOF'
# Security Headers
# Generated by nself security headers
# See: https://owasp.org/www-project-secure-headers/

EOF

  # Get all headers
  local headers
  headers=$(headers::generate_all "$SECURITY_HEADERS_MODE" "$ssl_enabled")

  # Convert to nginx format
  echo "$headers" | while IFS= read -r line; do
    if [[ -n "$line" ]]; then
      local header_name header_value
      header_name=$(echo "$line" | cut -d: -f1)
      header_value=$(echo "$line" | cut -d: -f2- | sed 's/^ *//')
      printf "add_header %s \"%s\" always;\n" "$header_name" "$header_value"
    fi
  done >>"$output_file"

  # Add CORS headers placeholder
  cat >>"$output_file" <<'EOF'

# CORS Headers (configure as needed)
# Uncomment and configure for your domains
# add_header Access-Control-Allow-Origin "https://yourdomain.com" always;
# add_header Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS" always;
# add_header Access-Control-Allow-Headers "Authorization, Content-Type" always;
# add_header Access-Control-Allow-Credentials "true" always;
# add_header Access-Control-Max-Age "3600" always;
EOF

  show_success "Exported security headers to $output_file"
  return 0
}

# Show current security headers configuration
headers::show() {
  printf "${COLOR_CYAN}═══════════════════════════════════════════════════${COLOR_RESET}\n"
  printf "${COLOR_CYAN}       Security Headers Configuration${COLOR_RESET}\n"
  printf "${COLOR_CYAN}═══════════════════════════════════════════════════${COLOR_RESET}\n\n"

  printf "${COLOR_YELLOW}General Settings${COLOR_RESET}\n"
  printf "  Mode: %s\n" "${SECURITY_HEADERS_MODE:-strict}"
  printf "  CSP Mode: %s\n" "${CSP_MODE:-strict}"
  printf "\n"

  printf "${COLOR_YELLOW}HSTS Configuration${COLOR_RESET}\n"
  printf "  Max Age: %s seconds (%s days)\n" "$HSTS_MAX_AGE" "$((HSTS_MAX_AGE / 86400))"
  printf "  Include Subdomains: %s\n" "$HSTS_INCLUDE_SUBDOMAINS"
  printf "  Preload: %s\n" "$HSTS_PRELOAD"
  printf "\n"

  printf "${COLOR_YELLOW}Other Headers${COLOR_RESET}\n"
  printf "  X-Frame-Options: %s\n" "$X_FRAME_OPTIONS"
  printf "  Referrer-Policy: %s\n" "$REFERRER_POLICY"
  printf "\n"

  printf "${COLOR_YELLOW}Permissions Policy${COLOR_RESET}\n"
  printf "  Camera: %s\n" "$PERMISSIONS_POLICY_CAMERA"
  printf "  Microphone: %s\n" "$PERMISSIONS_POLICY_MICROPHONE"
  printf "  Geolocation: %s\n" "$PERMISSIONS_POLICY_GEOLOCATION"
  printf "  Payment: %s\n" "$PERMISSIONS_POLICY_PAYMENT"
  printf "  USB: %s\n" "$PERMISSIONS_POLICY_USB"
  printf "\n"

  printf "${COLOR_CYAN}Generated Headers:${COLOR_RESET}\n"
  local headers
  headers=$(headers::generate_all "$SECURITY_HEADERS_MODE" "true")
  echo "$headers" | while IFS= read -r line; do
    if [[ -n "$line" ]]; then
      printf "  %s\n" "$line"
    fi
  done
}

# Validate security headers
headers::validate() {
  local url="${1:-http://localhost}"
  local errors=0

  printf "${COLOR_CYAN}Validating security headers for: %s${COLOR_RESET}\n\n" "$url"

  if ! command -v curl >/dev/null 2>&1; then
    show_error "curl is required for header validation"
    return 1
  fi

  # Fetch headers
  local response
  response=$(curl -sI "$url" 2>/dev/null)

  if [[ -z "$response" ]]; then
    show_error "Failed to fetch headers from $url"
    return 1
  fi

  # Check each header
  local required_headers="X-Frame-Options X-Content-Type-Options Referrer-Policy"
  for header in $required_headers; do
    if echo "$response" | grep -qi "^$header:"; then
      local value
      value=$(echo "$response" | grep -i "^$header:" | cut -d: -f2- | tr -d '\r' | sed 's/^ *//')
      show_success "$header: $value"
    else
      show_error "$header: MISSING"
      errors=$((errors + 1))
    fi
  done

  # Check Content-Security-Policy
  if echo "$response" | grep -qi "^Content-Security-Policy:"; then
    show_success "Content-Security-Policy: Present"
  else
    show_warning "Content-Security-Policy: MISSING (recommended)"
  fi

  # Check HSTS (only for HTTPS)
  if [[ "$url" == https://* ]]; then
    if echo "$response" | grep -qi "^Strict-Transport-Security:"; then
      local hsts_value
      hsts_value=$(echo "$response" | grep -i "^Strict-Transport-Security:" | cut -d: -f2- | tr -d '\r' | sed 's/^ *//')
      show_success "Strict-Transport-Security: $hsts_value"
    else
      show_error "Strict-Transport-Security: MISSING (required for HTTPS)"
      errors=$((errors + 1))
    fi
  fi

  # Check Permissions-Policy
  if echo "$response" | grep -qi "^Permissions-Policy:"; then
    show_success "Permissions-Policy: Present"
  else
    show_info "Permissions-Policy: Not configured (optional)"
  fi

  printf "\n"
  if [[ $errors -eq 0 ]]; then
    show_success "All required security headers are present"
    return 0
  else
    show_error "Missing $errors required security header(s)"
    return 1
  fi
}

# Interactive configuration wizard
headers::configure() {
  printf "${COLOR_CYAN}Security Headers Configuration Wizard${COLOR_RESET}\n\n"

  # Select mode
  printf "Select security headers mode:\n"
  printf "  1) Strict (maximum security)\n"
  printf "  2) Moderate (balanced) [recommended]\n"
  printf "  3) Permissive (minimal restrictions)\n"
  printf "\nChoice [2]: "
  read -r mode_choice

  local mode="strict"
  case "${mode_choice:-2}" in
    1) mode="strict" ;;
    2) mode="moderate" ;;
    3) mode="permissive" ;;
    *) mode="moderate" ;;
  esac

  # HSTS configuration
  printf "\n${COLOR_YELLOW}HSTS (Strict-Transport-Security) Configuration${COLOR_RESET}\n"
  printf "HSTS max-age in seconds [31536000 = 1 year]: "
  read -r hsts_age
  hsts_age="${hsts_age:-31536000}"

  printf "Include subdomains? (y/n) [y]: "
  read -r hsts_subdomains
  local include_subdomains="true"
  if [[ "$(echo "${hsts_subdomains:-y}" | tr '[:upper:]' '[:lower:]')" == "n" ]]; then
    include_subdomains="false"
  fi

  # X-Frame-Options
  printf "\n${COLOR_YELLOW}X-Frame-Options Configuration${COLOR_RESET}\n"
  printf "Select X-Frame-Options:\n"
  printf "  1) DENY (most secure)\n"
  printf "  2) SAMEORIGIN (allow framing from same origin)\n"
  printf "\nChoice [1]: "
  read -r frame_choice

  local frame_options="DENY"
  case "${frame_choice:-1}" in
    2) frame_options="SAMEORIGIN" ;;
    *) frame_options="DENY" ;;
  esac

  # CSP configuration
  printf "\n${COLOR_YELLOW}Content Security Policy${COLOR_RESET}\n"
  printf "Configure CSP now? (y/n) [y]: "
  read -r configure_csp

  if [[ "$(echo "${configure_csp:-y}" | tr '[:upper:]' '[:lower:]')" == "y" ]]; then
    csp::configure
  fi

  # Save configuration
  printf "\n${COLOR_CYAN}Save configuration?${COLOR_RESET} (y/n) [y]: "
  read -r save_choice

  if [[ "$(echo "${save_choice:-y}" | tr '[:upper:]' '[:lower:]')" == "y" ]]; then
    # Update .env
    if [[ -f ".env" ]]; then
      # Remove old settings
      local temp_file
      temp_file=$(mktemp)
      grep -v "^SECURITY_HEADERS_MODE=" .env >"$temp_file" 2>/dev/null || true
      grep -v "^HSTS_MAX_AGE=" "$temp_file" >.env 2>/dev/null || true
      grep -v "^HSTS_INCLUDE_SUBDOMAINS=" .env >"$temp_file" 2>/dev/null || true
      grep -v "^X_FRAME_OPTIONS=" "$temp_file" >.env 2>/dev/null || true
      rm -f "$temp_file"

      # Add new settings
      printf "\n# Security Headers\n" >>.env
      printf "SECURITY_HEADERS_MODE=%s\n" "$mode" >>.env
      printf "HSTS_MAX_AGE=%s\n" "$hsts_age" >>.env
      printf "HSTS_INCLUDE_SUBDOMAINS=%s\n" "$include_subdomains" >>.env
      printf "X_FRAME_OPTIONS=%s\n" "$frame_options" >>.env

      show_success "Security headers configuration saved to .env"
    fi

    # Export to nginx
    headers::export_nginx "nginx/includes/security-headers.conf" "true"
  fi
}

# Test security headers
headers::test() {
  local test_url="${1:-http://localhost}"

  printf "${COLOR_CYAN}Testing security headers...${COLOR_RESET}\n\n"

  # Validate headers
  if headers::validate "$test_url"; then
    printf "\n${COLOR_GREEN}Security headers test PASSED${COLOR_RESET}\n"
    return 0
  else
    printf "\n${COLOR_RED}Security headers test FAILED${COLOR_RESET}\n"
    return 1
  fi
}

# Generate report
headers::report() {
  local output_file="${1:-security-headers-report.txt}"

  printf "Generating security headers report...\n"

  {
    printf "Security Headers Report\n"
    printf "Generated: %s\n" "$(date)"
    printf "="
    printf "%.0s=" {1..60}
    printf "\n\n"

    printf "Configuration\n"
    printf "="
    printf "%.0s=" {1..60}
    printf "\n"
    headers::show

    printf "\n\nGenerated Headers\n"
    printf "="
    printf "%.0s=" {1..60}
    printf "\n"
    headers::generate_all "$SECURITY_HEADERS_MODE" "true"
  } >"$output_file"

  show_success "Report saved to $output_file"
  return 0
}

# Export functions
export -f headers::generate_all
export -f headers::generate_hsts
export -f headers::generate_permissions_policy
export -f headers::export_nginx
export -f headers::show
export -f headers::validate
export -f headers::configure
export -f headers::test
export -f headers::report
