package canon

// Go move table (EPIC P7-CANON D2).
//
// Purpose:     the canon engine runs on every invocation, and P7-REG keeps YAML
//              parsing off the startup path, so the rows of contract
//              canon-fragments v1 (and the core verbs) are compiled into
//              cmd/commands/canon_moves_gen.go by tools/canongen. This file builds
//              the table value and renders it as Go source.
// Inputs:      a validated raw *File (LoadRaw).
// Outputs:     Table (token slices, deterministic order) and the gofmt-ed source
//              of `package commands` holding `var canonTable = canonTableT{...}`.
// Constraints: pure and deterministic: the same File renders the same bytes. The
//              types the generated literal names (canonTableT, canonRowT) are
//              aliases of Table and TableRow declared in cmd/commands.

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strconv"
	"strings"
)

// GeneratedMarker is the first line of the generated move table.
const GeneratedMarker = "// GENERATED BY tools/canongen — DO NOT HAND EDIT"

// TableRow is one row of the table. From and To are command tokens without the
// leading "nself ". Which fields are set depends on the list the row is in.
type TableRow struct {
	From      []string
	To        []string
	Since     string
	RemovalAt string
	Plugin    string // breakouts: the plugin that now owns the command
	Message   string // removed: the text E410 prints
	Summary   string // hubs: the one-line summary (From holds the hub path)
}

// Table is the engine's view of the raw canon: no YAML, no maps, token slices.
type Table struct {
	Verbs       []string
	Moves       []TableRow
	Shims       []TableRow
	RetiredHubs []TableRow
	Hubs        []TableRow
	Builtins    [][]string
	Breakouts   []TableRow
	Removed     []TableRow
}

// BuildTable turns the raw canon into a Table. Rows of each list are sorted by
// prefix length (longest first), then lexically, so a reader scanning the list
// meets the most specific row first.
func BuildTable(f *File) Table {
	t := Table{Verbs: append([]string{}, f.Verbs...)}
	for _, r := range f.Moves {
		t.Moves = append(t.Moves, rowOf(r))
	}
	for _, r := range f.Shims {
		t.Shims = append(t.Shims, rowOf(r))
	}
	for _, r := range f.RetiredHubs {
		t.RetiredHubs = append(t.RetiredHubs, rowOf(r))
	}
	for _, h := range f.Hubs {
		t.Hubs = append(t.Hubs, TableRow{From: strings.Fields(h.Path), Summary: h.Summary})
	}
	for _, b := range f.Builtins {
		t.Builtins = append(t.Builtins, strings.Fields(b))
	}
	for _, b := range f.Breakouts {
		t.Breakouts = append(t.Breakouts, TableRow{From: strings.Fields(b.From), To: strings.Fields(b.To), Since: b.Since, Plugin: b.Plugin})
	}
	for _, r := range f.Removed {
		t.Removed = append(t.Removed, TableRow{From: strings.Fields(r.From), Since: r.Since, Message: r.Message})
	}
	for _, list := range [][]TableRow{t.Moves, t.Shims, t.RetiredHubs, t.Hubs, t.Breakouts, t.Removed} {
		sortRows(list)
	}
	sort.Slice(t.Builtins, func(i, j int) bool {
		return strings.Join(t.Builtins[i], " ") < strings.Join(t.Builtins[j], " ")
	})
	return t
}

func rowOf(r Row) TableRow {
	return TableRow{From: strings.Fields(r.From), To: strings.Fields(r.To), Since: r.Since, RemovalAt: r.RemovalAt}
}

func sortRows(rows []TableRow) {
	sort.Slice(rows, func(i, j int) bool {
		if len(rows[i].From) != len(rows[j].From) {
			return len(rows[i].From) > len(rows[j].From)
		}
		return strings.Join(rows[i].From, " ") < strings.Join(rows[j].From, " ")
	})
}

// RenderGoTable renders the Go source of the move table for f.
func RenderGoTable(f *File) []byte {
	t := BuildTable(f)
	var b bytes.Buffer
	b.WriteString(GeneratedMarker + "\n")
	b.WriteString("// Source: internal/canon/canon.yaml and internal/canon/domains/*.yaml (go run ./tools/canongen).\n\n")
	b.WriteString("package commands\n\n")
	b.WriteString("var canonTable = canonTableT{\n")
	fmt.Fprintf(&b, "\tVerbs: %s,\n", strs(t.Verbs))
	for _, l := range []struct {
		name string
		rows []TableRow
	}{{"Moves", t.Moves}, {"Shims", t.Shims}, {"RetiredHubs", t.RetiredHubs}, {"Hubs", t.Hubs}, {"Breakouts", t.Breakouts}, {"Removed", t.Removed}} {
		if len(l.rows) == 0 {
			continue
		}
		fmt.Fprintf(&b, "\t%s: []canonRowT{\n", l.name)
		for _, r := range l.rows {
			b.WriteString("\t\t" + rowLit(r) + ",\n")
		}
		b.WriteString("\t},\n")
	}
	if len(t.Builtins) > 0 {
		b.WriteString("\tBuiltins: [][]string{\n")
		for _, p := range t.Builtins {
			b.WriteString("\t\t" + strings.TrimPrefix(strs(p), "[]string") + ",\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	out, err := format.Source(b.Bytes())
	if err != nil {
		// The input is built from quoted strings only; a failure is a bug here.
		panic(fmt.Sprintf("canon: RenderGoTable produced invalid Go: %v", err))
	}
	return out
}

func rowLit(r TableRow) string {
	parts := []string{"From: " + strs(r.From)}
	if len(r.To) > 0 {
		parts = append(parts, "To: "+strs(r.To))
	}
	for _, kv := range []struct{ k, v string }{{"Since", r.Since}, {"RemovalAt", r.RemovalAt}, {"Plugin", r.Plugin}, {"Message", r.Message}, {"Summary", r.Summary}} {
		if kv.v != "" {
			parts = append(parts, kv.k+": "+strconv.Quote(kv.v))
		}
	}
	return "{" + strings.Join(parts, ", ") + "}"
}

func strs(s []string) string {
	q := make([]string, len(s))
	for i, x := range s {
		q[i] = strconv.Quote(x)
	}
	return "[]string{" + strings.Join(q, ", ") + "}"
}
