package main

// The canon page: .github/wiki/Command-Canon.md.
//
// Purpose: one generated table of every old command spelling and where it went
// in v1.5 (move, shim, retired hub, break-out to a plugin, removal), so readers
// and CI see the canon's move plan without reading the YAML fragments.
//
// Inputs: the merged canon rows (canon.LoadRaw) and, optionally, an earlier
// copy of the page whose PROSE block is carried over.
//
// Outputs: Markdown with the table between GENERATED markers and one human PROSE
// block for the removal plan.
//
// Constraints: deterministic (rows sorted by old path, then kind); never
// reads the cobra tree or the installed plugins; the page states that the
// change applies from v1.5.0 and the old spelling works until v1.6.0.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"github.com/nself-org/cli/internal/canon"
)

const (
	canonProseBegin = "<!-- BEGIN PROSE:removal-plan -->"
	canonProseEnd   = "<!-- END PROSE:removal-plan -->"
	canonTableBegin = "<!-- BEGIN GENERATED:canon-table -->"
	canonTableEnd   = "<!-- END GENERATED:canon-table -->"
	canonHeader     = "<!-- GENERATED BY tools/cmdinventory -format canon — DO NOT HAND EDIT (the removal-plan PROSE block is the only hand-written part) -->"
	defaultProse    = "Each old spelling keeps working through v1.5.x with a deprecation warning and is removed at the release in `removal_at`. Break-outs and removals have no removal date: the command leaves core at v1.5.0."
)

// canonProseFrom is the -prose-from flag value.
var canonProseFrom string

// canonRow is one line of the canon table.
type canonRow struct{ Old, New, Kind, Since, RemovalAt string }

// canonRows flattens the canon move rows, sorted by old path then kind.
func canonRows(r canon.Rows) []canonRow {
	var out []canonRow
	for _, m := range r.Moves {
		out = append(out, canonRow{m.From, m.To, "move", m.Since, m.RemovalAt})
	}
	for _, m := range r.Shims {
		out = append(out, canonRow{m.From, m.To, "shim", m.Since, m.RemovalAt})
	}
	for _, m := range r.RetiredHubs {
		out = append(out, canonRow{m.From, m.To, "retired-hub", m.Since, m.RemovalAt})
	}
	for _, b := range r.Breakouts {
		out = append(out, canonRow{b.From, b.To + " (plugin " + b.Plugin + ")", "breakout", b.Since, ""})
	}
	for _, x := range r.Removed {
		out = append(out, canonRow{x.From, "", "removed", x.Since, ""})
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Old != out[j].Old {
			return out[i].Old < out[j].Old
		}
		return out[i].Kind < out[j].Kind
	})
	return out
}

// writeCanon renders the page for the embedded canon rows.
func writeCanon(w io.Writer, proseFrom string) error {
	raw, err := canon.LoadRaw()
	if err != nil {
		return fmt.Errorf("load canon: %w", err)
	}
	prose := defaultProse
	if proseFrom != "" {
		if data, rerr := os.ReadFile(proseFrom); rerr == nil {
			if kept := between(string(data), canonProseBegin, canonProseEnd); kept != "" {
				prose = kept
			}
		}
	}
	_, err = io.WriteString(w, renderCanon(canonRows(raw.Rows), prose))
	return err
}

// renderCanon builds the page text.
func renderCanon(rows []canonRow, prose string) string {
	var b strings.Builder
	b.WriteString(canonHeader + "\n\n# Command Canon\n\n")
	b.WriteString("Where every old command spelling went in the v1.5 canon (ADR 0016). The change applies from v1.5.0; the old spelling keeps working until the release in `removal_at` (v1.6.0 at the earliest). Run `make canon cmd-inventory wiki-commands parity` after editing a canon fragment.\n\n")
	b.WriteString(canonTableBegin + "\n\n")
	b.WriteString("| Old path | New path | Kind | Since | Removal at |\n|---|---|---|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | %s | %s | %s | %s |\n", code(r.Old), code(r.New), r.Kind, dash(r.Since), dash(r.RemovalAt))
	}
	fmt.Fprintf(&b, "\nTotal rows: %d\n\n", len(rows))
	b.WriteString(canonTableEnd + "\n\n## Removal plan\n\n")
	b.WriteString(canonProseBegin + "\n" + strings.TrimSpace(prose) + "\n" + canonProseEnd + "\n\n")
	b.WriteString("← [[Commands]] | [[Home]] →\n")
	return b.String()
}

// code formats a command path (or a path with a note) for the table.
func code(p string) string {
	if p == "" {
		return "—"
	}
	if i := strings.Index(p, " ("); i >= 0 {
		return "`nself " + p[:i] + "`" + p[i:]
	}
	return "`nself " + p + "`"
}

func dash(s string) string {
	if s == "" {
		return "—"
	}
	return s
}

// between returns the trimmed text between two markers, or "" when absent.
func between(body, start, end string) string {
	i := strings.Index(body, start)
	if i < 0 {
		return ""
	}
	i += len(start)
	j := strings.Index(body[i:], end)
	if j < 0 {
		return ""
	}
	return strings.TrimSpace(body[i : i+j])
}
