package main

// Tests for the plugin exclusion and the canon page format.

import (
	"bytes"
	"strings"
	"testing"

	"github.com/nself-org/cli/internal/canon"
	"github.com/nself-org/cli/internal/cmdregistry"
)

func fixtureRegistry() *cmdregistry.Registry {
	cmd := func(path, name, parent, cn string) cmdregistry.Command {
		return cmdregistry.Command{Path: path, Name: name, Parent: parent, Canon: cn, Summary: name}
	}
	return &cmdregistry.Registry{Commands: []cmdregistry.Command{
		cmd("nself db", "db", "nself", canon.CanonCore),
		cmd("nself acme", "acme", "nself", canon.CanonPlugin),
		cmd("nself acme sync", "sync", "nself acme", canon.CanonPlugin),
		cmd("nself help", "help", "nself", canon.CanonBuiltin),
		cmd("nself db migrate", "migrate", "nself db", canon.CanonSubcommand),
	}}
}

func TestInventoryExcludesPlugin(t *testing.T) {
	got := project(fixtureRegistry(), 3, true)
	if len(got) != 1 || got[0].Name != "db" {
		t.Fatalf("top level = %+v, want only db", got)
	}
	if len(got[0].Subcommands) != 1 || got[0].Subcommands[0].Name != "migrate" {
		t.Fatalf("db subcommands = %+v", got[0].Subcommands)
	}
	for _, n := range project(fixtureRegistry(), 3, true) {
		if strings.HasPrefix(n.Path, "nself acme") {
			t.Fatalf("plugin entry leaked: %s", n.Path)
		}
	}
}

func TestCanonFormat(t *testing.T) {
	rows := canonRows(canon.Rows{
		Moves:       []canon.Row{{From: "urls", To: "config urls", Since: "v1.5.0", RemovalAt: "v1.6.0"}},
		Shims:       []canon.Row{{From: "up", To: "start", Since: "v1.5.0", RemovalAt: "v1.6.0"}},
		Breakouts:   []canon.Breakout{{From: "ci", Plugin: "ci", To: "ci", Since: "v1.5.0"}},
		Removed:     []canon.Removed{{From: "legacy", Since: "v1.5.0", Message: "gone"}},
		RetiredHubs: []canon.Row{{From: "service", To: "add", Since: "v1.5.0", RemovalAt: "v1.6.0"}},
	})
	if len(rows) != 5 {
		t.Fatalf("rows = %d", len(rows))
	}
	page := renderCanon(rows, "keep me")
	for _, want := range []string{
		"GENERATED BY tools/cmdinventory -format canon",
		"| Old path | New path | Kind | Since | Removal at |",
		"| `nself urls` | `nself config urls` | move | v1.5.0 | v1.6.0 |",
		"| `nself ci` | `nself ci` (plugin ci) | breakout | v1.5.0 | — |",
		"| `nself legacy` | — | removed | v1.5.0 | — |",
		"Total rows: 5",
		canonProseBegin + "\nkeep me\n" + canonProseEnd,
	} {
		if !strings.Contains(page, want) {
			t.Errorf("page lacks %q", want)
		}
	}
	// sorted by old path
	if strings.Index(page, "`nself ci`") > strings.Index(page, "`nself urls`") {
		t.Error("rows not sorted by old path")
	}
	if renderCanon(rows, "keep me") != page {
		t.Error("render is not deterministic")
	}
	empty := renderCanon(nil, defaultProse)
	if !strings.Contains(empty, "Total rows: 0") || !strings.Contains(empty, "removed at the release") {
		t.Error("empty page malformed")
	}
}

func TestCanonFormatRunsOnEmbeddedCanon(t *testing.T) {
	var buf bytes.Buffer
	if err := run(&buf, "canon", 1, false); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(buf.String(), canonTableBegin) {
		t.Fatal("no table markers")
	}
}
