// Command cmdinventory prints the CLI's real command tree.
//
// Purpose:     make SPORT F02, the wiki, the parity matrix and the command
//
//	registry generated from the binary rather than hand-maintained.
//	Every previous count in the docs was typed by a human and had
//	drifted (F02 and the PRI both claimed 84 when the binary
//	registered more).
//
// Inputs:      -format json|markdown|names|registry, -depth N (0 = top
//
//	level only), -hidden.
//
// Outputs:     the command tree on stdout. json, markdown and names are
//
//	projections of the command registry (internal/cmdregistry) in the
//	historical inventory shape, byte-identical to the former walker.
//	registry writes the registry document itself (contract
//	cli.command-registry v1) behind a first `_generated` key, as the
//	v1.5 contract that .github/command-registry.json commits.
//
// Constraints: imports cmd/commands so the source of truth is the same cobra
//
//	registration the shipped binary uses and the same registry build
//	`nself help --json` serves; no separate parser to drift.
//	Read-only: never mutates the tree. The json format keeps HTML
//	escaping (the committed inventory has it); registry does not.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/nself-org/cli/cmd/commands"
	"github.com/nself-org/cli/internal/cmdregistry"
)

// generatedMarker is the first key of the committed registry document.
const generatedMarker = "GENERATED BY tools/cmdinventory -format registry \u2014 DO NOT HAND EDIT"

func main() {
	format := flag.String("format", "json", "output format: json, markdown, names, registry")
	depth := flag.Int("depth", 1, "how many levels below root to include (1 = top level only)")
	includeHidden := flag.Bool("hidden", false, "include hidden commands")
	flag.Parse()

	if err := run(os.Stdout, *format, *depth, *includeHidden); err != nil {
		fmt.Fprintln(os.Stderr, err)
		if strings.HasPrefix(err.Error(), "unknown -format") {
			os.Exit(2)
		}
		os.Exit(1)
	}
}

// run builds the registry of the live tree and renders one format to w.
func run(w io.Writer, format string, depth int, includeHidden bool) error {
	switch format {
	case "json", "names", "markdown", "registry":
	default:
		return fmt.Errorf("unknown -format %q", format)
	}
	reg, err := commands.BuildRegistry(true)
	if err != nil {
		return fmt.Errorf("build registry: %w", err)
	}
	if format == "registry" {
		return writeRegistry(w, reg)
	}
	tree := project(reg, depth, includeHidden)
	switch format {
	case "json":
		enc := json.NewEncoder(w)
		enc.SetIndent("", "  ")
		if err := enc.Encode(tree); err != nil {
			return fmt.Errorf("encode: %w", err)
		}
	case "names":
		for _, c := range tree {
			fmt.Fprintln(w, c.Name)
		}
	case "markdown":
		printMarkdown(w, tree)
	}
	return nil
}

// generatedDoc puts the GENERATED marker before the registry's own fields
// (encoding/json flattens the embedded pointer, keeping field order).
type generatedDoc struct {
	Generated string `json:"_generated"`
	*cmdregistry.Registry
}

// writeRegistry writes the registry document with the first-key marker, in the
// registry's published style: 2-space indent, no HTML escaping, newline.
func writeRegistry(w io.Writer, reg *cmdregistry.Registry) error {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(generatedDoc{Generated: generatedMarker, Registry: reg}); err != nil {
		return fmt.Errorf("encode registry: %w", err)
	}
	_, err := w.Write(buf.Bytes())
	return err
}

func printMarkdown(w io.Writer, tree []Command) {
	fmt.Fprintln(w, "| Command | Short Description | Group | Subcommands |")
	fmt.Fprintln(w, "|---|---|---|---|")
	for _, c := range tree {
		subs := make([]string, 0, len(c.Subcommands))
		for _, s := range c.Subcommands {
			subs = append(subs, s.Name)
		}
		group := c.GroupID
		if group == "" {
			group = "—"
		}
		sub := strings.Join(subs, ", ")
		if sub == "" {
			sub = "—"
		}
		fmt.Fprintf(w, "| `%s` | %s | %s | %s |\n", c.Path, escapePipes(c.Short), group, sub)
	}
	fmt.Fprintf(w, "\nTotal top-level commands: %d\n", len(tree))
}

func escapePipes(s string) string { return strings.ReplaceAll(s, "|", "\\|") }
