package main

// Tests for the registry projection and the registry output format.
//
// Purpose: pin that the inventory formats are byte-identical to the committed
// files the old tree walker produced, and that -format registry is
// deterministic and carries the GENERATED marker as its first key.

import (
	"bytes"
	"os"
	"strings"
	"testing"
)

func render(t *testing.T, format string, depth int, hidden bool) []byte {
	t.Helper()
	var buf bytes.Buffer
	if err := run(&buf, format, depth, hidden); err != nil {
		t.Fatalf("run %s: %v", format, err)
	}
	return buf.Bytes()
}

func TestProjectionMatchesCommittedInventory(t *testing.T) {
	want, err := os.ReadFile("../../.github/command-inventory.json")
	if err != nil {
		t.Fatal(err)
	}
	if got := render(t, "json", 2, false); !bytes.Equal(got, want) {
		t.Fatalf("projection differs from .github/command-inventory.json (%d vs %d bytes); run `make cmd-inventory`", len(got), len(want))
	}
}

func TestProjectionHidesHelpAndHiddenCommands(t *testing.T) {
	names := strings.Fields(string(render(t, "names", 1, false)))
	if len(names) == 0 {
		t.Fatal("no top-level commands")
	}
	for _, n := range names {
		if n == "help" {
			t.Error("help must not be part of the inventory")
		}
	}
	withHidden := strings.Fields(string(render(t, "names", 1, true)))
	if len(withHidden) <= len(names) {
		t.Errorf("-hidden added nothing: %d vs %d", len(withHidden), len(names))
	}
	if got := render(t, "json", 0, false); string(got) != "null\n" {
		t.Errorf("depth 0 = %q, want null", got)
	}
}

func TestRegistryFormatIsDeterministicAndMarked(t *testing.T) {
	a, b := render(t, "registry", 1, false), render(t, "registry", 1, false)
	if !bytes.Equal(a, b) {
		t.Fatal("two runs differ")
	}
	if !bytes.HasPrefix(a, []byte("{\n  \"_generated\": \"GENERATED BY tools/cmdinventory -format registry — DO NOT HAND EDIT\",\n  \"schema_version\": \"1\",\n")) {
		t.Fatalf("unexpected start: %.200s", a)
	}
	if !bytes.HasSuffix(a, []byte("}\n")) {
		t.Error("missing trailing newline")
	}
}

func TestUnknownFormatIsRefused(t *testing.T) {
	var buf bytes.Buffer
	if err := run(&buf, "bogus", 1, false); err == nil || !strings.HasPrefix(err.Error(), "unknown -format") {
		t.Fatalf("err = %v", err)
	}
	if buf.Len() != 0 {
		t.Error("wrote output for an unknown format")
	}
}
