package apidocs

// openapi_render.go — Scalar HTML rendering, default config and nginx wiring.
//
// Purpose: render the embedded Scalar HTML doc viewer, provide the default ApiDocsConfig and generate the nginx config snippet that serves /api-docs and /docs, split out of openapi.go for file size.
// Inputs: an ApiDocsConfig and the generated spec's URL.
// Outputs: rendered HTML, a default config, or an nginx config fragment.
// Constraints: pure move from openapi.go (CLI-R12 Batch E); no behaviour change.

import (
	_ "embed"
	"fmt"
	"strings"

	"github.com/nself-org/cli/internal/nginxtopo"
)

// renderScalarHTML substitutes template variables into the embedded HTML.
func renderScalarHTML(tmpl string, cfg ApiDocsConfig, title string) string {
	theme := cfg.Theme
	if theme == "" {
		theme = "default"
	}
	docsPath := cfg.Path
	if docsPath == "" {
		docsPath = "/docs"
	}
	_ = docsPath // used by nginx conf; scalar page self-references via relative URL

	tmpl = strings.ReplaceAll(tmpl, "{{.Title}}", title)
	tmpl = strings.ReplaceAll(tmpl, "{{.Theme}}", theme)
	return tmpl
}

// DefaultApiDocsConfig returns defaults when api_docs is not configured.
func DefaultApiDocsConfig() ApiDocsConfig {
	return ApiDocsConfig{
		Enabled:         true,
		Path:            "/docs",
		Theme:           "default",
		GraphQLEnabled:  true,
		GraphQLEndpoint: "/v1/graphql",
	}
}

// NginxConf returns the nginx site configuration for /api-docs and /docs,
// served on docs.<baseDomain>. Output is a complete server { } block intended
// to live in nginx/sites/ alongside hasura.conf and auth.conf.
//
// docsServePath is the path on the docs subdomain (default /docs); /api-docs
// is always served alongside it.
func NginxConf(docsServePath, baseDomain string) string {
	if docsServePath == "" {
		docsServePath = "/docs"
	}
	if baseDomain == "" {
		baseDomain = "localhost"
	}
	certDir := strings.ReplaceAll(baseDomain, ".", "-")
	return fmt.Sprintf(`# Generated by nself build - DO NOT EDIT MANUALLY
# Service: docs.%s

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name docs.%s;

    ssl_certificate %s/certificates/%s/fullchain.pem;
    ssl_certificate_key %s/certificates/%s/privkey.pem;

    server_tokens off;

    location /api-docs {
        alias /opt/nself/.dist/openapi.json;
        add_header Content-Type "application/json";
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-store";
    }
    location %s {
        alias /opt/nself/.dist/scalar.html;
        add_header Content-Type "text/html";
        add_header Cache-Control "no-store";
    }
}
`, baseDomain, baseDomain, nginxtopo.NginxSSLContainerPath, certDir, nginxtopo.NginxSSLContainerPath, certDir, docsServePath)
}
