// Package ledger is the bundle install-state ledger (contract:cli.bundle-ledger
// v1, P7 PLUG D6): per project, which bundles are installed and, per plugin,
// installed_by / explicit / tier / version / checksum.
//
// Purpose: record WHY a plugin is present, so refcounted bundle remove
// (P7-PLUG-20), app-ready (P7-PLUG-19) and the surfaces (P7-SURF-13) stop
// inferring it from plugin directories.
// Inputs: a project root (the file lives at <root>/.nself/state/bundles.json)
// and, for bootstrap, Sources (bundle membership plus installed plugins).
// Outputs: a validated Ledger, written atomically (temp + rename) under a file
// lock. The file is machine-owned: its first key is _generated and nothing in
// it is meant to be edited by hand.
// Constraints: this package imports neither internal/bundle nor
// internal/plugin, so bundle install/remove can import it without a cycle;
// callers adapt their own types to Sources. No new dependency.
package ledger

import (
	"bytes"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"time"
)

const (
	// Generated is the value of the first key, _generated.
	Generated = "GENERATED BY nself — DO NOT HAND EDIT"
	// SchemaVersion is the only schema_version this package reads or writes.
	SchemaVersion = 1

	// TierFree and TierLicensed are the two tiers a plugin record may carry.
	TierFree     = "free"
	TierLicensed = "licensed"

	// MaxBytes caps the size of a ledger file that Parse and Load accept.
	MaxBytes = 4 << 20

	// SlugPattern is the shape of a bundle or plugin slug used as a map key.
	SlugPattern = `^[a-z0-9][a-z0-9._-]*$`
	// ChecksumPattern is a lowercase hex sha256, or empty when unknown.
	ChecksumPattern = `^([0-9a-f]{64})?$`
)

var (
	slugRE     = regexp.MustCompile(SlugPattern)
	checksumRE = regexp.MustCompile(ChecksumPattern)
)

// Tiers lists the accepted tier values.
var Tiers = []string{TierFree, TierLicensed}

// BundleRecord is one installed bundle.
type BundleRecord struct {
	InstalledAt string `json:"installed_at"` // RFC 3339 UTC
}

// PluginRecord says why one plugin is present.
type PluginRecord struct {
	// InstalledBy lists the installed bundles that reference the plugin, sorted.
	InstalledBy []string `json:"installed_by"`
	// Explicit is true when the owner installed the plugin on its own, so a
	// bundle remove must keep it.
	Explicit bool   `json:"explicit"`
	Tier     string `json:"tier"`
	Version  string `json:"version"`
	// Checksum is the lowercase hex sha256 of the installed artifact, or empty
	// when the install did not record one.
	Checksum string `json:"checksum"`
}

// Ledger is the file. Field order is the on-disk key order: _generated first.
type Ledger struct {
	Generated     string                  `json:"_generated"`
	SchemaVersion int                     `json:"schema_version"`
	Bundles       map[string]BundleRecord `json:"bundles"`
	Plugins       map[string]PluginRecord `json:"plugins"`
}

// New returns an empty, valid ledger.
func New() Ledger {
	return Ledger{
		Generated:     Generated,
		SchemaVersion: SchemaVersion,
		Bundles:       map[string]BundleRecord{},
		Plugins:       map[string]PluginRecord{},
	}
}

// normalize replaces nil maps and slices with empty ones and sorts and
// de-duplicates every installed_by, so the written bytes are deterministic.
func (l *Ledger) normalize() {
	l.Generated = Generated
	l.SchemaVersion = SchemaVersion
	if l.Bundles == nil {
		l.Bundles = map[string]BundleRecord{}
	}
	if l.Plugins == nil {
		l.Plugins = map[string]PluginRecord{}
	}
	for slug, p := range l.Plugins {
		seen := map[string]bool{}
		by := make([]string, 0, len(p.InstalledBy))
		for _, b := range p.InstalledBy {
			if !seen[b] {
				seen[b] = true
				by = append(by, b)
			}
		}
		sort.Strings(by)
		p.InstalledBy = by
		l.Plugins[slug] = p
	}
}

// Clone returns a deep copy.
func (l Ledger) Clone() Ledger {
	c := New()
	c.Generated, c.SchemaVersion = l.Generated, l.SchemaVersion
	for k, v := range l.Bundles {
		c.Bundles[k] = v
	}
	for k, v := range l.Plugins {
		v.InstalledBy = append([]string(nil), v.InstalledBy...)
		c.Plugins[k] = v
	}
	return c
}

// Validate checks every rule the JSON Schema cannot express alone: references
// between records and the keep-or-remove invariant.
func (l Ledger) Validate() error {
	if l.Generated != Generated {
		return fmt.Errorf("ledger: _generated must be %q", Generated)
	}
	if l.SchemaVersion != SchemaVersion {
		return fmt.Errorf("ledger: unsupported schema_version %d (this nself reads %d)", l.SchemaVersion, SchemaVersion)
	}
	for slug, b := range l.Bundles {
		if !slugRE.MatchString(slug) {
			return fmt.Errorf("ledger: bundle slug %q does not match %s", slug, SlugPattern)
		}
		if _, err := time.Parse(time.RFC3339, b.InstalledAt); err != nil {
			return fmt.Errorf("ledger: bundle %q installed_at %q is not RFC 3339", slug, b.InstalledAt)
		}
	}
	for slug, p := range l.Plugins {
		if !slugRE.MatchString(slug) {
			return fmt.Errorf("ledger: plugin slug %q does not match %s", slug, SlugPattern)
		}
		if p.Tier != TierFree && p.Tier != TierLicensed {
			return fmt.Errorf("ledger: plugin %q tier %q is neither free nor licensed", slug, p.Tier)
		}
		if !checksumRE.MatchString(p.Checksum) {
			return fmt.Errorf("ledger: plugin %q checksum is not a lowercase hex sha256", slug)
		}
		if !p.Explicit && len(p.InstalledBy) == 0 {
			return fmt.Errorf("ledger: plugin %q has no installed_by and is not explicit; it should not be recorded", slug)
		}
		seen := map[string]bool{}
		for _, b := range p.InstalledBy {
			if _, ok := l.Bundles[b]; !ok {
				return fmt.Errorf("ledger: plugin %q installed_by %q, which is not an installed bundle", slug, b)
			}
			if seen[b] {
				return fmt.Errorf("ledger: plugin %q lists bundle %q twice", slug, b)
			}
			seen[b] = true
		}
	}
	return nil
}

// Marshal validates and renders the canonical bytes: 2-space indent, sorted
// map keys, _generated first, trailing newline. It does not change l.
func (l Ledger) Marshal() ([]byte, error) {
	c := l.Clone()
	c.normalize()
	if err := c.Validate(); err != nil {
		return nil, err
	}
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(c); err != nil {
		return nil, fmt.Errorf("ledger: encode: %w", err)
	}
	return buf.Bytes(), nil
}
