package commands

// Purpose: test extension regeneration with a local plugin registry fixture.
// Inputs: temporary projects and plugin archives; outputs: routes and plans.
// Constraints: no external registry, daemon, or production target.

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nself-org/cli/internal/bundle"
	"github.com/nself-org/cli/internal/compat"
	"github.com/nself-org/cli/internal/compat/compattest"
	"github.com/nself-org/cli/internal/errs"
	"github.com/nself-org/cli/internal/reconcile"
)

func extensionFixture(t *testing.T, env string) *l03Project {
	t.Helper()
	p := newL03Project(t, "dev-minimal")
	if env != "" {
		body, err := os.ReadFile(filepath.Join(p.project, ".env"))
		if err != nil {
			t.Fatal(err)
		}
		l03Write(t, filepath.Join(p.project, ".env"), string(body)+"\nENV="+env+"\n", 0o600)
	}
	t.Setenv("HOME", p.home)
	t.Setenv("NSELF_PLUGIN_DIR", p.plugins)
	cwd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	if err := os.Chdir(p.project); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chdir(cwd) })
	return p
}

func localPluginRegistry(t *testing.T) {
	t.Helper()
	files := map[string]string{
		"plugin.json":      `{"name":"zzfixture","version":"1.0.0","description":"fixture","category":"utility","license":"MIT"}`,
		"nginx/route.conf": "server { listen 80; server_name fixture.invalid; }\n",
	}
	var archive bytes.Buffer
	gz := gzip.NewWriter(&archive)
	tw := tar.NewWriter(gz)
	for _, name := range []string{"plugin.json", "nginx/route.conf"} {
		body := files[name]
		if err := tw.WriteHeader(&tar.Header{Name: name, Mode: 0o644, Size: int64(len(body))}); err != nil {
			t.Fatal(err)
		}
		if _, err := tw.Write([]byte(body)); err != nil {
			t.Fatal(err)
		}
	}
	if err := tw.Close(); err != nil {
		t.Fatal(err)
	}
	if err := gz.Close(); err != nil {
		t.Fatal(err)
	}
	sum := sha256.Sum256(archive.Bytes())
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if strings.HasSuffix(r.URL.Path, "/tarball") {
			_, _ = w.Write(archive.Bytes())
			return
		}
		_, _ = fmt.Fprintf(w, `{"plugins":[{"name":"zzfixture","version":"1.0.0","description":"fixture","category":"utility","tier":"free","license":"MIT","checksum":"%s"}]}`, hex.EncodeToString(sum[:]))
	}))
	t.Cleanup(server.Close)
	t.Setenv("NSELF_PLUGIN_REGISTRY", server.URL)
	t.Setenv("NSELF_PLUGIN_LICENSE_KEY", "fixture-key")
	if err := pluginInstallCmd.Flags().Set("skip-sbom-check", "true"); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = pluginInstallCmd.Flags().Set("skip-sbom-check", "false") })
}

func assertEmptyBuildPlan(t *testing.T, project string) {
	t.Helper()
	plan, err := reconcile.Compute(context.Background(), reconcile.Request{ProjectDir: project})
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Artifacts) != 0 {
		t.Fatalf("following build --plan changes %d artifacts: %+v", len(plan.Artifacts), plan.Artifacts)
	}
	if !plan.Empty {
		t.Fatalf("following build --plan is not empty: %+v", plan)
	}
}

func TestBundleInstallReconcileGolden(t *testing.T) {
	compattest.Both(t, func(t *testing.T) {
		p := extensionFixture(t, "")
		l03Write(t, filepath.Join(p.plugins, "fixture", "plugin.json"), `{"name":"fixture","version":"1.0.0"}`, 0o644)
		l03Write(t, filepath.Join(p.plugins, "fixture", "nginx", "route.conf"), "server { listen 80; server_name fixture.invalid; }\n", 0o644)
		old := bundleInstall
		bundleInstall = func(_ context.Context, slug string, opts bundle.InstallOpts) (*bundle.InstallResult, error) {
			if slug != "fixture" || opts.DryRun {
				t.Fatalf("unexpected bundle install: slug=%q dry=%v", slug, opts.DryRun)
			}
			return &bundle.InstallResult{Changed: true, Installed: []string{"fixture"}}, nil
		}
		t.Cleanup(func() { bundleInstall = old })
		if err := runBundleInstall(bundleInstallCmd, []string{"fixture"}); err != nil {
			t.Fatal(err)
		}
		route, err := os.ReadFile(filepath.Join(p.project, "nginx", "sites", "fixture-route.conf"))
		if err != nil {
			t.Fatal(err)
		}
		if want := "# Generated by nself build\nserver { listen 80; server_name fixture.invalid; }\n"; string(route) != want {
			t.Fatalf("bundle route golden:\n got %q\nwant %q", route, want)
		}
		if _, err := os.Stat(filepath.Join(p.project, ".nself", "state", "generated.json")); err != nil {
			t.Fatal(err)
		}
		assertEmptyBuildPlan(t, p.project)
	})
}

func TestBundleInstallUnchangedSkipsReconcile(t *testing.T) {
	p := extensionFixture(t, "")
	old := bundleInstall
	bundleInstall = func(_ context.Context, _ string, opts bundle.InstallOpts) (*bundle.InstallResult, error) {
		return &bundle.InstallResult{DryRun: opts.DryRun, Changed: false}, nil
	}
	t.Cleanup(func() { bundleInstall = old })
	if err := runBundleInstall(bundleInstallCmd, []string{"fixture"}); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(p.project, ".nself", "state", "generated.json")); !os.IsNotExist(err) {
		t.Fatalf("unchanged bundle regenerated: %v", err)
	}
}

func TestPluginInstallReconcileV15(t *testing.T) {
	compattest.Both(t, func(t *testing.T) {
		if !compat.V15() {
			return
		}
		p := extensionFixture(t, "")
		localPluginRegistry(t)
		if err := runPluginInstall(pluginInstallCmd, []string{"zzfixture"}); err != nil {
			t.Fatal(err)
		}
		route := filepath.Join(p.project, "nginx", "sites", "zzfixture-route.conf")
		data, err := os.ReadFile(route)
		if err != nil {
			t.Fatal(err)
		}
		if !strings.HasPrefix(string(data), "# Generated by nself build\n") {
			t.Fatalf("unmarked route: %q", data)
		}
		assertEmptyBuildPlan(t, p.project)
	})
}

func TestPluginRemoveReconcileV15(t *testing.T) {
	compattest.Both(t, func(t *testing.T) {
		if !compat.V15() {
			return
		}
		p := extensionFixture(t, "")
		localPluginRegistry(t)
		if err := runPluginInstall(pluginInstallCmd, []string{"zzfixture"}); err != nil {
			t.Fatal(err)
		}
		if err := runPluginRemove(pluginRemoveCmd, []string{"zzfixture"}); err != nil {
			t.Fatal(err)
		}
		if _, err := os.Stat(filepath.Join(p.project, "nginx", "sites", "zzfixture-route.conf")); !os.IsNotExist(err) {
			t.Fatalf("removed route remains: %v", err)
		}
		assertEmptyBuildPlan(t, p.project)
	})
}

func TestBundleRemoveReconcileBothModes(t *testing.T) {
	compattest.Both(t, func(t *testing.T) {
		p := extensionFixture(t, "")
		localPluginRegistry(t)
		if err := runPluginInstall(pluginInstallCmd, []string{"zzfixture"}); err != nil {
			t.Fatal(err)
		}
		if !compat.V15() {
			if err := reconcileAfterExtension(bundleInstallCmd, reconcile.Trigger{Kind: reconcile.TriggerBundle, Subject: "fixture"}); err != nil {
				t.Fatal(err)
			}
		}
		if err := bundle.LoadBytes([]byte(`{"schema_version":"2.0.0","bundles":{"fixture":{"display":"Fixture","tier":"paid","plugins":["zzfixture"]}}}`)); err != nil {
			t.Fatal(err)
		}
		t.Cleanup(func() { _ = bundle.LoadBytes([]byte(fixtureBundlesJSON)) })
		if err := runBundleRemove(bundleRemoveCmd, []string{"fixture"}); err != nil {
			t.Fatal(err)
		}
		if _, err := os.Stat(filepath.Join(p.project, "nginx", "sites", "zzfixture-route.conf")); !os.IsNotExist(err) {
			t.Fatalf("bundle route remains: %v", err)
		}
		assertEmptyBuildPlan(t, p.project)
	})
}

func TestPluginInstallProdClassRefusal(t *testing.T) {
	compattest.Both(t, func(t *testing.T) {
		if !compat.V15() {
			return
		}
		p := extensionFixture(t, "prod")
		localPluginRegistry(t)
		err := runPluginInstall(pluginInstallCmd, []string{"zzfixture"})
		if err == nil || errs.ExitCodeFor(err) != 4 || !strings.Contains(err.Error(), "E403") || !strings.Contains(err.Error(), "nself build --plan") {
			t.Fatalf("want exit 4 E403 with plan hint, got %v", err)
		}
		if _, err := os.Stat(filepath.Join(p.plugins, "zzfixture", "plugin.json")); err != nil {
			t.Fatalf("plugin files missing after refusal: %v", err)
		}
		if _, err := os.Stat(filepath.Join(p.project, "nginx", "sites", "zzfixture-route.conf")); !os.IsNotExist(err) {
			t.Fatalf("regeneration ran despite refusal: %v", err)
		}
	})
}
