// GENERATED BY tools/canongen — DO NOT HAND EDIT
// Source: internal/canon/canon.yaml and internal/canon/domains/*.yaml (go run ./tools/canongen).

package commands

var canonTable = canonTableT{
	Verbs: []string{"init", "start", "stop", "restart", "status", "logs", "doctor", "build", "reset", "clean", "add", "remove", "config", "db", "backup", "deploy", "update", "license", "mcp", "exec"},
	Moves: []canonRowT{
		{From: []string{"account"}, To: []string{"license", "account"}, Since: "v1.5.0", RemovalAt: "v1.6.0"},
		{From: []string{"env"}, To: []string{"config", "env"}, Since: "v1.5.0", RemovalAt: "v1.6.0"},
		{From: []string{"login"}, To: []string{"license", "login"}, Since: "v1.5.0", RemovalAt: "v1.6.0"},
		{From: []string{"logout"}, To: []string{"license", "logout"}, Since: "v1.5.0", RemovalAt: "v1.6.0"},
		{From: []string{"oauth"}, To: []string{"config", "oauth"}, Since: "v1.5.0", RemovalAt: "v1.6.0"},
		{From: []string{"secrets"}, To: []string{"config", "secrets"}, Since: "v1.5.0", RemovalAt: "v1.6.0"},
		{From: []string{"telemetry"}, To: []string{"config", "telemetry"}, Since: "v1.5.0", RemovalAt: "v1.6.0"},
		{From: []string{"trust"}, To: []string{"config", "trust"}, Since: "v1.5.0", RemovalAt: "v1.6.0"},
	},
}
