// GENERATED BY tools/canongen — DO NOT HAND EDIT
// Source: internal/canon/canon.yaml and internal/canon/domains/*.yaml (go run ./tools/canongen).

package commands

var canonTable = canonTableT{
	Verbs: []string{"init", "start", "stop", "restart", "status", "logs", "doctor", "build", "reset", "clean", "add", "remove", "config", "db", "backup", "deploy", "update", "license", "mcp", "exec"},
}
