package commands

// Canon engine: shared types, warnings and tree helpers (EPIC P7-CANON D2, D3).
//
// Purpose: the canon moves commands under hubs at startup, from data, so a move
// Ticket edits a canon fragment and never a command's source file. This file
// holds what the argv rewrite (canon_engine_argv.go), the tree application
// (canon_engine_tree.go) and prepareTree (tree_prepare.go) share.
//
// Inputs: canonTable (canon_moves_gen.go, generated by tools/canongen from the
// canon fragments). Nothing here parses YAML or calls canon.Load: the engine
// runs on every invocation (EPIC D15).
//
// Outputs: canonNote (one per argv rewrite), the once-per-process warning, and
// the helpers that find commands by their path words.
//
// Constraints: every v1.5 branch carries `// compat.V15(P7-CANON-21): <old> ->
// <new>`; v1.4 behaviour of every existing argv is unchanged.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strings"
	"sync"

	"github.com/nself-org/cli/internal/canon"
	"github.com/nself-org/cli/internal/errs"
	"github.com/nself-org/cli/internal/output"
	"github.com/spf13/cobra"
)

// canonTableT and canonRowT are the types of the generated table.
type (
	canonTableT = canon.Table
	canonRowT   = canon.TableRow
)

// Annotation keys the engine puts on the nodes it creates or relocates.
const (
	annMovedFrom = "nself.canon.moved-from" // value: the old path of a relocated node
	annStub      = "nself.canon.stub"       // value: the new path a stub points at
	annHub       = "nself.canon.hub"        // value: "1" on a created hub
)

// canonRemovalDefault is the release that removes an old spelling when its row
// names none (break-outs carry no removal_at).
const canonRemovalDefault = "v1.6.0"

// canonNote records one argv rewrite. Old and New are the matched prefix and
// its replacement ("env" -> "config env"), not the whole command line.
type canonNote struct {
	Kind      string // move, shim, retired, breakout
	Old, New  string
	RemovalAt string
	Plugin    string   // breakout: the plugin that must be mounted at New
	From, To  []string // the row's tokens
}

var canonWarn struct {
	mu   sync.Mutex
	done bool
}

// resetCanonWarning re-arms the once-per-process warning (tests only).
func resetCanonWarning() {
	canonWarn.mu.Lock()
	defer canonWarn.mu.Unlock()
	canonWarn.done = false
}

// warningsSilenced reports whether --no-deprecation-warnings or --quiet is on
// the command line. Flags are not parsed when the engine runs, so argv is read.
func warningsSilenced(args []string) bool {
	for _, a := range args {
		if a == "--no-deprecation-warnings" || a == "--quiet" {
			return true
		}
	}
	return false
}

// emitCanonWarning prints the first note's move notice once per process (stderr
// unless silenced) and, in JSON mode, records every note for meta.deprecations.
// old overrides the first note's old spelling (a legacy spelling the user typed)
// and final, when set, replaces its new path.
func emitCanonWarning(w io.Writer, args []string, notes []canonNote, old, final string) {
	if len(notes) == 0 {
		return
	}
	n := notes[0]
	if old == "" {
		old = n.Old
	}
	if final == "" {
		final = n.New
	}
	if output.JSONRequestedFromArgs(args) {
		output.AddDeprecation(old, final, n.RemovalAt)
		for _, x := range notes[1:] {
			output.AddDeprecation(x.Old, x.New, x.RemovalAt)
		}
	}
	canonWarn.mu.Lock()
	defer canonWarn.mu.Unlock()
	if canonWarn.done || warningsSilenced(args) {
		return
	}
	canonWarn.done = true
	_, _ = fmt.Fprintf(w, "warning: 'nself %s' moved to 'nself %s'; the old spelling is removed in %s\n", old, final, n.RemovalAt)
}

// removedError is the E410 error of a removed command.
func removedError(r canonRowT) error {
	from := strings.Join(r.From, " ")
	return errs.New("E410", fmt.Sprintf("'nself %s' was removed in %s: %s", from, r.Since, r.Message))
}

// walkNames returns the command at the path words below root (exact names, no
// aliases), or nil.
func walkNames(root *cobra.Command, words []string) *cobra.Command {
	cur := root
	for _, w := range words {
		var next *cobra.Command
		for _, c := range cur.Commands() {
			if c.Name() == w {
				next = c
				break
			}
		}
		if next == nil {
			return nil
		}
		cur = next
	}
	return cur
}

// isDescendant reports whether c lies below anc.
func isDescendant(c, anc *cobra.Command) bool {
	for p := c.Parent(); p != nil; p = p.Parent() {
		if p == anc {
			return true
		}
	}
	return false
}

// hasPrefix reports whether words starts with prefix (word by word).
func hasPrefix(words, prefix []string) bool {
	if len(prefix) == 0 || len(words) < len(prefix) {
		return false
	}
	for i, p := range prefix {
		if words[i] != p {
			return false
		}
	}
	return true
}

// helpOnlyParents are parent commands whose body only prints help: they accept
// and ignore any argument (D-0062). v1.5 gives them an unknown-subcommand
// validator, and the v1.4 skip rule does not treat them as commands that
// consume the tokens after them. Parents that do real work or read positional
// arguments (update, ci, health, admin, migrate, trust, account, bundle,
// plugin, db drift) are deliberately absent. TestHubUnknownSubcommand proves
// every entry is help-only.
var helpOnlyParents = []string{
	"access", "admin projects", "backup", "backup pitr", "config", "config features", "db", "db fk-index",
	"db hasura", "db hasura metadata", "db migrate", "db pgbouncer", "db pitr", "db rls", "db seed fixtures",
	"db soft-delete", "env target", "functions", "license", "oauth", "ops", "plugin marketplace", "runner",
	"secrets", "security", "server", "service", "telemetry", "template", "trust ssl",
}

// helpOnlySet resolves helpOnlyParents against root (call before relocation).
func helpOnlySet(root *cobra.Command) map[*cobra.Command]bool {
	set := map[*cobra.Command]bool{}
	for _, p := range helpOnlyParents {
		if c := walkNames(root, strings.Fields(p)); c != nil && c.HasSubCommands() && c.Args == nil {
			set[c] = true
		}
	}
	return set
}

// hubUnknownSubcommand is the D-0062 validator: a hub takes no arguments of its
// own, so any positional argument is an unknown subcommand (E401).
func hubUnknownSubcommand(cmd *cobra.Command, args []string) error {
	if len(args) == 0 {
		return nil
	}
	msg := fmt.Sprintf("unknown subcommand %q for %q", args[0], cmd.CommandPath())
	return errs.New("E401", sanitizeUsageMessage(msg))
}

// processArgs returns os.Args without the program name.
func processArgs() []string {
	if len(os.Args) < 2 {
		return nil
	}
	return os.Args[1:]
}

// rewriteProse replaces `nself <old>` with `nself <new>` in the Short, Long and
// Example of every relocated subtree, for moves and shims (not retired hubs: a
// hub forwards, it is not the same command).
func rewriteProse(u *undoList, t *canonTableT, src map[string]*cobra.Command) {
	var subs []canonRowT
	subs = append(append(subs, t.Moves...), t.Shims...)
	sort.SliceStable(subs, func(i, j int) bool { return len(subs[i].From) > len(subs[j].From) })
	seen := map[*cobra.Command]bool{}
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		if seen[c] {
			return
		}
		seen[c] = true
		short, long, example := c.Short, c.Long, c.Example
		c.Short, c.Long, c.Example = proseOf(short, subs), proseOf(long, subs), proseOf(example, subs)
		u.add(func() { c.Short, c.Long, c.Example = short, long, example })
		for _, ch := range c.Commands() {
			walk(ch)
		}
	}
	for _, r := range t.Moves {
		if n := src[rowKey("move", r)]; n != nil && n.Annotations[annMovedFrom] != "" {
			walk(n)
		}
	}
}

// proseOf rewrites whole-word `nself <from>` spellings (longest row first).
func proseOf(s string, subs []canonRowT) string {
	if !strings.Contains(s, "nself ") {
		return s
	}
	var b strings.Builder
	for i := 0; i < len(s); {
		if strings.HasPrefix(s[i:], "nself ") && (i == 0 || !isWordByte(s[i-1])) {
			if r, ok := proseMatch(s[i+6:], subs); ok {
				b.WriteString("nself " + strings.Join(r.To, " "))
				i += 6 + len(strings.Join(r.From, " "))
				continue
			}
		}
		b.WriteByte(s[i])
		i++
	}
	return b.String()
}

func proseMatch(rest string, subs []canonRowT) (canonRowT, bool) {
	for _, r := range subs {
		from := strings.Join(r.From, " ")
		if strings.HasPrefix(rest, from) && (len(rest) == len(from) || !isWordByte(rest[len(from)])) {
			return r, true
		}
	}
	return canonRowT{}, false
}

func isWordByte(b byte) bool {
	return b == '_' || b == '-' || (b >= '0' && b <= '9') || (b >= 'a' && b <= 'z') || (b >= 'A' && b <= 'Z')
}
