package commands

// Purpose: keep the "nself build" subprocess deploy spawns building the SAME
// project root deploy already resolved, and refuse to roll a restart against
// a compose file that build did not just (re)generate.
//
// Production incident 2026-09-20: deploy resolved workdir=/opt/nself-web
// (the nself-web Turborepo checkout root), but the "nself build" subprocess
// it spawned printed "Detected monorepo layout. Using backend as project
// root" (because /opt/nself-web/backend/.env exists) and generated
// backend/docker-compose.yml from backend/'s own env cascade — a different
// file, built from a different .env, than the docker-compose.yml the rolling
// restart that follows actually reads from workdir. runCLISelf spawns the
// subprocess with a fresh argv (just "build"), so it does not inherit
// whatever --no-monorepo state the outer "nself deploy" invocation had; the
// subprocess's own root.go PersistentPreRunE (config.DetectMonorepoRoot,
// which checks both "backend" and ".backend") runs its own independent
// monorepo detection against workdir, disagreeing with however the OUTER
// deploy command settled on workdir in the first place.
//
// Inputs:  workdir (deploy's already-resolved project root), the deploy
//          command's context, and its accumulated deployStep slice.
// Outputs: the extra "--no-monorepo" build arg when it's needed, and a
//          refusal error (no rolling restart attempted) when the compose
//          file that restart would read was not actually written by this
//          build call.
// Constraints: pure move-adjacent addition — does not change deploy's
//              existing step/error reporting shape (deployStep, finalize).

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/nself-org/cli/internal/build"
)

// composeFreshnessSkew absorbs filesystem mtime resolution and clock skew
// between this process and the one that wrote the file, so a legitimately
// fresh write is never rejected by a few hundred milliseconds of rounding.
const composeFreshnessSkew = 2 * time.Second

// projectHasOwnEnv reports whether workdir itself (not a backend/ or
// .backend/ subdirectory) already has at least one committed env cascade
// file — i.e. workdir is already a complete, self-sufficient nself project
// root and needs no further monorepo redirection by a subprocess.
func projectHasOwnEnv(workdir string) bool {
	for _, name := range []string{".env", ".env.dev", ".env.staging", ".env.prod"} {
		if _, err := os.Stat(filepath.Join(workdir, name)); err == nil {
			return true
		}
	}
	return false
}

// deployBuildArgs returns the argv (after "nself") for the "nself build"
// subprocess deploy spawns via runCLISelf. When workdir already has its own
// env cascade, "--no-monorepo" is added so the subprocess builds workdir
// itself rather than re-detecting and redirecting into a nested backend/ —
// which would write a second, different docker-compose.yml that the rolling
// restart (which always reads workdir/docker-compose.yml) never sees.
func deployBuildArgs(workdir string) []string {
	args := []string{"build"}
	if projectHasOwnEnv(workdir) {
		args = append(args, "--no-monorepo")
	}
	return args
}

// verifyDeployComposeFreshness refuses to continue when
// workdir/docker-compose.yml — the file the rolling restart that follows is
// about to read — was not actually (re)written by the build call that just
// ran. This is the direct guard against the production incident: had this
// check existed, the mismatched backend/docker-compose.yml would have been
// caught here instead of the rolling restart silently recreating
// postgres/hasura/auth against a stale/foreign root compose.
//
// Checks, in order:
//  1. The file exists at all.
//  2. It carries build.ComposeGeneratedHeader's marker, proving nself build
//     (not a hand edit, not some other mechanism) produced it.
//  3. Its mtime is at or after buildStart (minus composeFreshnessSkew),
//     proving THIS build call wrote it and not a stale copy from a
//     previous, possibly differently-rooted, run.
func verifyDeployComposeFreshness(workdir string, buildStart time.Time) error {
	composePath := filepath.Join(workdir, "docker-compose.yml")
	info, err := os.Stat(composePath)
	if err != nil {
		return fmt.Errorf(
			"deploy build did not produce %s: %w — the build may have generated its compose in a different directory (e.g. a monorepo %s); re-run from inside that directory or pass --no-monorepo",
			composePath, err, filepath.Join(workdir, "backend"))
	}
	if info.ModTime().Before(buildStart.Add(-composeFreshnessSkew)) {
		return fmt.Errorf(
			"refusing to roll a restart: %s was last modified %s, before this deploy's build started at %s — it was not regenerated by this deploy. This is the signature of a monorepo root mismatch: check for a stray %s",
			composePath, info.ModTime().Format(time.RFC3339), buildStart.Format(time.RFC3339), filepath.Join(workdir, "backend", "docker-compose.yml"))
	}
	data, err := os.ReadFile(composePath)
	if err != nil {
		return fmt.Errorf("reading %s to verify it was generated by nself build: %w", composePath, err)
	}
	if !strings.Contains(string(data), build.ComposeGeneratedHeader) {
		return fmt.Errorf("refusing to roll a restart: %s does not carry the nself-build generated-file marker — refusing to restart against a hand-edited or foreign compose file", composePath)
	}
	return nil
}

// runDeployBuildStep runs the "nself build" subprocess for a deploy (with
// deployBuildArgs' --no-monorepo guard) and then verifies the compose file
// the rolling restart is about to read was actually regenerated by that
// call. Returns the updated steps slice either way; a non-nil error means
// the caller must stop before attempting any restart.
func runDeployBuildStep(ctx context.Context, workdir string, steps []deployStep) ([]deployStep, error) {
	buildStart := time.Now()
	if err := runCLISelf(ctx, workdir, deployBuildArgs(workdir)...); err != nil {
		return append(steps, deployStep{Name: "Build images", Status: "failed"}), err
	}
	if err := verifyDeployComposeFreshness(workdir, buildStart); err != nil {
		return append(steps, deployStep{Name: "Build images", Status: "failed"}), err
	}
	return steps, nil
}
