package commands

import (
	"fmt"
	"os"

	migratebash "github.com/nself-org/cli/internal/migrate"
	"github.com/nself-org/cli/internal/migration"
	"github.com/nself-org/cli/internal/ui"

	"github.com/spf13/cobra"
)

var migrateCmd = &cobra.Command{
	Use:   "migrate",
	Short: "Detect and migrate legacy artifacts to the current nSelf version",
	Long: `Scan the current project directory for legacy nSelf artifacts and report
what needs to be updated for compatibility.

Examples:
  nself migrate                # Scan current directory for legacy artifacts
  nself migrate detect         # Alias for the default scan
  nself migrate run            # Migrate v1 project to v2
  nself migrate rollback       # Restore from the most recent backup
  nself migrate --from-bash    # Guide migration from v0.9.9 Bash-era config`,
	RunE: dataEnv(runMigrate),
}

var migrateDetectCmd = &cobra.Command{
	Use:   "detect",
	Short: "Detect v1 artifacts in the current project",
	RunE:  dataEnv(runMigrate),
}

var migrateRunCmd = &cobra.Command{
	Use:   "run",
	Short: "Migrate v1 project to v2",
	Long: `Perform a full v1 → v2 migration.

Steps:
  1. Detect v1 artifacts (idempotent — exits cleanly if already v2)
  2. Stop running containers gracefully
  3. Backup current state to .nself/backup/{timestamp}/
  4. Move nginx configs to v2 layout (nginx/sites/)
  5. Regenerate docker-compose.yml, nginx, and SSL certificates
  6. Print migration summary

On any failure, run 'nself migrate rollback' to restore the previous state.`,
	RunE: dataEnv(runMigrateRun),
}

var migrateRollbackCmd = &cobra.Command{
	Use:   "rollback",
	Short: "Restore a v1 backup created by migrate run",
	Long: `Restore the project from the most recent migration backup.

Use --backup to select a specific backup by timestamp.
Use --list to see all available backups.`,
	RunE: dataEnv(runMigrateRollback),
}

// migrateFromBashCmd handles the --from-bash migration path. Operators running
// nSelf v0.9.9 (Bash era) have a different project layout (.nself/config.sh,
// docker-compose.yml without the GENERATED header, etc.). This subcommand
// detects that layout and guides the operator through the steps needed to
// migrate to the current Go-based CLI.
//
// Automated migration is P98 scope. This release provides detection + guided
// output + the most automatable steps (config file backup, .env.dev generation).
var migrateFromBashCmd = &cobra.Command{
	Use:   "from-bash",
	Short: "Migrate a v0.9.9 Bash-era project to the current nSelf CLI",
	Long: `Detect and guide migration from a v0.9.9 Bash-era nSelf project.

The Bash-era CLI (v0.9.9) used a different project layout:
  - .nself/config.sh (shell variable config, not .env cascade)
  - docker-compose.yml without the "GENERATED BY nself build" header
  - nself.sh bootstrap script at project root

This command:
  1. Scans the current directory for v0.9.9 artifacts
  2. Prints a step-by-step migration checklist with exact commands
  3. Optionally runs automatable steps (backup, .env.dev generation)

The command is idempotent: re-running on an already-migrated project prints
"Nothing to migrate" and exits cleanly.

Full migration guide: https://github.com/nself-org/cli/wiki/Upgrading-from-v0.9.9

Examples:
  nself migrate from-bash            # Detect and print migration guide
  nself migrate from-bash --auto     # Run automatable steps after confirmation`,
	RunE: dataEnv(runMigrateFromBash),
}

func init() {
	migrateRollbackCmd.Flags().String("backup", "", "Specific backup timestamp to restore (e.g. 20260328-143022)")
	migrateRollbackCmd.Flags().Bool("list", false, "List available backups with timestamps and sizes")

	migrateFromBashCmd.Flags().Bool("auto", false, "Run automatable migration steps after prompting for confirmation")
	migrateFromBashCmd.Flags().Bool("yes", false, "Skip confirmation prompts (non-interactive/CI mode). Implies --auto.")

	// Also support `nself migrate --from-bash` as a top-level flag for discoverability.
	migrateCmd.Flags().Bool("from-bash", false, "Migrate from a v0.9.9 Bash-era project (alias for: nself migrate from-bash)")

	migrateCmd.AddCommand(migrateDetectCmd)
	migrateCmd.AddCommand(migrateRunCmd)
	migrateCmd.AddCommand(migrateRollbackCmd)
	migrateCmd.AddCommand(migrateFromBashCmd)
	RootCmd.AddCommand(migrateCmd)
}

func runMigrate(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}

	artifacts := migration.Detect(cwd)
	if len(artifacts) == 0 {
		ui.Success("No v1 artifacts detected. This project is ready for nSelf v2.")
	} else {
		_, _ = fmt.Fprintf(cmd.ErrOrStderr(), "\n%s %s\n\n", ui.C(ui.Yellow, ui.IconWarning), ui.C(ui.Bold, "Legacy nSelf v1 artifacts detected:"))

		tbl := ui.NewTable("Path", "Description", "Action")
		for _, a := range artifacts {
			tbl.AddRow(a.Path, a.Description, a.Action)
		}
		tbl.Render()

		fmt.Println()
		ui.Warn(fmt.Sprintf("%d v1 artifact(s) found. Review the table above and migrate each item.", len(artifacts)))
	}

	// CLI-R18: auto-detect and fix .env cascade-order drift. Unlike the v1
	// artifact scan above, this is safe to fix automatically wherever the
	// old effective value can be preserved unambiguously — see
	// internal/migrate/env_order.go for exactly which shapes qualify.
	envReport, err := migratebash.Migrate(cwd)
	if err != nil {
		return fmt.Errorf("checking .env cascade order: %w", err)
	}
	printEnvOrderSummary(cmd, envReport)

	return nil
}

func runMigrateRun(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}

	return migration.Run(cmd.Context(), cwd)
}

func runMigrateRollback(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return fmt.Errorf("getting working directory: %w", err)
	}

	listOnly, _ := cmd.Flags().GetBool("list")
	if listOnly {
		return printBackupList(cwd)
	}

	backupTimestamp, _ := cmd.Flags().GetString("backup")
	return migration.Rollback(cmd.Context(), cwd, backupTimestamp)
}

// printBackupList prints all available backups with timestamps and sizes.
func printBackupList(projectDir string) error {
	backups, err := migration.ListBackups(projectDir)
	if err != nil {
		return fmt.Errorf("listing backups: %w", err)
	}

	if len(backups) == 0 {
		ui.Warn("No backups found in .nself/backup/")
		return nil
	}

	fmt.Printf("\n%s %s\n\n", ui.C(ui.Blue, ui.IconInfo), ui.C(ui.Bold, "Available migration backups:"))

	tbl := ui.NewTable("Timestamp", "Size", "Path")
	for _, b := range backups {
		tbl.AddRow(b.Timestamp, formatBytes(b.Size), b.Dir)
	}
	tbl.Render()

	fmt.Println()
	ui.Info("Restore a backup: nself migrate rollback --backup <timestamp>")
	return nil
}
