package commands

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nself-org/cli/internal/config"
	"github.com/nself-org/cli/internal/docker"
)

func TestStartPullErrorSurfaced(t *testing.T) {
	t.Setenv("IMAGE_PINNING", "legacy")
	dir := t.TempDir()
	bin := filepath.Join(dir, "docker")
	if err := os.WriteFile(bin, []byte("#!/bin/sh\necho 'manifest unknown: 404' >&2\nexit 1\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	previous := newStartCompose
	newStartCompose = func(files ...string) *docker.Compose { return &docker.Compose{DockerPath: bin, ComposeFiles: files} }
	t.Cleanup(func() { newStartCompose = previous })
	_, _, err := startPostgresPhase(context.Background(), startOpts{quiet: true}, &config.Config{}, dir, nil)
	if err == nil || !strings.Contains(err.Error(), "E465") || !strings.Contains(err.Error(), "repository or tag missing") {
		t.Fatalf("first-run pull error was swallowed: %v", err)
	}
	if _, statErr := os.Stat(filepath.Join(dir, ".nself", ".first-run-complete")); !os.IsNotExist(statErr) {
		t.Fatalf("failed pull marked first run complete: %v", statErr)
	}
}

func TestStartPullNonFirstRunError(t *testing.T) {
	t.Setenv("IMAGE_PINNING", "lock")
	dir := t.TempDir()
	marker := filepath.Join(dir, ".nself", ".first-run-complete")
	if err := os.MkdirAll(filepath.Dir(marker), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(marker, nil, 0o600); err != nil {
		t.Fatal(err)
	}
	previous := ensureStartImages
	called := false
	ensureStartImages = func(_ context.Context, _ string, _ *docker.Compose, refs []docker.LockedImage) (bool, error) {
		called = true
		if len(refs) == 0 {
			t.Fatal("lock entries not passed to image check")
		}
		return false, errors.New("postgres: repository or tag missing")
	}
	t.Cleanup(func() { ensureStartImages = previous })
	_, _, err := startPostgresPhase(context.Background(), startOpts{}, &config.Config{}, dir, nil)
	if !called || err == nil || !strings.Contains(err.Error(), "E465") || !strings.Contains(err.Error(), "postgres: repository or tag missing") {
		t.Fatalf("non-first-run image failure was not surfaced: called=%v err=%v", called, err)
	}
}

func TestStartPullSkipPluginsKeepsMirror(t *testing.T) {
	t.Setenv("IMAGE_PINNING", "lock")
	dir := t.TempDir()
	state := filepath.Join(dir, ".nself", "state")
	if err := os.MkdirAll(state, 0o700); err != nil {
		t.Fatal(err)
	}
	base := filepath.Join(dir, "docker-compose.yml")
	plugin := filepath.Join(dir, "plugin.yml")
	for _, file := range []string{base, plugin} {
		if err := os.WriteFile(file, []byte("services: {}\n"), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(dir, ".nself", "compose-files.txt"), []byte(base+"\n"+plugin+"\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	bin := filepath.Join(dir, "docker-fake")
	if err := os.WriteFile(bin, []byte("#!/bin/sh\nexit 0\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	previousCompose, previousEnsure := newStartCompose, ensureStartImages
	newStartCompose = func(files ...string) *docker.Compose { return &docker.Compose{DockerPath: bin, ComposeFiles: files} }
	ensureStartImages = func(_ context.Context, _ string, _ *docker.Compose, _ []docker.LockedImage) (bool, error) {
		return true, os.WriteFile(filepath.Join(dir, docker.ImageOverrideFile), []byte("# GENERATED BY nself\nservices: {}\n"), 0o600)
	}
	t.Cleanup(func() { newStartCompose, ensureStartImages = previousCompose, previousEnsure })
	client, _, err := startPostgresPhase(context.Background(), startOpts{skipPlugins: true}, &config.Config{ProjectName: "l18skippluginsfixture"}, dir, []string{base})
	if err != nil {
		t.Fatal(err)
	}
	if len(client.ComposeFiles) != 2 || client.ComposeFiles[0] != base || client.ComposeFiles[1] != filepath.Join(dir, docker.ImageOverrideFile) {
		t.Fatalf("skip plugins lost mirror or re-enabled plugin: %v", client.ComposeFiles)
	}
}
