#!/usr/bin/env bash
# Purpose: regenerate the CLI command inventory from the cobra tree so SPORT F02,
#          the wiki command index, and the parity matrix stop being hand-typed.
#          Every prior count in those docs had drifted from the binary.
# Inputs:  none. Optional NSELF_SPORT_DIR to also refresh the SPORT F02 file
#          (it lives in the PPI, outside this repo, so it is only written when
#          that path is present on the machine running this).
# Outputs: .github/command-inventory.json  (machine-readable, committed)
#          .github/command-registry.json   (contract:cli.command-registry v1, the
#                                           v1.5 document `nself help --json`
#                                           serves; committed)
#          .github/wiki/Commands.md        (public command index, committed)
#          .github/wiki/Command-Canon.md   (every old spelling and where it went
#                                           in v1.5; the removal-plan PROSE block
#                                           is kept across runs; committed)
#          $NSELF_SPORT_DIR/F02-COMMAND-INVENTORY.md when the dir exists.
# Constraints: read-only against the source tree; must be idempotent so CI can
#              assert "regenerating produces no diff".
set -euo pipefail

cd "$(dirname "$0")/../.."

JSON_OUT=".github/command-inventory.json"
REG_OUT=".github/command-registry.json"
WIKI_OUT=".github/wiki/Commands.md"
CANON_OUT=".github/wiki/Command-Canon.md"

echo "Generating $JSON_OUT ..."
CGO_ENABLED=0 go run -mod=vendor ./tools/cmdinventory -format json -depth 2 > "$JSON_OUT"

echo "Generating $REG_OUT ..."
CGO_ENABLED=0 go run -mod=vendor ./tools/cmdinventory -format registry > "$REG_OUT"

echo "Generating $CANON_OUT ..."
CANON_TMP=$(mktemp)
CGO_ENABLED=0 go run -mod=vendor ./tools/cmdinventory -format canon -prose-from "$CANON_OUT" > "$CANON_TMP"
mv "$CANON_TMP" "$CANON_OUT"

COUNT=$(CGO_ENABLED=0 go run -mod=vendor ./tools/cmdinventory -format names | wc -l | tr -d ' ')

echo "Updating $WIKI_OUT ($COUNT top-level commands) ..."
# The curated grouped index in Commands.md is hand-written and worth keeping.
# Only the delimited block below is generated: it is the completeness guarantee
# that every registered command appears somewhere on the page.
BLOCK=$(mktemp)
trap 'rm -f "$BLOCK"' EXIT
{
  echo "<!-- BEGIN GENERATED:command-table -->"
  echo
  echo "## Complete index"
  echo
  echo "Generated from the cobra registration tree in \`cmd/commands/\`."
  echo "Run \`make cmd-inventory\` to refresh. **Total top-level commands: $COUNT**"
  echo
  CGO_ENABLED=0 go run -mod=vendor ./tools/cmdinventory -format markdown -depth 2 \
    | sed '$d' | sed '$d'
  echo
  echo "<!-- END GENERATED:command-table -->"
} > "$BLOCK"

python3 - "$WIKI_OUT" "$BLOCK" <<'PYEOF'
import sys
page_path, block_path = sys.argv[1], sys.argv[2]
block = open(block_path, encoding="utf-8").read().rstrip("\n")
page = open(page_path, encoding="utf-8").read()
BEGIN, END = "<!-- BEGIN GENERATED:command-table -->", "<!-- END GENERATED:command-table -->"
if BEGIN in page and END in page:
    head = page[: page.index(BEGIN)]
    tail = page[page.index(END) + len(END) :]
    page = head + block + tail
else:
    nav = "\n---\n← [[Home]] | [[_Sidebar]]"
    if page.rstrip().endswith("← [[Home]] | [[_Sidebar]]"):
        page = page.rstrip()[: -len("← [[Home]] | [[_Sidebar]]")].rstrip().rstrip("-").rstrip()
    page = page.rstrip("\n") + "\n\n" + block + nav + "\n"
open(page_path, "w", encoding="utf-8").write(page)
PYEOF

if [ -n "${NSELF_SPORT_DIR:-}" ] && [ -d "${NSELF_SPORT_DIR}" ]; then
  SPORT_OUT="${NSELF_SPORT_DIR}/F02-COMMAND-INVENTORY.md"
  echo "Generating $SPORT_OUT ..."
  {
    echo "# F02 — CLI Command Inventory"
    echo
    echo "<!-- GENERATED BY cli/scripts/sport/generate-f02.sh — DO NOT HAND EDIT -->"
    echo
    echo "Last generated: $(date -u +%Y-%m-%d)"
    echo "Source: \`cli/cmd/commands\` cobra registration tree (not a hand count)."
    echo
    echo "**Counts: $COUNT top-level commands.** Subcommands listed but not counted separately."
    echo
    CGO_ENABLED=0 go run -mod=vendor ./tools/cmdinventory -format markdown -depth 2 \
      | sed '$d' | sed '$d'
  } > "$SPORT_OUT"
else
  echo "NSELF_SPORT_DIR not set or missing — skipping SPORT F02 refresh."
fi

echo "Done. $COUNT top-level commands."
