#!/usr/bin/env bash
# generate-f17.sh — Generate SPORT F17-CLI-PLUGIN-COMPAT.md
# For the current CLI version (cli/.github/VERSION, or .github/facts.json when present), enumerates:
#   - Compatible stable plugins
#   - Compatible beta plugins
#   - EOL plugins
# Runs at E2 Stage 0. S58-T05.
#
# Usage: bash cli/scripts/sport/generate-f17.sh
# Output: $F17_OUT_FILE, default ${TMPDIR:-/tmp}/F17-CLI-PLUGIN-COMPAT.md. The output
#         directory must already exist; the retired .claude/docs/sport/ path is refused.
# Env:    F17_NSELF_ROOT overrides the directory holding plugins/ and plugins-pro/
#         (default: the nearest ancestor of cli/ that contains plugins/registry.json).
# Exit:   0 generated; 1 usage/data error (no CLI version, no plugin rows, bad output path).
#
# Bash 3.2 compatible (macOS system shell).

set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CLI_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Find the nSelf root (parent of plugins/): override, else walk up from cli/.
find_nself_root() {
  local d
  if [ -n "${F17_NSELF_ROOT:-}" ]; then
    printf "%s\n" "${F17_NSELF_ROOT}"
    return
  fi
  d="$(cd "${CLI_ROOT}/.." && pwd)"
  while [ "${d}" != "/" ]; do
    if [ -f "${d}/plugins/registry.json" ]; then
      printf "%s\n" "${d}"
      return
    fi
    d="$(dirname "${d}")"
  done
  cd "${CLI_ROOT}/.." && pwd
}
REPO_ROOT="$(find_nself_root)"

FREE_REGISTRY="${REPO_ROOT}/plugins/registry.json"
PRO_REGISTRY="${REPO_ROOT}/plugins-pro/registry.json"
OUT_FILE="${F17_OUT_FILE:-${TMPDIR:-/tmp}/F17-CLI-PLUGIN-COMPAT.md}"

case "${OUT_FILE}" in
  */.claude/docs/sport/*)
    printf "error: refusing to write to the retired .claude/docs/sport/ path: %s\n" "${OUT_FILE}" >&2
    exit 1
    ;;
esac
if [ ! -d "$(dirname "${OUT_FILE}")" ]; then
  printf "error: output directory does not exist: %s\n" "$(dirname "${OUT_FILE}")" >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  printf "error: jq is required to generate F17\n" >&2
  exit 1
fi

# Print the current CLI version: .github/facts.json (when present), else .github/VERSION.
extract_cli_versions() {
  local v=""
  if [ -f "${CLI_ROOT}/.github/facts.json" ]; then
    v="$(jq -r '.version // empty' "${CLI_ROOT}/.github/facts.json" 2>/dev/null || true)"
  fi
  if [ -z "${v}" ] && [ -f "${CLI_ROOT}/.github/VERSION" ]; then
    v="$(tr -d '[:space:]' < "${CLI_ROOT}/.github/VERSION")"
  fi
  v="${v#v}"
  if [ -z "${v}" ]; then
    printf "error: cannot read the CLI version from .github/facts.json or .github/VERSION\n" >&2
    return 1
  fi
  printf "%s\n" "${v}"
}

# Given a registry file, emit plugin names with their status and minNselfVersion.
# Output: <name>\t<status>\t<minCLI>\t<maxCLI>
registry_plugins() {
  local path="$1"
  [ -f "${path}" ] || return 0
  jq -r '
    .plugins | to_entries[] |
    .key as $name |
    .value as $p |
    [
      $name,
      ($p.status // "stable"),
      ($p.minNselfVersion // $p.min_nself_version // "0.0.0"),
      ($p.maxNselfVersion // "99.99.99")
    ] | @tsv
  ' "${path}"
}

# semver_lte: returns 0 (true) if $1 <= $2, else 1.
# Compares major.minor.patch numerically.
semver_lte() {
  local a="$1" b="$2"
  local a1 a2 a3 b1 b2 b3
  a1=$(printf "%s" "${a}" | cut -d. -f1)
  a2=$(printf "%s" "${a}" | cut -d. -f2)
  a3=$(printf "%s" "${a}" | cut -d. -f3)
  b1=$(printf "%s" "${b}" | cut -d. -f1)
  b2=$(printf "%s" "${b}" | cut -d. -f2)
  b3=$(printf "%s" "${b}" | cut -d. -f3)
  if [ "${a1}" -lt "${b1}" ]; then return 0; fi
  if [ "${a1}" -gt "${b1}" ]; then return 1; fi
  if [ "${a2}" -lt "${b2}" ]; then return 0; fi
  if [ "${a2}" -gt "${b2}" ]; then return 1; fi
  if [ "${a3}" -le "${b3}" ]; then return 0; fi
  return 1
}

# Collect all plugin data once.
ALL_PLUGINS_TSV="$(
  registry_plugins "${FREE_REGISTRY}"
  registry_plugins "${PRO_REGISTRY}"
)"

CLI_VERSIONS="$(extract_cli_versions)" || exit 1

# Fail closed: an empty plugin set would write a table with no rows.
if [ -z "$(printf "%s" "${ALL_PLUGINS_TSV}" | tr -d '[:space:]')" ]; then
  printf "error: no plugin rows read from %s or %s (registries missing, unreadable or empty)\n" \
    "${FREE_REGISTRY}" "${PRO_REGISTRY}" >&2
  exit 1
fi

# Write header.
cat > "${OUT_FILE}" << 'HEADER'
# F17 — CLI-PLUGIN-COMPAT

**SPORT — Single Point of Reference Truth**
Auto-generated by `cli/scripts/sport/generate-f17.sh`. Do not edit manually.
Regenerate: `bash cli/scripts/sport/generate-f17.sh`

S58-T05. Inverse of F18: for the current CLI version, which plugins are compatible?

HEADER

# Write one section per CLI version (the current version).
printf "%s\n" "${CLI_VERSIONS}" | while read -r cli_ver; do
  {
    printf "## v%s\n\n" "${cli_ver}"
    printf "| Plugin | Status | Notes |\n"
    printf "|--------|--------|-------|\n"
  } >> "${OUT_FILE}"

  printf "%s\n" "${ALL_PLUGINS_TSV}" | while IFS="	" read -r name status min_cli max_cli; do
    [ -n "${name}" ] || continue
    # Check if cli_ver falls within [min_cli, max_cli].
    if semver_lte "${min_cli}" "${cli_ver}" && semver_lte "${cli_ver}" "${max_cli}"; then
      label=""
      case "${status}" in
        eol) label=" **[EOL]**" ;;
        deprecated) label=" *[deprecated]*" ;;
        beta) label=" *(beta)*" ;;
        experimental) label=" *(experimental)*" ;;
        planned) label=" *(planned)*" ;;
      esac
      printf "| %-30s | %-12s | %s |\n" "${name}" "${status}" "${label}" >> "${OUT_FILE}"
    fi
  done

  printf "\n" >> "${OUT_FILE}"
done

# Summary.
TOTAL_CLI=$(printf "%s\n" "${CLI_VERSIONS}" | wc -l | tr -d ' ')
cat >> "${OUT_FILE}" << FOOTER

## Summary

- **CLI versions covered:** ${TOTAL_CLI}
- **Generated:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")
FOOTER

printf "F17 generated for CLI v%s: %s\n" "$(printf "%s\n" "${CLI_VERSIONS}" | head -1)" "${OUT_FILE}"
