package main

import (
	"bytes"
	"strings"
	"testing"

	"github.com/nself-org/cli/internal/compose"
)

func TestRun_CommittedLock(t *testing.T) {
	if err := compose.LockError(); err != nil {
		t.Fatalf("committed lock has error: %v", err)
	}
	images := compose.LockedImages()
	if len(images) == 0 {
		t.Fatal("committed lock is empty")
	}

	var buf bytes.Buffer
	if err := run([]string{"-platforms"}, &buf, images); err != nil {
		t.Fatalf("run failed: %v", err)
	}

	out := buf.String()
	lines := strings.Split(strings.TrimSpace(out), "\n")
	if len(lines) != len(images) {
		t.Errorf("expected %d lines, got %d", len(images), len(lines))
	}
}

func TestRun_FixtureLock(t *testing.T) {
	fixtureData := []byte(`{
		"_generated": "GENERATED BY tools/imagelock — DO NOT HAND EDIT",
		"schema_version": "1",
		"images": [
			{
				"name": "plugin/test",
				"role": "plugin",
				"repository": "docker.io/plugin/test",
				"version": "1.0",
				"index_digest": "sha256:1111111111111111111111111111111111111111111111111111111111111111",
				"platforms": {
					"linux/amd64": "sha256:2222222222222222222222222222222222222222222222222222222222222222",
					"linux/arm64": "sha256:3333333333333333333333333333333333333333333333333333333333333333"
				},
				"legacy_ref": "plugin/test:1.0",
				"license": "MIT",
				"source": "https://github.com/plugin/test",
				"mirror": null
			}
		]
	}`)

	f, err := compose.ParseLock(fixtureData)
	if err != nil {
		t.Fatalf("failed to parse fixture: %v", err)
	}

	var buf bytes.Buffer
	if err := run([]string{"-platforms"}, &buf, f.Images); err != nil {
		t.Fatalf("run failed: %v", err)
	}

	expected := "plugin/test\tdocker.io/plugin/test:1.0@sha256:1111111111111111111111111111111111111111111111111111111111111111\tlinux/amd64,linux/arm64\n"
	if buf.String() != expected {
		t.Errorf("expected %q, got %q", expected, buf.String())
	}
}

func TestRun_Empty(t *testing.T) {
	var buf bytes.Buffer
	err := run([]string{}, &buf, nil)
	if err == nil || !strings.Contains(err.Error(), "the image lock is empty") {
		t.Errorf("expected empty lock error, got %v", err)
	}
}
