// Generated schemas for the plugin catalog (contract:plugins.catalog v1) and
// releases.json (P7-PLUG-07).
//
// Purpose: schemas/catalog.v1.schema.json and schemas/releases.v1.schema.json come
// from the Go types in tools/catalog/model, the types the generator itself
// reads and writes; enums, versions and the checksum pattern come from that
// package's exported values. Slices are never null in a written document, so
// the schema says `array`; the catalog's nullable keys stay nullable.
package main

import (
	"github.com/nself-org/cli/internal/plugin/manifestv2"
	"github.com/nself-org/cli/tools/catalog/model"
)

const sha256Pattern = `^[0-9a-f]{64}$`

func init() {
	arr := map[string]any{"type": "array"}
	const row = "/properties/plugins/items"
	cat := []Override{
		{Pointer: "", Set: map[string]any{"description": "Plugin catalog (contract plugins.catalog v1): one row per slug and tier, bundles and counts. Generated by tools/catalog."}},
		{Pointer: "/properties/schema_version", Set: map[string]any{"const": model.CatalogVersion}},
		{Pointer: "/properties/plugins", Set: arr},
		{Pointer: row + "/properties/tier", Set: map[string]any{"enum": anyList(model.Tiers)}},
		{Pointer: row + "/properties/checksum", Set: map[string]any{"pattern": sha256Pattern}},
		{Pointer: row + "/properties/maturity", Set: map[string]any{"enum": anyList(manifestv2.Maturities)}},
		{Pointer: row + "/properties/service_kind", Set: map[string]any{"enum": anyList(manifestv2.ServiceKinds)}},
		{Pointer: row + "/properties/requires/properties/plugins", Set: arr},
		{Pointer: row + "/properties/requires/properties/postgres_extensions", Set: arr},
		{Pointer: row + "/properties/bundles", Set: arr},
		{Pointer: row + "/properties/commands/properties/subcommands", Set: arr},
		{Pointer: row + "/properties/release_signature/properties/alg", Set: map[string]any{"const": model.SigAlg}},
		{Pointer: "/properties/bundles/additionalProperties/properties/tier", Set: map[string]any{"enum": anyList(model.Tiers)}},
		{Pointer: "/properties/bundles/additionalProperties/properties/plugins", Set: arr},
		{Pointer: "/properties/counts/properties/schema_version", Set: map[string]any{"const": model.CountsVersion}},
	}
	for _, side := range []string{"free", "pro"} {
		cat = append(cat, Override{Pointer: "/properties/counts/properties/" + side + "/properties/nonInstallable", Set: arr})
	}
	for _, k := range []string{"sharedSlugs", "tierPairs", "duplicates"} {
		cat = append(cat, Override{Pointer: "/properties/counts/properties/overlap/properties/" + k, Set: arr})
	}
	Register(Spec{Out: "catalog.v1.schema.json", Type: model.Catalog{}, Overrides: cat})

	const rel = "/properties/releases/additionalProperties"
	Register(Spec{Out: "releases.v1.schema.json", Type: model.Releases{}, Overrides: []Override{
		{Pointer: "", Set: map[string]any{"description": "releases.json: release data (version, sha256, signature, tarball) written only by the release pipeline from published bytes."}},
		{Pointer: "/properties/schema_version", Set: map[string]any{"const": model.ReleasesVersion}},
		{Pointer: rel + "/properties/sha256", Set: map[string]any{"pattern": sha256Pattern}},
		{Pointer: rel + "/properties/release_signature/properties/alg", Set: map[string]any{"const": model.SigAlg}},
		{Pointer: rel + "/properties/platform_checksums", Set: map[string]any{"type": "object"}},
	}})
}
