// Schema generation for tools/schemagen.
//
// Purpose: turn one registered Spec into the bytes of its schema file and the
// whole set into a name -> bytes map (schemas plus index.json).
//
// Inputs: a *specSet. Outputs: map of path-under-schemas -> file bytes.
// Constraints: draft 2020-12; keys sorted (Go marshals maps in key order);
// 2-space indent; trailing newline; HTML never escaped; first-level $comment
// carries the GENERATED marker; $id is urn:nself:cli:schema:<name>:v<N>.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"reflect"
	"regexp"
	"strings"

	"github.com/google/jsonschema-go/jsonschema"
)

const (
	draftURI     = "https://json-schema.org/draft/2020-12/schema"
	generatedTag = "GENERATED BY tools/schemagen — DO NOT HAND EDIT"
	idPrefix     = "urn:nself:cli:schema:"
	indexOut     = "index.json"
)

var outVersion = regexp.MustCompile(`^(.*)\.v([0-9]+)\.schema\.json$`)

// schemaID derives the $id of a schema from its Out path.
func schemaID(out string) string {
	m := outVersion.FindStringSubmatch(out)
	if m == nil {
		return idPrefix + out
	}
	return idPrefix + strings.ReplaceAll(m[1], "/", ":") + ":v" + m[2]
}

// marshal renders v as the canonical file bytes.
func marshal(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// build infers the schema of s.Type, applies the overrides and the header.
func build(s Spec) ([]byte, error) {
	sch, err := jsonschema.ForType(reflect.TypeOf(s.Type), &jsonschema.ForOptions{})
	if err != nil {
		return nil, fmt.Errorf("%s: infer: %w", s.Out, err)
	}
	raw, err := json.Marshal(sch)
	if err != nil {
		return nil, fmt.Errorf("%s: marshal inferred schema: %w", s.Out, err)
	}
	var doc map[string]any
	if err := json.Unmarshal(raw, &doc); err != nil {
		return nil, fmt.Errorf("%s: decode inferred schema: %w", s.Out, err)
	}
	ovs := append(append([]Override(nil), typeOverrides[reflect.TypeOf(s.Type)]...), s.Overrides...)
	for _, o := range ovs {
		if err := applyOverride(doc, o); err != nil {
			return nil, fmt.Errorf("%s: %w", s.Out, err)
		}
	}
	doc["$schema"] = draftURI
	doc["$id"] = schemaID(s.Out)
	doc["$comment"] = generatedTag
	return marshal(doc)
}

// applyOverride merges o.Set into the node at o.Pointer.
func applyOverride(doc map[string]any, o Override) error {
	node, err := resolvePointer(doc, o.Pointer)
	if err != nil {
		return err
	}
	for k, v := range o.Set {
		node[k] = v
	}
	return nil
}

// resolvePointer walks a JSON Pointer through nested objects and returns the
// object it names. Array steps are not needed: schemas address items by
// "/items" and "/properties/<name>".
func resolvePointer(doc map[string]any, ptr string) (map[string]any, error) {
	if ptr == "" {
		return doc, nil
	}
	if !strings.HasPrefix(ptr, "/") {
		return nil, fmt.Errorf("override pointer %q must start with /", ptr)
	}
	cur := doc
	for _, part := range strings.Split(ptr[1:], "/") {
		part = strings.ReplaceAll(strings.ReplaceAll(part, "~1", "/"), "~0", "~")
		next, ok := cur[part].(map[string]any)
		if !ok {
			return nil, fmt.Errorf("override pointer %q: no object at %q", ptr, part)
		}
		cur = next
	}
	return cur, nil
}

// generate renders every spec of ss plus the index. It returns the files keyed
// by path under schemas/.
func generate(ss *specSet) (map[string][]byte, error) {
	files := map[string][]byte{}
	type entry struct {
		Path string `json:"path"`
		ID   string `json:"id"`
	}
	entries := []entry{}
	for _, s := range ss.sorted() {
		b, err := build(s)
		if err != nil {
			return nil, err
		}
		files[s.Out] = b
		entries = append(entries, entry{Path: s.Out, ID: schemaID(s.Out)})
	}
	idx, err := marshal(struct {
		Generated string  `json:"_generated"`
		Schemas   []entry `json:"schemas"`
	}{generatedTag, entries})
	if err != nil {
		return nil, err
	}
	files[indexOut] = idx
	return files, nil
}
