package compose

import (
	"fmt"

	"github.com/nself-org/cli/internal/config"

	"gopkg.in/yaml.v3"
)

// NginxConfDDir is the host-side directory for env-specific nginx conf.d files.
// Hand-managed, safe to edit directly.
const NginxConfDDir = "nginx/conf.d"

// NginxSitesDir is the host-side directory for generated nginx site configs.
// GENERATED by nself build — never hand-edit.
const NginxSitesDir = "nginx/sites"

// Generator builds a docker-compose.yml from project configuration.
type Generator struct {
	cfg     *config.Config
	profile ServiceSet

	// workDir anchors CS_N_ENV_FILE reads to the project root. Empty by
	// default (falls back to the process's current directory — see
	// loadCustomServiceEnvFile) so existing callers that never set it are
	// unaffected. Set via WithWorkDir when the caller has an explicit
	// project directory (e.g. the build orchestrator's st.workdir).
	workDir string
}

// NewGenerator creates a compose Generator from the given config using the
// default "app" profile (full service set — no regression from pre-profile builds).
func NewGenerator(cfg *config.Config) *Generator {
	set, _ := ProfileForName(ProfileApp)
	return &Generator{cfg: cfg, profile: set}
}

// NewGeneratorWithProfile creates a compose Generator that emits only the
// services permitted by the named profile.  Unknown profile names fall back to
// ProfileApp and are not treated as hard errors here (the caller should warn).
//
// Purpose: enable curated deployments (e.g. ProfileOps for an observability
// server) without touching the config layer.
// Inputs:  cfg — project configuration; name — profile selected by the user.
// Outputs: *Generator with profile gate set.
func NewGeneratorWithProfile(cfg *config.Config, name ProfileName) *Generator {
	set, _ := ProfileForName(name)
	return &Generator{cfg: cfg, profile: set}
}

// WithWorkDir sets the project root used to resolve CS_N_ENV_FILE paths and
// returns the same Generator for chaining. Callers that build compose from a
// known project directory (rather than assuming os.Getwd()) should always
// set this — see internal/build/orchestrator_build_compose.go.
func (g *Generator) WithWorkDir(dir string) *Generator {
	g.workDir = dir
	return g
}

// Generate produces the complete docker-compose.yml as YAML bytes.
// It marshals a DockerCompose struct via gopkg.in/yaml.v3.
func (g *Generator) Generate() ([]byte, error) {
	dc, err := g.buildDockerCompose()
	if err != nil {
		return nil, err
	}
	return yaml.Marshal(dc)
}

// buildDockerCompose constructs the full DockerCompose struct from config.
func (g *Generator) buildDockerCompose() (*DockerCompose, error) {
	dc := &DockerCompose{
		Name:     g.cfg.ProjectName,
		Networks: g.buildNetworks(),
		Volumes:  g.buildVolumes(),
		Services: make(map[string]ServiceConfig),
	}

	p := g.profile // service-set gate for the active profile

	// Core services — profile-gated.
	// postgres / hasura / auth / nginx are always required by ProfileApp and
	// ProfileOps; other profiles may exclude them via the ServiceSet booleans.
	//
	// When NSELF_EMBEDDED_PG=true, the Docker postgres container is omitted;
	// the embedded pglite/wasmtime runtime is booted by `nself start --embedded-pg`
	// and Hasura connects via a Unix-domain socket bridge.
	if p.CoreDB && !g.cfg.EmbeddedPG {
		dc.AddService("postgres", g.buildPostgresService())
	}

	if p.Hasura {
		hasuraSvc, err := g.buildHasuraService()
		if err != nil {
			return nil, fmt.Errorf("building hasura service: %w", err)
		}
		// When embedded PG is active, add the UDS socket volume mount so Hasura
		// can reach the pglite bridge at /var/run/postgres/pglite.sock.
		if g.cfg.EmbeddedPG {
			runtimeDirEnv := "${NSELF_RUNTIME_DIR:-.nself/embedded-pg}"
			hasuraSvc.Volumes = append(hasuraSvc.Volumes,
				runtimeDirEnv+"/pglite.sock.bridge:/var/run/postgres/pglite.sock",
			)
			// Remove the postgres health-check dependency — there is no postgres container.
			delete(hasuraSvc.DependsOn, "postgres")
		}
		dc.AddService("hasura", hasuraSvc)
	}

	if p.Auth {
		authSvc, err := g.buildAuthService()
		if err != nil {
			return nil, fmt.Errorf("building auth service: %w", err)
		}
		// When embedded PG is active, remove the postgres health-check dependency
		// from auth — there is no postgres container.
		if g.cfg.EmbeddedPG {
			delete(authSvc.DependsOn, "postgres")
		}
		dc.AddService("auth", authSvc)
	}

	// Optional services — profile-gated AND config-gated.
	// Init containers are inserted BEFORE the service that depends on them
	// so Docker Compose v5 sees definitions before depends_on references.
	if p.Redis && g.cfg.Redis.Enabled {
		dc.AddService("redis", g.buildRedisService())
	}
	if p.Minio && g.cfg.Minio.Enabled {
		dc.AddService("minio", g.buildMinioService())
	}
	if p.Mailpit && g.cfg.Mailpit.Enabled {
		dc.AddService("mailpit", g.buildMailpitService())
	}
	if p.AdminUI && g.cfg.Admin.Enabled {
		dc.AddService("nself-admin", g.buildAdminService())
	}
	if p.Functions && g.cfg.Functions.Enabled {
		dc.AddService("functions", g.buildFunctionsService())
	}
	// MLflow: handled by nself-mlflow free plugin (not in core)

	// Search (provider-based) — profile-gated.
	if p.Search && g.cfg.Search.Enabled {
		switch g.cfg.Search.Engine {
		case "meilisearch":
			dc.AddService("meilisearch-init", g.buildMeiliInitService())
			dc.AddService("meilisearch", g.buildMeiliService())
		case "typesense":
			dc.AddService("typesense", g.buildTypesenseService())
		}
	}

	// Monitoring: handled by nself-monitoring free plugin (not in core).
	// MLflow: handled by nself-mlflow free plugin (not in core).
	// OpsServices (forgejo, container-registry, functions-v8): contributed
	// by dedicated plugins when ProfileOps is active; no core compose blocks here.

	// Custom services (always pass-through — per-project overrides).
	for _, cs := range g.cfg.CustomServices {
		svcCfg, err := g.buildCustomService(cs)
		if err != nil {
			return nil, fmt.Errorf("building custom service %q: %w", cs.Name, err)
		}
		dc.AddService(cs.Name, svcCfg)
	}

	// Nginx — profile-gated (always last — depends on other services).
	// Skipped entirely when NGINX_FRONTED_BY names another stack's nginx as
	// this project's ingress: this project's own nginx container could never
	// bind 80/443 (the fronting stack's nginx already holds them) and would
	// sit forever as an unhealthy container `nself status` can never clear.
	// See NginxConfig.FrontedBy.
	if p.Nginx && g.cfg.Nginx.FrontedBy == "" {
		dc.AddService("nginx", g.buildNginxService(dc))
	}

	// Post-process: add logging, security, graceful shutdown to ALL services
	g.postProcess(dc)

	return dc, nil
}

// defaultPidsLimit is the default pids_limit applied to every non-init container.
// Prevents fork-bomb attacks by capping processes+threads to 100. Services
// that legitimately spawn more threads (e.g. postgres under high concurrency)
// override PidsLimit directly in their builder function.
const defaultPidsLimit int64 = 100

// defaultMemLimit is the fallback memory cap applied to any generated service
// that does not set an explicit Deploy.Resources.Limits.Memory. Ensures no
// container can run unbounded in production.
const defaultMemLimit = "512m"

// defaultCPULimit is the fallback CPU cap applied to any generated service
// that does not set an explicit Deploy.Resources.Limits.CPUs.
const defaultCPULimit = "1.0"

// defaultMemReservation is the soft memory reservation applied to every
// service, guaranteeing a minimum allocation while the hard cap remains
// Deploy.Resources.Limits.Memory.
const defaultMemReservation = "256m"

// postProcess applies logging, security, and graceful shutdown to all services.
func (g *Generator) postProcess(dc *DockerCompose) {
	// Init containers are short-lived by design and should not be capped
	// by the service-wide resource policy (they exit before any limit matters).
	initContainers := map[string]bool{
		"meilisearch-init": true,
	}

	for name, svc := range dc.Services {
		// Logging: json-file driver with configurable max-size and max-file
		svc.Logging = &LoggingConfig{
			Driver: "json-file",
			Options: map[string]string{
				"max-size": g.cfg.DockerLogMaxSize,
				"max-file": g.cfg.DockerLogMaxFile,
			},
		}

		// Graceful shutdown
		svc.StopGrace = g.cfg.DockerStopGrace

		// Resource limits: every long-running service gets CPU+memory caps.
		// Services that already set Deploy.Resources.Limits (postgres, hasura,
		// auth, nginx, redis, custom_services) keep their per-service value;
		// others (minio, mailpit, admin, functions, meilisearch, typesense)
		// inherit the platform default so no container runs unbounded.
		if !initContainers[name] {
			if svc.Deploy == nil {
				svc.Deploy = &DeployConfig{}
			}
			if svc.Deploy.Resources == nil {
				svc.Deploy.Resources = &Resources{}
			}
			if svc.Deploy.Resources.Limits == nil {
				svc.Deploy.Resources.Limits = &ResourceLimits{}
			}
			if svc.Deploy.Resources.Limits.Memory == "" {
				svc.Deploy.Resources.Limits.Memory = defaultMemLimit
			}
			if svc.Deploy.Resources.Limits.CPUs == "" {
				svc.Deploy.Resources.Limits.CPUs = defaultCPULimit
			}
			if svc.Deploy.Resources.Reservations == nil {
				svc.Deploy.Resources.Reservations = &ResourceLimits{
					Memory: defaultMemReservation,
				}
			}
		}

		// Security hardening — per-service profiles
		switch name {
		case "postgres":
			applySecurityToService(&svc, PostgresSecurity())
		case "minio":
			applySecurityToService(&svc, MinioSecurity())
		case "nginx":
			applySecurityToService(&svc, NginxSecurity())
		case "redis":
			applySecurityToService(&svc, RedisSecurity())
		default:
			applySecurityToService(&svc, DefaultSecurity())
		}

		// Fork-bomb prevention: apply pids limit via deploy.resources.limits.pids
		// to every non-init long-running service. Uses modern Docker Compose syntax
		// (deploy.resources.limits.pids) instead of legacy pids_limit field.
		if !initContainers[name] {
			if svc.Deploy.Resources.Limits.Pids == 0 {
				svc.Deploy.Resources.Limits.Pids = defaultPidsLimit
			}
		}

		dc.Services[name] = svc
	}
}

// Service builders are implemented in separate files:
// - core_services.go: postgres, hasura, auth, nginx
// - optional_services.go: redis, minio, mailpit, admin, functions, mlflow, search
// - monitoring_services.go: prometheus, grafana, loki, promtail, tempo, alertmanager, exporters, cadvisor
// - custom_services.go: user-defined custom services (CS_1..CS_10)
// - networks.go: docker-compose network definitions
// - volumes.go: docker-compose volume definitions
