package compose

// images_lock.go — the generated image lock and its accessors (ADR 0030,
// contract:cli.image-lock v1).
//
// Purpose: one place that answers "which image does the CLI run for service X".
// internal/compose/images.yaml is authored; images.lock.json is generated from
// it by tools/imagelock (network) and embedded here. Every generator reads its
// image through ImageRef or LockedRef; the literal scan test fails on any image
// literal outside this lock.
// Inputs: the embedded lock; the IMAGE_PINNING environment value.
// Outputs: Ref values, LockedImages() for probes, image strings per mode.
// Constraints: stdlib + internal/compat only. No network and no panics: a bad
// embedded lock surfaces as an error from ParseLock and an empty accessor; the
// unit tests fail first. Pinning is a mode (ADR 0021): legacy emits the exact
// pre-lock strings, lock emits repository:version@index_digest.

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
	"sync"

	"github.com/nself-org/cli/internal/compat"
)

//go:embed images.lock.json
var lockData []byte

// Lock file constants.
const (
	// LockHeader is the value of the first key, `_generated`.
	LockHeader = "GENERATED BY tools/imagelock — DO NOT HAND EDIT"
	// LockSchemaVersion is the lock's schema_version.
	LockSchemaVersion = "1"
	// EnvImagePinning selects the pinning mode: lock or legacy.
	EnvImagePinning = "IMAGE_PINNING"
	// PinningLock emits repository:version@index_digest.
	PinningLock = "lock"
	// PinningLegacy emits each entry's legacy_ref (byte-identical to before).
	PinningLegacy = "legacy"
)

// Image roles.
const (
	RoleCore, RoleOptional, RoleMonitoring, RoleTool, RolePlugin = "core", "optional", "monitoring", "tool", "plugin"
)

// Ref is one lock entry. JSON field order is the contract's.
type Ref struct {
	Name        string            `json:"name"`
	Role        string            `json:"role"`
	Repository  string            `json:"repository"`
	Version     string            `json:"version"`
	IndexDigest string            `json:"index_digest"`
	Platforms   map[string]string `json:"platforms"`
	LegacyRef   string            `json:"legacy_ref"`
	License     string            `json:"license"`
	Source      string            `json:"source"`
	Mirror      *string           `json:"mirror"`
}

// LockFile is the decoded images.lock.json.
type LockFile struct {
	Generated     string `json:"_generated"`
	SchemaVersion string `json:"schema_version"`
	Images        []Ref  `json:"images"`
}

// String is the lock-mode reference: repository:version@index_digest.
func (r Ref) String() string { return r.Repository + ":" + r.Version + "@" + r.IndexDigest }

// LegacyRepository is legacy_ref without its tag, the repository spelling the
// CLI used before the lock (for example `redis`, `docker.io/pgsty/minio`).
func (r Ref) LegacyRepository() string {
	if i := strings.LastIndex(r.LegacyRef, ":"); i > strings.LastIndex(r.LegacyRef, "/") {
		return r.LegacyRef[:i]
	}
	return r.LegacyRef
}

var digestRE = regexp.MustCompile(`^sha256:[0-9a-f]{64}$`)

// MarshalLock renders a lock deterministically: 2-space indent, trailing
// newline, no HTML escaping, platforms with sorted keys.
func MarshalLock(f *LockFile) ([]byte, error) {
	var b bytes.Buffer
	enc := json.NewEncoder(&b)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(f); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

// ParseLock decodes and validates a lock: header, schema version, entries
// sorted by name and unique, every field present, an index digest and at least
// linux/amd64, and a mirror that is null exactly for role plugin.
func ParseLock(data []byte) (*LockFile, error) {
	var f LockFile
	if err := json.Unmarshal(data, &f); err != nil {
		return nil, fmt.Errorf("image lock: %w", err)
	}
	if f.Generated != LockHeader {
		return nil, fmt.Errorf("image lock: _generated header is %q, want %q", f.Generated, LockHeader)
	}
	if f.SchemaVersion != LockSchemaVersion {
		return nil, fmt.Errorf("image lock: schema_version %q, want %q", f.SchemaVersion, LockSchemaVersion)
	}
	for i, r := range f.Images {
		if i > 0 && f.Images[i-1].Name >= r.Name {
			return nil, fmt.Errorf("image lock: entries must be sorted and unique by name (%q after %q)", r.Name, f.Images[i-1].Name)
		}
		if err := validateRef(r); err != nil {
			return nil, fmt.Errorf("image lock: %s: %w", r.Name, err)
		}
	}
	return &f, nil
}

func validateRef(r Ref) error {
	switch {
	case r.Name == "" || r.Repository == "" || r.Version == "" || r.LegacyRef == "":
		return fmt.Errorf("name, repository, version and legacy_ref are required")
	case r.Role != RoleCore && r.Role != RoleOptional && r.Role != RoleMonitoring && r.Role != RoleTool && r.Role != RolePlugin:
		return fmt.Errorf("role %q is not core, optional, monitoring, tool or plugin", r.Role)
	case !digestRE.MatchString(r.IndexDigest):
		return fmt.Errorf("index_digest %q is not sha256:<64 hex>", r.IndexDigest)
	case !digestRE.MatchString(r.Platforms["linux/amd64"]):
		return fmt.Errorf("platforms must include linux/amd64 with a digest")
	case r.Role == RolePlugin && r.Mirror != nil:
		return fmt.Errorf("role plugin has mirror null")
	case r.Role != RolePlugin && (r.Mirror == nil || *r.Mirror != "docker.io/nself/"+r.Name):
		return fmt.Errorf("mirror must be docker.io/nself/%s", r.Name)
	}
	for p, d := range r.Platforms {
		if !digestRE.MatchString(d) {
			return fmt.Errorf("platform %s digest %q is not sha256:<64 hex>", p, d)
		}
	}
	return nil
}

var (
	lockOnce  sync.Once
	lockRefs  []Ref
	lockIndex map[string]Ref
	lockErr   error
)

func loadLock() {
	lockOnce.Do(func() {
		f, err := ParseLock(lockData)
		if err != nil {
			lockErr = err
			return
		}
		lockRefs = f.Images
		lockIndex = make(map[string]Ref, len(f.Images))
		for _, r := range f.Images {
			lockIndex[r.Name] = r
		}
	})
}

// LockError reports why the embedded lock failed to load (nil when it is sound).
func LockError() error { loadLock(); return lockErr }

// LockedRef returns the lock entry for name.
func LockedRef(name string) (Ref, bool) {
	loadLock()
	r, ok := lockIndex[name]
	return r, ok
}

// LockedImages returns every lock entry sorted by name (a copy).
func LockedImages() []Ref {
	loadLock()
	out := make([]Ref, len(lockRefs))
	copy(out, lockRefs)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// PinningMode returns the active mode. IMAGE_PINNING=lock|legacy wins (the env
// cascade is loaded into the process environment before generation); unset or
// invalid falls back to the ADR 0021 default: legacy in v1.4, lock in v1.5.
func PinningMode() string {
	switch strings.ToLower(strings.TrimSpace(os.Getenv(EnvImagePinning))) {
	case PinningLock:
		return PinningLock
	case PinningLegacy:
		return PinningLegacy
	}
	// compat.V15(P7-LIVE-17): IMAGE_PINNING defaults to legacy -> lock
	if compat.V15() {
		return PinningLock
	}
	return PinningLegacy
}

// ImageRef returns the image string for lock entry name at the requested
// version. An empty version, or one equal to the lock version, means "the
// default": legacy_ref in legacy mode, repository:version@digest in lock mode.
// Any other version is an explicit user override and is used as given,
// unpinned, on the entry's pre-lock repository spelling. An unknown name yields
// "" (the tests assert every generator name exists).
func ImageRef(name, version string) string {
	r, ok := LockedRef(name)
	if !ok {
		return ""
	}
	v := strings.TrimSpace(version)
	if PinningMode() == PinningLock {
		if v == "" || v == r.Version {
			return r.String()
		}
		return r.LegacyRepository() + ":" + v
	}
	if v == "" {
		return r.LegacyRef
	}
	return r.LegacyRepository() + ":" + v
}
