// Command canongen renders the canon move table.
//
// Purpose:     the canon engine (cmd/commands/canon_engine*.go) reads a Go table
//
//	instead of parsing YAML on every invocation (EPIC P7-CANON D2, D15).
//	This tool turns the embedded canon fragments into that table.
//
// Inputs:      the embedded internal/canon/canon.yaml and domains/*.yaml.
//
// Outputs:     cmd/commands/canon_moves_gen.go (marker GENERATED BY tools/canongen),
//
//	or with -check an exit status: 0 when the file is current, 1 when not.
//
// Constraints: run from the cli module root (make canon). Output is deterministic.
//
//	go run -mod=vendor ./tools/canongen [-out path] [-check]
package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"

	"github.com/nself-org/cli/internal/canon"
)

// defaultOut is the generated table, relative to the module root.
const defaultOut = "cmd/commands/canon_moves_gen.go"

func main() {
	out := flag.String("out", defaultOut, "path of the generated table")
	check := flag.Bool("check", false, "exit 1 when the file differs from the rendered table instead of writing it")
	flag.Parse()
	os.Exit(run(*out, *check, os.Stdout, os.Stderr))
}

// run renders the table and writes or checks it; it returns the exit status.
func run(path string, check bool, stdout, stderr io.Writer) int {
	f, err := canon.LoadRaw()
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "canongen: %v\n", err)
		return 1
	}
	want := canon.RenderGoTable(f)
	if check {
		have, err := os.ReadFile(path)
		if err != nil {
			_, _ = fmt.Fprintf(stderr, "canongen: %v (run `make canon`)\n", err)
			return 1
		}
		if !bytes.Equal(have, want) {
			_, _ = fmt.Fprintf(stderr, "canongen: %s is stale; run `make canon` and commit the result\n", path)
			return 1
		}
		return 0
	}
	if err := os.WriteFile(path, want, 0o644); err != nil {
		_, _ = fmt.Fprintf(stderr, "canongen: %v\n", err)
		return 1
	}
	_, _ = fmt.Fprintf(stdout, "canongen: wrote %s\n", path)
	return 0
}
