package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunWritesThenChecks(t *testing.T) {
	p := filepath.Join(t.TempDir(), "table.go")
	var out, errb bytes.Buffer
	if rc := run(p, true, &out, &errb); rc != 1 {
		t.Fatalf("check of a missing file = %d, want 1", rc)
	}
	if rc := run(p, false, &out, &errb); rc != 0 {
		t.Fatalf("write = %d: %s", rc, errb.String())
	}
	b, err := os.ReadFile(p)
	if err != nil || !strings.HasPrefix(string(b), "// GENERATED BY tools/canongen") {
		t.Fatalf("generated file lacks the marker: %v %q", err, b)
	}
	if rc := run(p, true, &out, &errb); rc != 0 {
		t.Fatalf("check of a fresh file = %d: %s", rc, errb.String())
	}
	if err := os.WriteFile(p, append(b, []byte("// edit\n")...), 0o644); err != nil {
		t.Fatal(err)
	}
	if rc := run(p, true, &out, &errb); rc != 1 {
		t.Fatalf("check of an edited file = %d, want 1", rc)
	}
}
