#!/usr/bin/env bash

# templates.sh - Project templates for wizard

# Source platform compatibility utilities
TEMPLATES_DIR="$(dirname "${BASH_SOURCE[0]}")"

set -euo pipefail

source "$TEMPLATES_DIR/../../utils/platform-compat.sh" 2>/dev/null || true

# Get template name
get_template_name() {
  local template="$1"

  case "$template" in
    saas) echo "SaaS Application" ;;
    ecommerce) echo "E-commerce Platform" ;;
    blog) echo "Blog/CMS" ;;
    api) echo "API Backend" ;;
    mobile) echo "Mobile Backend" ;;
    custom) echo "Custom Configuration" ;;
    *) echo "Unknown" ;;
  esac
}

# Get template services
# Returns colon-delimited strings via export (Bash 3.2 safe, no associative arrays, no eval).
# Callers split on ":" with IFS=: read -ra to get individual service names.
get_template_services() {
  local template="$1"
  local required_var="$2"
  local optional_var="$3"

  local _req _opt
  case "$template" in
    saas)
      _req="PostgreSQL:Redis:Authentication"
      _opt="MinIO Storage:Email Service:Search:Admin UI:Functions:Dashboard"
      ;;
    ecommerce)
      _req="PostgreSQL:Redis:MinIO Storage:Search"
      _opt="RabbitMQ:Email Service:Admin UI:Dashboard:Functions"
      ;;
    blog)
      _req="PostgreSQL:Search"
      _opt="Redis:MinIO Storage:Email Service:Admin UI"
      ;;
    api)
      _req="PostgreSQL:Redis"
      _opt="RabbitMQ:MinIO Storage:Email Service:Monitoring"
      ;;
    mobile)
      _req="PostgreSQL:Redis:Authentication"
      _opt="MinIO Storage:Push Notifications:Functions:WebSockets"
      ;;
    custom)
      _req="PostgreSQL"
      _opt="Redis:MinIO Storage:Search:Email Service:RabbitMQ:Admin UI:Functions:Dashboard"
      ;;
    *)
      _req=""
      _opt=""
      ;;
  esac

  # Assign into caller-named variables via export (safe, no eval)
  export "${required_var}=${_req}"
  export "${optional_var}=${_opt}"
}

# Generate .env.local from template
generate_env_from_template() {
  local template="$1"
  local project_name="$2"
  local base_domain="$3"
  local db_name="$4"
  shift 4
  local services=("$@")

  # Start with base configuration
  cat >.env.local <<EOF
# nself Configuration - Generated by Wizard
# Project: $project_name
# Template: $(get_template_name "$template")
# Generated: $(date)

# ====================================================================
# CORE CONFIGURATION
# ====================================================================

# Project name (used for container names)
PROJECT_NAME=$project_name

# Base domain for all services
BASE_DOMAIN=$base_domain

# Environment
ENVIRONMENT=development

# ====================================================================
# DATABASE CONFIGURATION
# ====================================================================

# PostgreSQL settings
POSTGRES_DB=$db_name
POSTGRES_USER=${project_name}_user
POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 24)
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_VERSION=15-alpine

EOF

  # Add Redis if selected
  # Check if Redis is in services array
  local has_redis=false
  for service in "${services[@]}"; do
    if [[ "$service" == "Redis" ]]; then
      has_redis=true
      break
    fi
  done
  if [[ "$has_redis" == "true" ]]; then
    cat >>.env.local <<EOF
# ====================================================================
# REDIS CONFIGURATION
# ====================================================================

REDIS_ENABLED=true
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_VERSION=7-alpine

EOF
  fi

  # Add MinIO if selected
  # Check if MinIO Storage is in services array
  local has_minio=false
  for service in "${services[@]}"; do
    if [[ "$service" == "MinIO Storage" ]]; then
      has_minio=true
      break
    fi
  done
  if [[ "$has_minio" == "true" ]]; then
    cat >>.env.local <<EOF
# ====================================================================
# STORAGE CONFIGURATION
# ====================================================================

MINIO_ENABLED=true
MINIO_ROOT_USER=minioadmin
MINIO_ROOT_PASSWORD=minioadmin
MINIO_DEFAULT_BUCKETS=uploads,avatars,documents
MINIO_PORT=9000
MINIO_CONSOLE_PORT=9001

EOF
  fi

  # Add Search if selected
  # Check if Search is in services array
  local has_search=false
  for service in "${services[@]}"; do
    if [[ "$service" == "Search" ]]; then
      has_search=true
      break
    fi
  done
  if [[ "$has_search" == "true" ]]; then
    cat >>.env.local <<EOF
# ====================================================================
# SEARCH CONFIGURATION
# ====================================================================

SEARCH_ENABLED=true
SEARCH_ENGINE=meilisearch
SEARCH_HOST=search
SEARCH_PORT=7700
SEARCH_API_KEY=$(openssl rand -hex 32)

EOF
  fi

  # Add Email if selected
  # Check if Email Service is in services array
  local has_email=false
  for service in "${services[@]}"; do
    if [[ "$service" == "Email Service" ]]; then
      has_email=true
      break
    fi
  done
  if [[ "$has_email" == "true" ]]; then
    cat >>.env.local <<EOF
# ====================================================================
# EMAIL CONFIGURATION
# ====================================================================

EMAIL_ENABLED=true
EMAIL_PROVIDER=mailpit
EMAIL_FROM=${project_name}@${base_domain}
MAILPIT_PORT=1025
MAILPIT_UI_PORT=8025

EOF
  fi

  # Add RabbitMQ if selected
  # Check if RabbitMQ is in services array
  local has_rabbitmq=false
  for service in "${services[@]}"; do
    if [[ "$service" == "RabbitMQ" ]]; then
      has_rabbitmq=true
      break
    fi
  done
  if [[ "$has_rabbitmq" == "true" ]]; then
    cat >>.env.local <<EOF
# ====================================================================
# MESSAGE QUEUE CONFIGURATION
# ====================================================================

RABBITMQ_ENABLED=true
RABBITMQ_USER=rabbit
RABBITMQ_PASSWORD=localpass123
RABBITMQ_HOST=rabbitmq
RABBITMQ_PORT=5672
RABBITMQ_MANAGEMENT_PORT=15672

EOF
  fi

  # Add Admin UI if selected
  # Check if Admin UI is in services array
  local has_admin=false
  for service in "${services[@]}"; do
    if [[ "$service" == "Admin UI" ]]; then
      has_admin=true
      break
    fi
  done
  if [[ "$has_admin" == "true" ]]; then
    cat >>.env.local <<EOF
# ====================================================================
# ADMIN UI CONFIGURATION
# ====================================================================

ADMIN_ENABLED=true
ADMIN_PORT=3021
ADMIN_ROUTE=admin.\${BASE_DOMAIN}
ADMIN_USERNAME=admin

EOF
  fi

  # Add Authentication (Hasura) if selected
  # Check if Authentication is in services array
  local has_auth=false
  for service in "${services[@]}"; do
    if [[ "$service" == "Authentication" ]]; then
      has_auth=true
      break
    fi
  done
  if [[ "$has_auth" == "true" ]]; then
    cat >>.env.local <<EOF
# ====================================================================
# HASURA CONFIGURATION
# ====================================================================

HASURA_GRAPHQL_DATABASE_URL=postgresql://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@\${POSTGRES_HOST}:\${POSTGRES_PORT}/\${POSTGRES_DB}
HASURA_GRAPHQL_ADMIN_SECRET=localsecret123
HASURA_GRAPHQL_JWT_SECRET='{"type":"HS256","key":"your-256-bit-secret-key-here-minimum-32-chars"}'
HASURA_GRAPHQL_ENABLE_CONSOLE=true
HASURA_GRAPHQL_DEV_MODE=true
HASURA_PORT=8080
HASURA_ROUTE=api.\${BASE_DOMAIN}

# ====================================================================
# AUTHENTICATION CONFIGURATION
# ====================================================================

AUTH_ENABLED=true
AUTH_PORT=4000
AUTH_ROUTE=auth.\${BASE_DOMAIN}
AUTH_JWT_EXPIRES_IN=7d
AUTH_REFRESH_TOKEN_EXPIRES_IN=30d

EOF
  fi

  # Add SSL configuration
  cat >>.env.local <<EOF
# ====================================================================
# SSL CONFIGURATION
# ====================================================================

SSL_MODE=local
SSL_EMAIL=admin@${base_domain}

# ====================================================================
# NGINX CONFIGURATION
# ====================================================================

NGINX_CLIENT_MAX_BODY_SIZE=100M
NGINX_PROXY_TIMEOUT=300
NGINX_WORKER_CONNECTIONS=1024

EOF
}

# Create environment-specific files
create_environment_file() {
  local env="$1"
  local project_name="$2"
  local base_domain="$3"

  case "$env" in
    staging)
      cat >.env.staging <<EOF
# Staging Environment Configuration
# Extends: .env.local

ENVIRONMENT=staging
BASE_DOMAIN=staging.${base_domain}

# Use different database
POSTGRES_DB=${project_name}_staging

# Disable dev mode
HASURA_GRAPHQL_DEV_MODE=false
HASURA_GRAPHQL_ENABLE_CONSOLE=false

# Enable basic monitoring
MONITORING_ENABLED=true
EOF
      ;;

    production)
      cat >.env.prod <<EOF
# Production Environment Configuration
# DO NOT STORE SECRETS HERE - Use .env.secrets

ENVIRONMENT=production
BASE_DOMAIN=${base_domain}

# Database
POSTGRES_DB=${project_name}_prod
POSTGRES_VERSION=15

# Disable all dev features
HASURA_GRAPHQL_DEV_MODE=false
HASURA_GRAPHQL_ENABLE_CONSOLE=false
DEBUG=false

# Enable SSL
SSL_MODE=letsencrypt
SSL_EMAIL=admin@${base_domain}

# Enable monitoring
MONITORING_ENABLED=true
BACKUP_ENABLED=true
BACKUP_SCHEDULE="0 2 * * *"

# Security
ADMIN_2FA_ENABLED=true
RATE_LIMITING_ENABLED=true
EOF

      # Create .env.secrets template
      cat >.env.secrets <<EOF
# Production Secrets - ADD TO .gitignore!
# These values override .env.prod

# Database passwords
POSTGRES_PASSWORD=CHANGE_ME_$(openssl rand -hex 16)

# Service passwords
REDIS_PASSWORD=CHANGE_ME_$(openssl rand -hex 16)
MINIO_ROOT_PASSWORD=CHANGE_ME_$(openssl rand -hex 16)
RABBITMQ_PASSWORD=CHANGE_ME_$(openssl rand -hex 16)

# API Keys
HASURA_GRAPHQL_ADMIN_SECRET=CHANGE_ME_$(openssl rand -hex 32)
HASURA_GRAPHQL_JWT_SECRET='{"type":"HS256","key":"CHANGE_ME_$(openssl rand -hex 32)"}'
SEARCH_API_KEY=CHANGE_ME_$(openssl rand -hex 32)
ADMIN_PASSWORD_HASH=CHANGE_ME_$(openssl rand -hex 32)
ADMIN_SECRET_KEY=CHANGE_ME_$(openssl rand -hex 32)

# External services
SMTP_PASSWORD=
AWS_SECRET_ACCESS_KEY=
STRIPE_SECRET_KEY=
EOF

      # Set secure permissions (user read/write only)
      chmod 600 .env.secrets

      # Add to .gitignore
      if ! grep -q ".env.secrets" .gitignore 2>/dev/null; then
        echo ".env.secrets" >>.gitignore
      fi
      ;;
  esac
}

# Generate production secrets
generate_production_secrets() {
  log_info "Generating secure production secrets..."

  # Try to use the secrets library if available
  local secrets_lib="$INIT_MODULE_DIR/../../security/secrets.sh"
  if [[ -f "$secrets_lib" ]]; then
    source "$secrets_lib"

    # Use the library's generate_all function
    if command -v secrets::generate_all >/dev/null 2>&1; then
      secrets::generate_all ".env.secrets" false
      return $?
    fi
  fi

  # Fallback to manual generation if library not available
  log_warning "Using fallback secret generation"

  # Ensure openssl is available
  if ! command -v openssl >/dev/null 2>&1; then
    log_error "openssl not found - cannot generate secure secrets"
    log_info "Install openssl or use pre-generated secrets"
    return 1
  fi

  # Generate secure passwords (alphanumeric for passwords)
  local postgres_pass=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
  local redis_pass=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
  local minio_pass=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
  local rabbitmq_pass=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)
  local grafana_pass=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)

  # Generate secure secrets (hex for secrets/keys)
  local hasura_secret=$(openssl rand -hex 64)
  local jwt_key=$(openssl rand -hex 64)
  local cookie_secret=$(openssl rand -hex 32)
  local search_key=$(openssl rand -hex 32)

  # Create or overwrite .env.secrets
  cat > .env.secrets <<EOF
# Production Secrets - NEVER COMMIT TO VERSION CONTROL
# Generated by nself on $(date +%Y-%m-%d)
#
# IMPORTANT: Keep this file secure with permissions 600
# chmod 600 .env.secrets

# Database Credentials
POSTGRES_PASSWORD=$postgres_pass

# Hasura Security
HASURA_GRAPHQL_ADMIN_SECRET=$hasura_secret

# JWT Configuration
JWT_SECRET=$jwt_key

# Session Security
COOKIE_SECRET=$cookie_secret

# MinIO Storage (if enabled)
MINIO_ROOT_PASSWORD=$minio_pass

# Redis (if enabled)
REDIS_PASSWORD=$redis_pass

# Grafana (if monitoring enabled)
GRAFANA_ADMIN_PASSWORD=$grafana_pass
EOF

  # Set secure permissions
  chmod 600 .env.secrets

  # Ensure it's in .gitignore
  if [[ -f ".gitignore" ]]; then
    if ! grep -q "\.env\.secrets" .gitignore 2>/dev/null; then
      echo ".env.secrets" >> .gitignore
    fi
  else
    echo ".env.secrets" > .gitignore
  fi

  log_success "Generated secure secrets in .env.secrets"
  printf "\n"
  printf "  ${COLOR_YELLOW}IMPORTANT:${COLOR_RESET}\n"
  printf "  1. File permissions set to 600 (secure)\n"
  printf "  2. Added to .gitignore (will not be committed)\n"
  printf "  3. Back up securely for disaster recovery\n"
  printf "  4. Never share these secrets publicly\n"
  printf "\n"
}

# Export functions
export -f get_template_name
export -f get_template_services
export -f generate_env_from_template
export -f create_environment_file
export -f generate_production_secrets
