#!/usr/bin/env bash
# tools/imagebump/render-body.sh — render the weekly pin-bump PR body.
#
# Purpose: P7-HYG-34. Turns the files the workflow collected into one Markdown
# body: bumps, diff stat, lock check, probe, stack smoke, mirror plan.
# Usage:  tools/imagebump/render-body.sh <dir>   (body on stdout)
# Inputs: <dir>/bumps.txt (imagebump stdout), diffstat.txt, lockcheck.txt,
#         probe.txt and smoke.txt (dispatch-wait.sh stdout), probe.rc, smoke.rc,
#         mirror.out (status lines), mirror.plan (detail), mirror.rc. A missing
#         file renders as "not run".
# Output: Markdown. Sections are cut to fixed sizes so the body stays under
#         GitHub's 65536 character limit.
# Exit:   0; 2 usage error.
set -euo pipefail

[ "$#" -eq 1 ] && [ -d "$1" ] || { echo "usage: render-body.sh <dir>" >&2; exit 2; }
d="$1"

# cap FILE BYTES — the file's content cut to BYTES, with a marker when cut.
cap() {
  if [ ! -s "$1" ]; then echo "(empty)"; return 0; fi
  LC_ALL=C head -c "$2" "$1"
  if [ "$(wc -c < "$1")" -gt "$2" ]; then printf '\n[truncated]\n'; fi
}
# verdict RCFILE — PASS, FAIL or not run.
verdict() {
  if [ ! -f "$1" ]; then echo "not run"; elif [ "$(cat "$1")" = "0" ]; then echo "PASS"; else echo "FAIL"; fi
}
# field FILE KEY — value of a KEY=value line, or n/a.
field() { local v; v="$(grep "^$2=" "$1" 2>/dev/null | head -n1 | cut -d= -f2-)" || v=""; echo "${v:-n/a}"; }

echo "Weekly image pin bump (ADR 0030 section 4). Generated by tools/imagebump; review before merge."
echo
echo "## Proposed bumps"
echo '```'
cap "$d/bumps.txt" 8000
echo '```'
echo
echo "## Files changed"
echo '```'
cap "$d/diffstat.txt" 4000
echo '```'
echo
echo "## Checks"
echo
echo "| Check | Result | Run |"
echo "|---|---|---|"
echo "| imagelock -check | $(verdict "$d/lockcheck.rc") | |"
echo "| Image probe (default-images-pullable.yml) | $(verdict "$d/probe.rc") | $(field "$d/probe.txt" RUN_URL) |"
echo "| Stack smoke (e2e-golden-path.yml, source=local) | $(verdict "$d/smoke.rc") | $(field "$d/smoke.txt" RUN_URL) |"
echo "| Mirror plan (mirror-images.sh --plan) | $(verdict "$d/mirror.rc") | |"
echo
echo "## Mirror plan"
echo
if [ -f "$d/mirror.out" ]; then
  awk '$1 == "PRESENT" || $1 == "MISSING" || $1 == "DIFFERS" { c[$1]++ }
       END { printf "Status lines: PRESENT %d, MISSING %d, DIFFERS %d\n", c["PRESENT"], c["MISSING"], c["DIFFERS"] }' "$d/mirror.out"
else
  echo "Status lines: not run"
fi
echo
echo "Nothing is pushed to Docker Hub by this PR. The apply step runs after merge only when the repo variable IMAGE_MIRROR_APPLY is true."
echo
echo "<details><summary>Plan detail (stderr of mirror-images.sh --plan)</summary>"
echo
echo '```'
cap "$d/mirror.plan" 40000
echo '```'
echo
echo "</details>"
echo
echo "PRs opened with the workflow token do not start the normal PR checks. Close and reopen this PR to run them."
