package monitoring

import (
	"bytes"
	"fmt"
	"text/template"

	"github.com/nself-org/cli/internal/compose"
)

// TempoConfig captures the fields needed to render tempo.yml and the Tempo
// and OTEL Collector docker-compose service blocks.
//
// Tempo is Grafana's distributed tracing backend. It receives spans over OTLP
// (from the OTEL Collector) and makes them queryable from Grafana via the
// Tempo data source.
//
// OTEL Collector sits in front of Tempo and acts as a fan-out router: app
// services (Hasura, plugins, custom services) emit spans to the collector via
// OTLP gRPC (:4317) or OTLP HTTP (:4318), and the collector forwards them to
// Tempo's OTLP HTTP ingress (:4318).
type TempoConfig struct {
	// RetentionPeriod is how long traces are kept. Accepts Go-style durations
	// (e.g. "168h" = 7d, "720h" = 30d). Default: 168h (7 days).
	RetentionPeriod string

	// StoragePath is the bind-mount path inside the Tempo container where
	// trace data is persisted. Default: /var/tempo.
	StoragePath string

	// HTTPPort is the Tempo HTTP port used for UI + /api/v1/push ingress.
	// Default: 3200.
	HTTPPort int

	// OTLPGRPCPort is the gRPC port Tempo listens on for OTLP spans from the
	// OTEL Collector. Default: 4317.
	OTLPGRPCPort int
}

// DefaultTempoConfig returns nSelf's out-of-the-box Tempo settings:
// 7-day retention, local filesystem storage, standard ports.
func DefaultTempoConfig() *TempoConfig {
	return &TempoConfig{
		RetentionPeriod: "168h",
		StoragePath:     "/var/tempo",
		HTTPPort:        3200,
		OTLPGRPCPort:    4317,
	}
}

// TempoScrapeTarget returns the Prometheus ScrapeTarget for the Tempo service.
// Tempo exposes its own metrics at /metrics on the HTTP port.
func TempoScrapeTarget(cfg *TempoConfig) ScrapeTarget {
	port := 3200
	if cfg != nil && cfg.HTTPPort > 0 {
		port = cfg.HTTPPort
	}
	return ScrapeTarget{
		JobName:     "tempo",
		ServiceName: "tempo",
		Port:        port,
		Path:        "/metrics",
		Labels:      map[string]string{"service": "tempo"},
	}
}

const tempoYAMLTmpl = `# Generated by nself build — DO NOT HAND EDIT
stream_over_http_enabled: true

server:
  http_listen_port: {{.HTTPPort}}

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:{{.OTLPGRPCPort}}
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 5m

compactor:
  compaction:
    block_retention: {{.RetentionPeriod}}

storage:
  trace:
    backend: local
    local:
      path: {{.StoragePath}}/blocks
    wal:
      path: {{.StoragePath}}/wal

metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: nself
  storage:
    path: {{.StoragePath}}/generator/wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write
        send_exemplars: true

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]
`

// RenderTempoYAML returns the rendered tempo.yml bytes.
func RenderTempoYAML(cfg *TempoConfig) ([]byte, error) {
	if cfg == nil {
		return nil, fmt.Errorf("monitoring: nil TempoConfig")
	}
	tmpl, err := template.New("tempo").Parse(tempoYAMLTmpl)
	if err != nil {
		return nil, fmt.Errorf("monitoring: parse tempo template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return nil, fmt.Errorf("monitoring: execute tempo template: %w", err)
	}
	return buf.Bytes(), nil
}

// OTELCollectorConfig captures the fields needed to generate the OTEL
// Collector configuration. The collector receives OTLP from instrumented
// services and forwards spans to Tempo.
type OTELCollectorConfig struct {
	// TempoEndpoint is the OTLP HTTP endpoint the collector forwards to.
	// Default: http://tempo:4318.
	TempoEndpoint string

	// OTLPGRPCPort is the gRPC port the collector exposes to apps.
	// Default: 4317.
	OTLPGRPCPort int

	// OTLPHTTPPort is the HTTP port the collector exposes to apps.
	// Default: 4318.
	OTLPHTTPPort int
}

// DefaultOTELCollectorConfig returns nSelf's out-of-the-box OTEL Collector config.
func DefaultOTELCollectorConfig() *OTELCollectorConfig {
	return &OTELCollectorConfig{
		TempoEndpoint: "http://tempo:4318",
		OTLPGRPCPort:  4317,
		OTLPHTTPPort:  4318,
	}
}

const otelCollectorYAMLTmpl = `# Generated by nself build — DO NOT HAND EDIT
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:{{.OTLPGRPCPort}}
      http:
        endpoint: 0.0.0.0:{{.OTLPHTTPPort}}

processors:
  batch:
    timeout: 5s
    send_batch_size: 512

exporters:
  otlphttp:
    endpoint: {{.TempoEndpoint}}
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
`

// RenderOTELCollectorYAML returns the rendered otel-collector.yml bytes.
func RenderOTELCollectorYAML(cfg *OTELCollectorConfig) ([]byte, error) {
	if cfg == nil {
		return nil, fmt.Errorf("monitoring: nil OTELCollectorConfig")
	}
	tmpl, err := template.New("otelcollector").Parse(otelCollectorYAMLTmpl)
	if err != nil {
		return nil, fmt.Errorf("monitoring: parse otel collector template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, cfg); err != nil {
		return nil, fmt.Errorf("monitoring: execute otel collector template: %w", err)
	}
	return buf.Bytes(), nil
}

// TempoComposeService returns the docker-compose service definition for Tempo
// as a map suitable for YAML marshalling into the monitoring compose fragment.
//
// The service block:
//   - Uses grafana/tempo:latest
//   - Binds the config file from the monitoring/ directory generated by nself build
//   - Exposes HTTP (:3200) and OTLP gRPC (:4317)
//   - Persists trace data to a named volume
func TempoComposeService(cfg *TempoConfig) map[string]interface{} {
	if cfg == nil {
		cfg = DefaultTempoConfig()
	}
	return map[string]interface{}{
		"image":   compose.ImageRef("tempo", ""),
		"restart": "unless-stopped",
		"command": []string{"-config.file=/etc/tempo/tempo.yml"},
		"volumes": []string{
			"./monitoring/tempo.yml:/etc/tempo/tempo.yml:ro",
			"tempo_data:/var/tempo",
		},
		"ports": []string{
			fmt.Sprintf("127.0.0.1:%d:%d", cfg.HTTPPort, cfg.HTTPPort),
			fmt.Sprintf("127.0.0.1:%d:%d", cfg.OTLPGRPCPort, cfg.OTLPGRPCPort),
		},
		"networks": []string{"nself"},
		"labels": map[string]string{
			"com.docker.compose.project": "${NSELF_PROJECT_NAME}",
			"nself.service":              "tempo",
			"nself.monitoring":           "true",
		},
		// CPU limits prevent Tempo's trace ingestion from starving other services
		// under load. 0.5 CPU cap with 0.1 reservation matches the nSelf default
		// for optional services.
		"deploy": map[string]interface{}{
			"resources": map[string]interface{}{
				"limits": map[string]interface{}{
					"cpus": "0.5",
				},
				"reservations": map[string]interface{}{
					"cpus": "0.1",
				},
			},
		},
	}
}

// OTELCollectorComposeService returns the docker-compose service definition
// for the OTEL Collector.
//
// The service block:
//   - Uses otel/opentelemetry-collector-contrib:latest
//   - Binds the config file from the monitoring/ directory
//   - Exposes OTLP gRPC (:4317) and OTLP HTTP (:4318) for apps to push spans
//   - Depends on Tempo being up before starting
func OTELCollectorComposeService(cfg *OTELCollectorConfig) map[string]interface{} {
	if cfg == nil {
		cfg = DefaultOTELCollectorConfig()
	}
	return map[string]interface{}{
		"image":   compose.ImageRef("otel-collector", ""),
		"restart": "unless-stopped",
		"command": []string{"--config=/etc/otelcol/otel-collector.yml"},
		"volumes": []string{
			"./monitoring/otel-collector.yml:/etc/otelcol/otel-collector.yml:ro",
		},
		"ports": []string{
			fmt.Sprintf("127.0.0.1:%d:%d", cfg.OTLPGRPCPort, cfg.OTLPGRPCPort),
			fmt.Sprintf("127.0.0.1:%d:%d", cfg.OTLPHTTPPort, cfg.OTLPHTTPPort),
		},
		"depends_on": []string{"tempo"},
		"networks":   []string{"nself"},
		"labels": map[string]string{
			"com.docker.compose.project": "${NSELF_PROJECT_NAME}",
			"nself.service":              "otel-collector",
			"nself.monitoring":           "true",
		},
		// CPU limits prevent the OTEL Collector's batch processor from consuming
		// unbounded CPU during trace bursts.
		"deploy": map[string]interface{}{
			"resources": map[string]interface{}{
				"limits": map[string]interface{}{
					"cpus": "0.5",
				},
				"reservations": map[string]interface{}{
					"cpus": "0.1",
				},
			},
		},
	}
}
