// Registry fragment: plugin codes (E100-E149). Registered from init() through
// Register; see codes.go for the rules and codes_blocks.go for the allocation.
package errs

func init() {
	Register(
		CodeEntry{
			Code:       "E100",
			Category:   "plugin",
			Summary:    "Plugin not found",
			DefaultWhy: "The requested plugin does not exist in the registry.",
			DefaultFix: "Run 'nself plugin list' to see available plugins.",
			DocsPath:   "reference/error-codes#e100",
			Exit:       1,
		},
		CodeEntry{
			Code:       "E101",
			Category:   "plugin",
			Summary:    "Invalid license key",
			DefaultWhy: "The license key format is invalid.",
			DefaultFix: "License keys start with 'nself_pro_' followed by 32+ characters. Check your key.",
			DocsPath:   "reference/error-codes#e101",
			Exit:       3,
		},
		CodeEntry{
			Code:       "E102",
			Category:   "plugin",
			Summary:    "License tier insufficient",
			DefaultWhy: "Your license tier does not include this plugin.",
			DefaultFix: "Upgrade your plan at https://nself.org/pricing",
			DocsPath:   "reference/error-codes#e102",
			Exit:       3,
		},
		CodeEntry{
			Code:       "E103",
			Category:   "plugin",
			Summary:    "License expired",
			DefaultWhy: "The license key has expired.",
			DefaultFix: "Renew your license at https://nself.org/account",
			DocsPath:   "reference/error-codes#e103",
			Exit:       3,
		},
		CodeEntry{
			Code:       "E104",
			Category:   "plugin",
			Summary:    "License validation failed (network)",
			DefaultWhy: "Cannot reach the license server and no valid local cache exists.",
			DefaultFix: "Check your internet connection. Previously validated licenses work offline for 7 days.",
			DocsPath:   "reference/error-codes#e104",
			Exit:       3,
		},
		CodeEntry{
			Code:       "E105",
			Category:   "plugin",
			Summary:    "Circular plugin dependency",
			DefaultWhy: "Plugin dependency graph contains a cycle.",
			DefaultFix: "Report this as a bug at https://github.com/nself-org/cli/issues",
			DocsPath:   "reference/error-codes#e105",
			Exit:       1,
		},
		CodeEntry{
			Code:       "E106",
			Category:   "plugin",
			Summary:    "Invalid plugin manifest",
			DefaultWhy: "The plugin manifest is missing a required field or contains an invalid value.",
			DefaultFix: "Fix the manifest fields named in the message, or reinstall the plugin: nself add <plugin>",
			DocsPath:   "reference/error-codes#e106",
			Exit:       1,
		},
		CodeEntry{
			Code:       "E107",
			Category:   "plugin",
			Summary:    "Plugin is not signed",
			DefaultWhy: "A stable plugin release has no signature, so the install was refused.",
			DefaultFix: "Use a release that carries a signature, or report the missing signature to the plugin publisher.",
			DocsPath:   "reference/error-codes#e107",
			Exit:       1,
		},
		CodeEntry{
			Code:       "E108",
			Category:   "plugin",
			Summary:    "Plugin checksum missing",
			DefaultWhy: "A stable plugin release has no checksum, so the install was refused.",
			DefaultFix: "Use a release that carries a checksum, or report the missing checksum to the plugin publisher.",
			DocsPath:   "reference/error-codes#e108",
			Exit:       1,
		},
		CodeEntry{
			Code:       "E109",
			Category:   "plugin",
			Summary:    "Duplicate plugin slug",
			DefaultWhy: "The same plugin slug is served by more than one unrelated registry entry.",
			DefaultFix: "Report this to the registry maintainers. Install the plugin by its full registry name if one is shown.",
			DocsPath:   "reference/error-codes#e109",
			Exit:       1,
		},
		CodeEntry{
			Code:       "E110",
			Category:   "plugin",
			Summary:    "License does not entitle this plugin tier",
			DefaultWhy: "The installed license does not include the pro tier of this plugin.",
			DefaultFix: "Check your plan with: nself license status. Upgrade at https://nself.org/pricing if the tier is missing.",
			DocsPath:   "reference/error-codes#e110",
			Exit:       3,
		},
	)
}
