// Registry fragment: database codes (E200-E249). Registered from init() through
// Register; see codes.go for the rules and codes_blocks.go for the allocation.
package errs

func init() {
	Register(
		CodeEntry{
			Code:       "E200",
			Category:   "database",
			Summary:    "Database not running",
			DefaultWhy: "PostgreSQL container is not running or not accepting connections.",
			DefaultFix: "Run 'nself start' to start all services, or 'nself doctor' to diagnose.",
			DocsPath:   "reference/error-codes#e200",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E201",
			Category:   "database",
			Summary:    "Migration failed",
			DefaultWhy: "A database migration could not be applied.",
			DefaultFix: "Check the migration SQL for errors. Run 'nself db migrate --status' to see pending migrations.",
			DocsPath:   "reference/error-codes#e201",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E202",
			Category:   "database",
			Summary:    "Backup failed",
			DefaultWhy: "Database backup operation failed.",
			DefaultFix: "Ensure sufficient disk space and that the database is running.",
			DocsPath:   "reference/error-codes#e202",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E203",
			Category:   "database",
			Summary:    "Migration validation failed",
			DefaultWhy: "The migration dry run found an error in the migration SQL before anything was applied.",
			DefaultFix: "Fix the SQL named in the message and run the migration again. No changes were applied.",
			DocsPath:   "reference/error-codes#e203",
			Exit:       1,
		},
		CodeEntry{
			Code:       "E204",
			Category:   "database",
			Summary:    "Migration prerequisite missing",
			DefaultWhy: "An object the migration depends on does not exist in the live schema.",
			DefaultFix: "Apply the earlier migrations first: nself db migrate. Run nself doctor if the schema looks wrong.",
			DocsPath:   "reference/error-codes#e204",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E205",
			Category:   "database",
			Summary:    "Backup not found",
			DefaultWhy: "The requested backup file or backup ID does not exist.",
			DefaultFix: "List available backups with: nself backup list",
			DocsPath:   "reference/error-codes#e205",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E206",
			Category:   "database",
			Summary:    "Backup verification failed",
			DefaultWhy: "The backup failed its integrity check, so it may be corrupt or incomplete.",
			DefaultFix: "Create a fresh backup: nself backup create. Do not restore from the failed file.",
			DocsPath:   "reference/error-codes#e206",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E207",
			Category:   "database",
			Summary:    "Backup restore failed",
			DefaultWhy: "The backup could not be restored into the database.",
			DefaultFix: "Check that the database is running and has enough disk space, then retry. Run nself doctor for details.",
			DocsPath:   "reference/error-codes#e207",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E208",
			Category:   "database",
			Summary:    "Backup encryption failed",
			DefaultWhy: "The backup could not be encrypted.",
			DefaultFix: "Check the backup encryption key setting and that the key file is readable, then retry.",
			DocsPath:   "reference/error-codes#e208",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E209",
			Category:   "database",
			Summary:    "Backup decryption failed",
			DefaultWhy: "The backup could not be decrypted with the configured key.",
			DefaultFix: "Check that the key matches the one used to create the backup, then retry.",
			DocsPath:   "reference/error-codes#e209",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E210",
			Category:   "database",
			Summary:    "Remote backup operation failed",
			DefaultWhy: "Copying a backup to or from the remote destination failed.",
			DefaultFix: "Check the remote destination settings and network access, then retry.",
			DocsPath:   "reference/error-codes#e210",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E211",
			Category:   "database",
			Summary:    "Backup prune failed",
			DefaultWhy: "Old backups could not be removed according to the retention policy.",
			DefaultFix: "Check file permissions on the backup directory and the remote destination, then retry.",
			DocsPath:   "reference/error-codes#e211",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E212",
			Category:   "database",
			Summary:    "WAL archive failed",
			DefaultWhy: "PostgreSQL could not archive a write-ahead log segment.",
			DefaultFix: "Check free disk space and the archive destination. Run nself doctor for details.",
			DocsPath:   "reference/error-codes#e212",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E213",
			Category:   "database",
			Summary:    "Disaster recovery drill failed",
			DefaultWhy: "The disaster recovery drill did not complete successfully.",
			DefaultFix: "Read the drill report for the failing step, fix it and run the drill again.",
			DocsPath:   "reference/error-codes#e213",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E214",
			Category:   "database",
			Summary:    "Standby promotion failed",
			DefaultWhy: "The standby database could not be promoted to primary.",
			DefaultFix: "Check the standby status and replication lag, then retry the promotion.",
			DocsPath:   "reference/error-codes#e214",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E215",
			Category:   "database",
			Summary:    "Disaster recovery rollback failed",
			DefaultWhy: "Rolling back a disaster recovery step failed.",
			DefaultFix: "Check the current database role on each node before taking any further action.",
			DocsPath:   "reference/error-codes#e215",
			Exit:       2,
		},
		CodeEntry{
			Code:       "E216",
			Category:   "database",
			Summary:    "Split-brain fence failed",
			DefaultWhy: "The old primary could not be fenced, so two nodes might accept writes.",
			DefaultFix: "Stop the old primary by hand before continuing, then retry the fence step.",
			DocsPath:   "reference/error-codes#e216",
			Exit:       2,
		},
	)
}
