package reconcile

import (
	"bytes"
	"io/fs"
	"path"
	"strings"
)

// FrontingPrefix marks a path that belongs to the fronting stack rather than
// the project (contract: `@fronting/<rel>`).
const FrontingPrefix = "@fronting/"

// generatedMarker is matched case-insensitively in the first markerWindow
// bytes. It covers every spelling the CLI stamps: "Generated by nself build",
// "GENERATED BY nself build", "Generated by nself".
const (
	generatedMarker = "generated by nself"
	markerWindow    = 512
)

// File is one artifact's bytes and permission bits.
type File struct {
	Data []byte
	Perm fs.FileMode
}

// ArtifactSet maps a normalised path (project-relative, "/" separators, or
// "@fronting/<rel>") to its file. Diff compares two sets. A nil set is empty.
type ArtifactSet map[string]File

// Kind classifies a path per the change-plan contract.
//
// Inputs: an artifact path. Outputs: compose (docker-compose*.yml|yaml at the
// root), nginx (nginx/**), ssl (ssl/**), env (.env* basenames and
// .nself/compose.env), hasura, monitoring, postgres-init (postgres/init/**),
// lock (nself.lock.yaml), state (.nself/**), else other. A "@fronting/"
// prefix is ignored for classification, so the fronting stack's nginx tree is
// still nginx. Env is checked before state so .nself/compose.env is env.
func Kind(p string) ArtifactKind {
	p = cleanPath(p)
	if IsEnvPath(p) {
		return KindEnv
	}
	switch {
	case p == "nself.lock.yaml":
		return KindLock
	case isComposeFile(p):
		return KindCompose
	case underDir(p, "nginx"):
		return KindNginx
	case underDir(p, "ssl"):
		return KindSSL
	case underDir(p, "hasura"):
		return KindHasura
	case underDir(p, "monitoring"):
		return KindMonitoring
	case underDir(p, "postgres/init"):
		return KindPostgresInit
	case underDir(p, ".nself"):
		return KindState
	}
	return KindOther
}

// IsEnvPath reports whether a path is env-kind: a basename starting with
// ".env" (.env, .env.dev, .env.computed, .env.secrets) or .nself/compose.env.
// Env-kind artifacts are always redacted in diffs and plans.
func IsEnvPath(p string) bool {
	p = cleanPath(p)
	return strings.HasPrefix(path.Base(p), ".env") || p == ".nself/compose.env"
}

// IsGenerated reports whether the first 512 bytes of data carry the nself
// generated-file marker, matched case-insensitively.
func IsGenerated(data []byte) bool {
	if len(data) > markerWindow {
		data = data[:markerWindow]
	}
	return bytes.Contains(bytes.ToLower(data), []byte(generatedMarker))
}

// cleanPath strips a fronting prefix, a leading "./" and backslashes.
func cleanPath(p string) string {
	p = strings.ReplaceAll(p, "\\", "/")
	p = strings.TrimPrefix(p, FrontingPrefix)
	return strings.TrimPrefix(p, "./")
}

// underDir reports whether p is inside dir (not dir itself).
func underDir(p, dir string) bool {
	return strings.HasPrefix(p, dir+"/")
}

// isComposeFile matches root-level docker-compose*.yml and .yaml files.
func isComposeFile(p string) bool {
	if strings.Contains(p, "/") || !strings.HasPrefix(p, "docker-compose") {
		return false
	}
	return strings.HasSuffix(p, ".yml") || strings.HasSuffix(p, ".yaml")
}
