package reconcile

import (
	"reflect"
	"testing"
)

func TestEnvClassTable(t *testing.T) {
	cases := map[string]EnvClassName{
		"prod": ClassProd, "production": ClassProd, "staging": ClassProd, "stage": ClassProd,
		"PROD": ClassProd, " Production ": ClassProd,
		"dev": ClassDev, "development": ClassDev, "local": ClassDev, "test": ClassDev, "": ClassDev, "qa": ClassDev,
	}
	for in, want := range cases {
		if got := EnvClass(in); got != want {
			t.Errorf("EnvClass(%q) = %q, want %q", in, got, want)
		}
	}
	norm := map[string]string{"production": "prod", "stage": "staging", "Development": "dev", "devel": "dev", "local": "local", "": ""}
	for in, want := range norm {
		if got := NormalizeEnv(in); got != want {
			t.Errorf("NormalizeEnv(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestKindTable(t *testing.T) {
	cases := map[string]ArtifactKind{
		"docker-compose.yml": KindCompose, "docker-compose.plugin.yml": KindCompose, "sub/docker-compose.yml": KindOther,
		"nginx/sites/a.conf": KindNginx, "@fronting/nginx/sites/a.conf": KindNginx,
		"ssl/certificates/x/fullchain.pem": KindSSL, "@fronting/ssl/x": KindSSL,
		".env": KindEnv, ".env.dev": KindEnv, ".env.computed": KindEnv, ".nself/compose.env": KindEnv,
		"hasura/metadata/a.yaml": KindHasura, "monitoring/prom.yml": KindMonitoring,
		"postgres/init/01.sql": KindPostgresInit, ".nself/state/generated.json": KindState,
		"nself.lock.yaml": KindLock, "README.md": KindOther, "nginx": KindOther, "./nginx/a.conf": KindNginx,
	}
	for in, want := range cases {
		if got := Kind(in); got != want {
			t.Errorf("Kind(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestIsGenerated(t *testing.T) {
	for _, s := range []string{"# Generated by nself build - DO NOT EDIT\n", "# GENERATED BY nself build - DO NOT HAND EDIT\n", "x\n# generated by nself\n"} {
		if !IsGenerated([]byte(s)) {
			t.Errorf("%q should be generated", s)
		}
	}
	late := make([]byte, 600)
	copy(late[520:], "generated by nself")
	if IsGenerated(late) || IsGenerated([]byte("plain\n")) || IsGenerated(nil) {
		t.Error("marker outside the first 512 bytes or absent must not match")
	}
}

// build finalises a plan on env with the given parts.
func build(t *testing.T, env string, arts []Artifact, effs []Effect, items []ContainerItem) Plan {
	t.Helper()
	p := Plan{Command: CmdBuild, Env: env, Artifacts: arts, Effects: effs, Containers: Containers{Known: true, Items: items}}
	if err := p.Finalize(); err != nil {
		t.Fatal(err)
	}
	return p
}

func TestClassificationTable(t *testing.T) {
	hand := func(a Action) []Artifact {
		return []Artifact{{Kind: KindNginx, Path: "nginx/a.conf", Action: a, HandEdited: true, DiffLines: 1}}
	}
	cases := []struct {
		name    string
		arts    []Artifact
		effs    []Effect
		items   []ContainerItem
		reasons []string
	}{
		{"hand-edited change", hand(ActionChange), nil, nil, []string{"hand-edited file overwritten: nginx/a.conf"}},
		{"hand-edited remove", hand(ActionRemove), nil, nil, []string{"hand-edited file removed: nginx/a.conf"}},
		{"hand-edited add is not destructive", hand(ActionAdd), nil, nil, []string{}},
		{"plain change", []Artifact{{Kind: KindCompose, Path: "docker-compose.yml", Action: ActionChange}}, nil, nil, []string{}},
		{"orphan remove", nil, []Effect{{Kind: EffectOrphanRemove, Target: "nginx/sites/x.conf"}}, nil, []string{"orphan removed: nginx/sites/x.conf"}},
		{"plugin remove", nil, []Effect{{Kind: EffectPluginRemove, Target: "ai"}}, nil, []string{"plugin removed: ai"}},
		{"stateful recreate this command", nil, nil,
			[]ContainerItem{{Service: "postgres", Action: ContainerRecreate, Stateful: true, AppliedBy: AppliedThisCommand}},
			[]string{"stateful container recreated: postgres"}},
		{"stateful recreate next start", nil, nil,
			[]ContainerItem{{Service: "postgres", Action: ContainerRecreate, Stateful: true, AppliedBy: AppliedNextStart}}, []string{}},
		{"stateless recreate this command", nil, nil,
			[]ContainerItem{{Service: "nginx", Action: ContainerRecreate, AppliedBy: AppliedThisCommand}}, []string{}},
		{"reasons sorted and unique", nil,
			[]Effect{{Kind: EffectPluginRemove, Target: "b"}, {Kind: EffectPluginRemove, Target: "a"}, {Kind: EffectPluginRemove, Target: "a"}}, nil,
			[]string{"plugin removed: a", "plugin removed: b"}},
	}
	for _, c := range cases {
		p := build(t, "dev", c.arts, c.effs, c.items)
		if !reflect.DeepEqual(p.DestructiveReasons, c.reasons) || p.Destructive != (len(c.reasons) > 0) {
			t.Errorf("%s: destructive=%v reasons=%v, want %v", c.name, p.Destructive, p.DestructiveReasons, c.reasons)
		}
	}
}

func TestRequiresConfirmation(t *testing.T) {
	arts := []Artifact{{Kind: KindCompose, Path: "docker-compose.yml", Action: ActionChange, DiffLines: 2}}
	for env, want := range map[string]bool{"prod": true, "production": true, "staging": true, "stage": true, "dev": false, "": false} {
		if p := build(t, env, arts, nil, nil); p.RequiresConfirmation != want {
			t.Errorf("env %q: requires_confirmation = %v", env, p.RequiresConfirmation)
		}
		if p := build(t, env, nil, nil, nil); p.RequiresConfirmation {
			t.Errorf("env %q: an empty plan never needs confirmation", env)
		}
	}
	// A container item alone makes a plan non-empty; "none" does not.
	if p := build(t, "prod", nil, nil, []ContainerItem{{Service: "a", Action: ContainerUnknown}}); p.Empty || !p.RequiresConfirmation {
		t.Errorf("unknown container item: %+v", p)
	}
	if p := build(t, "prod", nil, nil, []ContainerItem{{Service: "a", Action: ContainerNone}}); !p.Empty {
		t.Errorf("none item must be dropped: %+v", p)
	}
}

func TestHandEditedPaths(t *testing.T) {
	p := build(t, "dev", []Artifact{
		{Path: "b", Action: ActionChange, HandEdited: true}, {Path: "a", Action: ActionRemove, HandEdited: true},
		{Path: "c", Action: ActionAdd, HandEdited: true}, {Path: "d", Action: ActionChange},
	}, nil, nil)
	if got := HandEditedPaths(p); !reflect.DeepEqual(got, []string{"a", "b"}) {
		t.Errorf("got %v", got)
	}
}
