package reconcile

import (
	"fmt"
	"math/rand"
	"reflect"
	"strings"
	"testing"
)

func set(kv ...string) ArtifactSet {
	s := ArtifactSet{}
	for i := 0; i < len(kv); i += 2 {
		s[kv[i]] = File{Data: []byte(kv[i+1]), Perm: 0o644}
	}
	return s
}

func TestDiffAddChangeRemoveSortedUnchangedOmitted(t *testing.T) {
	before := set("z.conf", "a\n", "same.yml", "x\n", "nginx/gone.conf", "# Generated by nself build\none\ntwo\n", "m.txt", "1\n2\n3\n")
	after := set("z.conf", "a\nb\n", "same.yml", "x\n", "a-new.txt", "p\nq\n", "m.txt", "1\n3\n4\n")
	hand := func(p string) bool { return p == "nginx/gone.conf" || p == "a-new.txt" }
	got := Diff(before, after, hand)
	want := []Artifact{
		{Kind: KindOther, Path: "a-new.txt", Action: ActionAdd, DiffLines: 2},
		{Kind: KindOther, Path: "m.txt", Action: ActionChange, DiffLines: 2 + 0},
		{Kind: KindNginx, Path: "nginx/gone.conf", Action: ActionRemove, Generated: true, HandEdited: true, DiffLines: 3},
		{Kind: KindOther, Path: "z.conf", Action: ActionChange, DiffLines: 1},
	}
	want[1].DiffLines = 2 // delete "2", insert "4"
	if !reflect.DeepEqual(got, want) {
		t.Errorf("Diff =\n%+v\nwant\n%+v", got, want)
	}
	if len(Diff(nil, nil, nil)) != 0 || Diff(nil, nil, nil) == nil {
		t.Error("empty diff must be a non-nil empty slice")
	}
}

func TestDiffLinesMatchesReference(t *testing.T) {
	rng := rand.New(rand.NewSource(7))
	for n := 0; n < 200; n++ {
		a, b := randLines(rng), randLines(rng)
		x, y := intern(a, b)
		d, ops := myers(x, y, true)
		if want := len(a) + len(b) - 2*lcsLen(a, b); d != want {
			t.Fatalf("case %d: D=%d want %d", n, d, want)
		}
		// replaying the script must rebuild b from a.
		var out []string
		for _, op := range ops {
			switch op.Tag {
			case '=', '+':
				out = append(out, b[op.B])
			}
		}
		if strings.Join(out, "") != strings.Join(b, "") {
			t.Fatalf("case %d: script does not rebuild b", n)
		}
	}
}

func randLines(rng *rand.Rand) []string {
	out := make([]string, rng.Intn(12))
	for i := range out {
		out[i] = fmt.Sprintf("l%d\n", rng.Intn(5))
	}
	return out
}

// lcsLen is the textbook O(nm) reference.
func lcsLen(a, b []string) int {
	t := make([][]int, len(a)+1)
	for i := range t {
		t[i] = make([]int, len(b)+1)
	}
	for i := 1; i <= len(a); i++ {
		for j := 1; j <= len(b); j++ {
			if a[i-1] == b[j-1] {
				t[i][j] = t[i-1][j-1] + 1
			} else {
				t[i][j] = max(t[i-1][j], t[i][j-1])
			}
		}
	}
	return t[len(a)][len(b)]
}

func TestDiffOverCapReportsMinusOne(t *testing.T) {
	big := strings.Repeat("line\n", MaxDiffLines+1)
	got := Diff(set("big.txt", big), set("big.txt", big+"more\n"), nil)
	if len(got) != 1 || got[0].Action != ActionChange || got[0].DiffLines != -1 {
		t.Errorf("got %+v", got)
	}
	if u := Unified("big.txt", []byte(big), []byte(big+"more\n")); u != "" {
		t.Errorf("unified over the cap must be empty, got %d bytes", len(u))
	}
	atCap := strings.Repeat("line\n", MaxDiffLines)
	if got := Diff(set("f", atCap), set("f", "x\n"+atCap[5:]), nil); got[0].DiffLines != 2 {
		t.Errorf("at the cap the diff is computed: %+v", got)
	}
}

func TestUnifiedHunks(t *testing.T) {
	a := "1\n2\n3\n4\n5\n6\n7\n8\n9\n10\n"
	b := "1\n2\nTHREE\n4\n5\n6\n7\n8\n9\n10\n11"
	want := "--- a/f.txt\n+++ b/f.txt\n" +
		"@@ -1,6 +1,6 @@\n 1\n 2\n-3\n+THREE\n 4\n 5\n 6\n" +
		"@@ -8,3 +8,4 @@\n 8\n 9\n 10\n+11\n\\ No newline at end of file\n"
	if got := Unified("f.txt", []byte(a), []byte(b)); got != want {
		t.Errorf("unified =\n%q\nwant\n%q", got, want)
	}
	if Unified("f.txt", []byte(a), []byte(a)) != "" {
		t.Error("equal sides must give no text")
	}
	add := Unified("n.txt", nil, []byte("x\n"))
	if add != "--- a/n.txt\n+++ b/n.txt\n@@ -0,0 +1,1 @@\n+x\n" {
		t.Errorf("add = %q", add)
	}
}

func TestUnifiedEnvShowsKeysNotValues(t *testing.T) {
	before := "# keep\nPOSTGRES_PASSWORD=hunter2-hunter2\nHASURA_KEY=abc123secret\nexport TOKEN=tok-9f8e7d\nPLAIN=1\n"
	after := "# keep\nPOSTGRES_PASSWORD=rotated-s3cr3t-value\nHASURA_KEY=abc123secret\nexport TOKEN=tok-9f8e7d\nNEW_KEY=brand-new-secret\nPLAIN=1\n"
	for _, path := range []string{".env", ".env.computed", ".nself/compose.env", "nested/.env.prod"} {
		u := Unified(path, []byte(before), []byte(after))
		for _, secret := range []string{"hunter2", "rotated", "abc123secret", "tok-9f8e7d", "brand-new-secret", "PLAIN=1"} {
			if strings.Contains(u, secret) {
				t.Errorf("%s: unified text leaks %q:\n%s", path, secret, u)
			}
		}
		for _, key := range []string{"POSTGRES_PASSWORD=[REDACTED]", "NEW_KEY=[REDACTED]"} {
			if !strings.Contains(u, key) {
				t.Errorf("%s: missing %q:\n%s", path, key, u)
			}
		}
	}
	// A non-env file is shown verbatim.
	if u := Unified("nginx/x.conf", []byte("a=1\n"), []byte("a=2\n")); !strings.Contains(u, "+a=2") {
		t.Errorf("non-env text must be verbatim: %s", u)
	}
}

func TestDiffMarksEnvRedacted(t *testing.T) {
	got := Diff(set(".env", "A=1\n"), set(".env", "A=2\n", ".nself/compose.env", "B=1\n"), nil)
	if len(got) != 2 || !got[0].Redacted || !got[1].Redacted || got[0].Kind != KindEnv || got[1].Kind != KindEnv {
		t.Errorf("env artifacts must be redacted: %+v", got)
	}
}

func TestUnifiedTooLargeForScript(t *testing.T) {
	var a, b strings.Builder
	for i := 0; i < maxTraceDistance; i++ {
		fmt.Fprintf(&a, "a%d\n", i)
		fmt.Fprintf(&b, "b%d\n", i)
	}
	u := Unified("f", []byte(a.String()), []byte(b.String()))
	if !strings.Contains(u, "diff too large to display (4000 lines changed)") {
		t.Errorf("got %q", u[:min(len(u), 200)])
	}
	if got := Diff(set("f", a.String()), set("f", b.String()), nil); got[0].DiffLines != 4000 {
		t.Errorf("diff_lines = %d", got[0].DiffLines)
	}
}
