package main

// error-codes.md page kind: the error-code reference rendered from the errs
// registry.
//
// Purpose: every structured CLI error prints a `Docs:` link of the shape
// …/reference/error-codes#eNNN, and the page those anchors point at was
// hand-kept, so rows drifted from internal/errs and links 404ed until someone
// noticed. The page is now generated: one section per allocated block that has
// registered codes, one row per code carrying an inline anchor equal to the
// fragment of the code's DocsPath, and the exit class of the registry entry.
//
// Inputs: a registry snapshot (a map, so tests can pass a fixture with a code
// the committed registry does not have) and the prose lifted from the page
// already on disk.
//
// Outputs: the whole page; writeErrorCodesPage compares it with the file and
// writes it (or reports it stale under -check).
//
// Constraints: the intro, the JSON error object, the code-allocation table,
// the scripting note and the related-pages list are human prose carried in
// PROSE blocks; regeneration never touches them. Category titles and
// one-line blurbs are page copy owned by this generator.
//
// After the merge this page is a shared generated artifact: Tickets that add
// an error code regenerate it (make wiki-commands) instead of editing rows.

import (
	"fmt"
	"os"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/nself-org/cli/internal/errs"
)

// errCodesProse holds the human-written sections of error-codes.md that
// regeneration carries verbatim.
type errCodesProse struct {
	intro      string // everything above the first category table
	jsonObject string // "## JSON error object"
	allocation string // "## Code allocation"
	scripts    string // "## Error codes in scripts"
	related    string // "## Related pages"
}

// categoryCopy is the authored heading and blurb of one category section.
// Titles and blurbs are page copy; the codes, ranges and order come from the
// registry and errs.Blocks, never from here.
type categoryCopy struct{ title, blurb, footnote string }

var categoryCopyByCategory = map[string]categoryCopy{
	"docker":    {"Docker", "These errors occur when the CLI cannot find or communicate with Docker.", ""},
	"config":    {"Config", "These errors occur during configuration validation or when reading `.env` files.", ""},
	"plugin":    {"Plugin and License", "These errors occur when installing plugins or validating license keys.", ""},
	"ssl":       {"SSL and Network", "These errors occur during SSL certificate generation or network operations.", ""},
	"database":  {"Database, Backup and Recovery", "These errors occur when the CLI interacts with the PostgreSQL container, backups, restores and disaster recovery.", ""},
	"health":    {"Health", "These errors occur during health checks run by `nself doctor`, `nself health`, `nself status` and startup probes.", ""},
	"init":      {"Init and Project", "These errors occur during `nself init` or when the CLI validates the working directory.", ""},
	"domain":    {"Domain", "These errors occur when the CLI validates domain names or port numbers from config.", ""},
	"cli":       {"CLI", "These errors come from the command line itself: usage, JSON support, destructive-action gates and moved commands.", ""},
	"reconcile": {"Reconcile and locks", "Change-plan (E450) and operation-lock (E460) codes. The other codes in this block are documented here when their Tickets register them.", ""},
	"deploy":    {"Deploy", "These errors come from `nself deploy` and related commands. Only the codes registered so far are listed.", ""},
	"adopt":     {"Adopt", "These errors come from adopting an existing stack: custom services that name dependencies, networks, build contexts and host binds. Only the codes registered so far are listed.", "See [[Config-Custom-Services]] for the keys and [[Import-Export-Format]] for the bundle codes."},
	"secret":    {"Secret", "These errors come from resolving secrets for a service.", ""},
}

// categoryHeadingRe matches a generated category heading, both to stop the
// legacy intro lift and so tests can split sections.
var categoryHeadingRe = regexp.MustCompile(`(?m)^## [^(]+\(E\d{3}-E\d{3}\)\s*$`)

// renderErrorCodesPage builds the whole page from a registry snapshot and the
// carried prose. A code outside every allocated block is an error, not a
// silently dropped row.
func renderErrorCodesPage(entries map[string]errs.CodeEntry, prose errCodesProse) (string, error) {
	var b strings.Builder
	b.WriteString("<!-- GENERATED BY tools/wikigen — DO NOT HAND EDIT (PROSE blocks excepted) -->\n")
	b.WriteString("# Error Codes Reference\n\n")
	writeProse(&b, "intro", prose.intro, defaultErrorCodesIntro())

	blocks := errs.Blocks
	for i, blk := range blocks {
		var codes []string
		for c, e := range entries {
			n, err := strconv.Atoi(c[1:])
			if err != nil || len(c) != 4 {
				return "", fmt.Errorf("bad code %q", c)
			}
			if n >= blk.Lo && n <= blk.Hi {
				if e.Category != blk.Category {
					return "", fmt.Errorf("%s: category %q differs from block %q", c, e.Category, blk.Category)
				}
				codes = append(codes, c)
			}
		}
		if len(codes) == 0 {
			continue
		}
		sort.Strings(codes)
		copyOf := categoryCopyByCategory[blk.Category]
		if copyOf.title == "" {
			copyOf = categoryCopy{title: strings.ToUpper(blk.Category[:1]) + blk.Category[1:]}
		}
		intro := prose.intro
		if intro == "" {
			intro = defaultErrorCodesIntro()
		}
		if i > 0 || strings.TrimSpace(intro) != "" {
			b.WriteString("---\n\n")
		}
		fmt.Fprintf(&b, "## %s (E%03d-E%03d)\n\n", copyOf.title, blk.Lo, blk.Hi)
		if copyOf.blurb != "" {
			b.WriteString(copyOf.blurb + "\n\n")
		}
		b.WriteString(beginGenerated("codes-"+blk.Category) + "\n")
		b.WriteString(errorCodesTable(codes, entries))
		b.WriteString(endGenerated("codes-"+blk.Category) + "\n\n")
		if copyOf.footnote != "" {
			b.WriteString(copyOf.footnote + "\n\n")
		}
	}

	for _, s := range []struct{ name, heading, body string }{
		{"json-error-object", "## JSON error object", prose.jsonObject},
		{"code-allocation", "## Code allocation", prose.allocation},
		{"scripts", "## Error codes in scripts", prose.scripts},
		{"related", "## Related pages", prose.related},
	} {
		b.WriteString("---\n\n")
		writeProseHeading(&b, s.name, s.heading, s.body)
	}
	b.WriteString("← [[Home]] | [[_Sidebar]]\n")
	return b.String(), nil
}

// errorCodesTable renders the rows of one category. Exit 0 means "classified
// by sentinel, else 1" (E400), and is spelled out rather than shown as 0.
func errorCodesTable(codes []string, entries map[string]errs.CodeEntry) string {
	var b strings.Builder
	b.WriteString("| Code | Exit | Summary | Why | Fix |\n")
	b.WriteString("|------|------|---------|-----|-----|\n")
	for _, c := range codes {
		e := entries[c]
		exit := strconv.Itoa(e.Exit)
		if e.Exit == 0 {
			exit = "classified"
		}
		fmt.Fprintf(&b, "| <a id=\"%s\"></a>%s | %s | %s | %s | %s |\n",
			strings.ToLower(c), c, exit,
			escapeCell(e.Summary), escapeCell(e.DefaultWhy), escapeCell(e.DefaultFix))
	}
	return b.String()
}

// defaultErrorCodesIntro seeds the intro before a human writes one, so the
// page is never generated with an empty top.
func defaultErrorCodesIntro() string {
	return "Every user-facing error in the ɳSelf CLI includes a stable code, a plain-language\n" +
		"explanation, and a suggested fix. This page is the catalog for all registered error codes.\n\n" +
		"<!-- TODO(docs): needs human prose -->"
}

// writeProseHeading emits one carried section with its heading inside the
// block, so a prose section is self-contained.
func writeProseHeading(b *strings.Builder, section, heading, body string) {
	body = strings.TrimSpace(body)
	b.WriteString(beginProse(section) + "\n")
	if body != "" {
		if !strings.HasPrefix(body, heading) {
			b.WriteString(heading + "\n\n")
		}
		b.WriteString(body + "\n")
	}
	b.WriteString(endProse(section) + "\n\n")
}

// readErrorCodesProse recovers the prose of the page on disk. Pages written by
// this generator are read back from their markers; a hand-written page has
// its sections lifted by heading so nothing human is lost on first generation.
func readErrorCodesProse(body string) errCodesProse {
	if strings.Contains(body, beginProse("intro")) {
		return errCodesProse{
			intro:      between(body, beginProse("intro"), endProse("intro")),
			jsonObject: between(body, beginProse("json-error-object"), endProse("json-error-object")),
			allocation: between(body, beginProse("code-allocation"), endProse("code-allocation")),
			scripts:    between(body, beginProse("scripts"), endProse("scripts")),
			related:    between(body, beginProse("related"), endProse("related")),
		}
	}
	rel := section(body, "## Related pages")
	if idx := strings.Index(rel, "← [[Home]]"); idx >= 0 {
		rel = strings.TrimSpace(rel[:idx])
	}
	for strings.HasSuffix(rel, "---") {
		rel = strings.TrimSpace(strings.TrimSuffix(rel, "---"))
	}
	p := errCodesProse{
		intro:      legacyIntro(body),
		jsonObject: section(body, "## JSON error object"),
		allocation: section(body, "## Code allocation"),
		scripts:    section(body, "## Error codes in scripts"),
		related:    rel,
	}
	return p
}

// legacyIntro lifts everything between the H1 and the first category heading,
// dropping the trailing separator, from a hand-written page.
func legacyIntro(body string) string {
	lines := strings.Split(body, "\n")
	start := 0
	for i, l := range lines {
		if strings.HasPrefix(strings.TrimSpace(l), "# ") {
			start = i + 1
			break
		}
	}
	var out []string
	for _, l := range lines[start:] {
		if categoryHeadingRe.MatchString(l) {
			break
		}
		out = append(out, l)
	}
	for len(out) > 0 && strings.TrimSpace(out[len(out)-1]) == "" {
		out = out[:len(out)-1]
	}
	for len(out) > 0 && strings.TrimSpace(out[len(out)-1]) == "---" {
		out = out[:len(out)-1]
		for len(out) > 0 && strings.TrimSpace(out[len(out)-1]) == "" {
			out = out[:len(out)-1]
		}
	}
	return strings.TrimSpace(strings.Join(out, "\n"))
}

// writeErrorCodesPage regenerates path from the registry snapshot. It reports
// whether the page changed; under check nothing is written and a change is
// reported as stale.
func writeErrorCodesPage(path string, entries map[string]errs.CodeEntry, check bool) (bool, error) {
	current, err := os.ReadFile(path)
	var prose errCodesProse
	if err == nil {
		prose = readErrorCodesProse(string(current))
	} else if !os.IsNotExist(err) {
		return false, fmt.Errorf("read %s: %w", path, err)
	}
	page, err := renderErrorCodesPage(entries, prose)
	if err != nil {
		return false, err
	}
	if err == nil && string(current) == page {
		return false, nil
	}
	if check {
		return true, nil
	}
	return true, os.WriteFile(path, []byte(page), 0o644)
}
