package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nself-org/cli/internal/cmdregistry"
	"github.com/spf13/cobra"
)

func ptr(s string) *string { return &s }

func TestRegistryPageFactsAndProse(t *testing.T) {
	c := &cobra.Command{Use: "build", Short: "Cobra summary", Long: "Cobra description", Example: "nself build"}
	entry := cmdregistry.Command{
		Path: "nself build", Name: "build", Parent: "nself", Summary: "Registry summary",
		Args: []cmdregistry.Arg{{Name: "project", Required: true}},
		Flags: []cmdregistry.Flag{{Name: "apply", Shorthand: ptr("a"), Type: "bool", Default: "false",
			Env: ptr("NSELF_APPLY"), SideEffect: ptr("write"), JSON: ptr("envelope"), Usage: "Apply changes"}},
		SideEffect: "read", Output: "document", JSON: "envelope",
		DataSchema: ptr("schemas/commands/build.v1.schema.json"),
		ExitCodes:  map[string]string{"error": "1", "ok": "0"},
	}
	entries := indexRegistry([]cmdregistry.Command{entry, {
		Path: "nself build plan", Name: "plan", Parent: "nself build", Summary: "Plan changes",
	}})
	prose := proseBlocks{summary: "> Authored summary.", description: "Authored description.\n\nSecond paragraph.",
		examples: "```bash\nnself build\n```", seeAlso: "- [[Commands]]"}
	page := renderPage(c, entry, entries, prose)
	for _, want := range []string{
		"nself build <project> [flags]", "| Name | Shorthand | Type | Default | Env | Escalates to | JSON override | Description |",
		"| `--apply` | `-a` | `bool` | `false` | `NSELF_APPLY` | `write` | `envelope` | Apply changes |",
		"| `plan` | Plan changes |", "**Side effect:** `read`", "**Output:** `document`",
		"[data schema](https://github.com/nself-org/cli/blob/main/schemas/commands/build.v1.schema.json)",
		"**Exit codes:** `error`: `1`, `ok`: `0`",
	} {
		if !strings.Contains(page, want) {
			t.Errorf("page lacks %q", want)
		}
	}
	if !strings.HasPrefix(page, "<!-- GENERATED BY tools/wikigen — DO NOT HAND EDIT") {
		t.Fatal("missing first-line generated marker")
	}
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, pageName("build")), []byte(page), 0o644); err != nil {
		t.Fatal(err)
	}
	got := readExisting(dir, "build")
	for _, section := range []string{"summary", "description", "examples", "see-also"} {
		if between(page, beginProse(section), endProse(section)) != between(renderPage(c, entry, entries, got), beginProse(section), endProse(section)) {
			t.Errorf("%s prose changed on regeneration", section)
		}
	}
}

func TestRegistryFlagMutationChangesPage(t *testing.T) {
	c := &cobra.Command{Use: "build"}
	entry := cmdregistry.Command{Path: "nself build", Name: "build", Parent: "nself", Flags: []cmdregistry.Flag{}}
	before := renderPage(c, entry, indexRegistry([]cmdregistry.Command{entry}), proseBlocks{})
	path := filepath.Join(t.TempDir(), "cmd-build.md")
	if err := os.WriteFile(path, []byte(before), 0o644); err != nil {
		t.Fatal(err)
	}
	entry.Flags = append(entry.Flags, cmdregistry.Flag{Name: "new", Type: "bool", Default: "false"})
	after := renderPage(c, entry, indexRegistry([]cmdregistry.Command{entry}), proseBlocks{})
	if before == after || !strings.Contains(after, "`--new`") || !pageStale(path, after) {
		t.Fatal("-check missed fixture registry flag addition")
	}
}
