package main

// Stub pages for commands that moved in v1.5.
//
// Purpose: a depth-1 command that the canon moved or shimmed keeps its old
// cmd-<old>.md page, rewritten as a stub that says where the command went and
// still carries the old PROSE blocks under "Previous content", so the human
// writing is not lost and a later move Ticket can fold it into the new page.
//
// Inputs: canon rows (internal/canon), the wiki directory, the existing page.
//
// Outputs: cmd-<old>.md rewritten as a stub; stale names under -check.
//
// Constraints: only pages that already exist are touched (no stub for a
// command that never had a page). The stub keeps the BEGIN/END PROSE markers,
// so readExisting recovers the same blocks and regeneration is idempotent;
// -check accepts a stub that matches the renderer's output.

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/nself-org/cli/internal/canon"
)

// stubRow is one moved depth-1 command.
type stubRow struct{ Old, New, Since, RemovalAt string }

// stubRows lists the depth-1 moves, shims and retired hubs, sorted by old name.
func stubRows(r canon.Rows) []stubRow {
	var out []stubRow
	add := func(rows []canon.Row) {
		for _, m := range rows {
			if m.From != "" && !strings.Contains(m.From, " ") {
				out = append(out, stubRow{m.From, m.To, m.Since, m.RemovalAt})
			}
		}
	}
	add(r.Moves)
	add(r.Shims)
	add(r.RetiredHubs)
	sort.Slice(out, func(i, j int) bool { return out[i].Old < out[j].Old })
	return out
}

// renderStub builds the stub page for row, carrying prose.
func renderStub(row stubRow, prose proseBlocks) string {
	var b strings.Builder
	target := strings.Fields(row.New + " ")[0]
	fmt.Fprintf(&b, "<!-- GENERATED BY tools/wikigen — DO NOT HAND EDIT (PROSE blocks excepted) -->\n# nself %s\n\n", row.Old)
	fmt.Fprintf(&b, "> Moved to `nself %s` in %s, removed in %s. The old spelling keeps working until then.\n\n",
		row.New, orDefault(row.Since, "v1.5.0"), orDefault(row.RemovalAt, "v1.6.0"))
	fmt.Fprintf(&b, "See [[%s]] for the current command. [[Command-Canon]] lists every move.\n\n", "cmd-"+target)
	b.WriteString("## Previous content\n\n")
	summary := strings.TrimSpace(prose.summary)
	for strings.HasPrefix(summary, ">") {
		summary = strings.TrimSpace(strings.TrimPrefix(summary, ">"))
	}
	if summary != "" {
		summary = "> " + summary
	}
	for _, blk := range []struct{ name, heading, body string }{
		{"summary", "", summary},
		{"description", "### Description", prose.description},
		{"examples", "### Examples", prose.examples},
		{"see-also", "### See Also", prose.seeAlso},
	} {
		if blk.heading != "" {
			b.WriteString(blk.heading + "\n\n")
		}
		b.WriteString(beginProse(blk.name) + "\n")
		if body := strings.TrimSpace(blk.body); body != "" {
			b.WriteString(body + "\n")
		}
		b.WriteString(endProse(blk.name) + "\n\n")
	}
	b.WriteString("← [[Commands]] | [[Home]] →\n")
	return b.String()
}

func orDefault(s, d string) string {
	if s == "" {
		return d
	}
	return s
}

// writeStubs renders a stub over every existing page of a moved command. Under
// check nothing is written; stale lists the pages that differ.
func writeStubs(dir string, rows []stubRow, check bool) (stale []string, written int, err error) {
	for _, row := range rows {
		path := filepath.Join(dir, pageName(row.Old))
		current, rerr := os.ReadFile(path)
		if rerr != nil {
			continue
		}
		page := renderStub(row, readExisting(dir, row.Old))
		if string(current) == page {
			continue
		}
		if check {
			stale = append(stale, pageName(row.Old))
			continue
		}
		if werr := os.WriteFile(path, []byte(page), 0o644); werr != nil {
			return stale, written, fmt.Errorf("write %s: %w", path, werr)
		}
		written++
	}
	return stale, written, nil
}
