package main

// Tests for the moved-command stub pages.

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/nself-org/cli/internal/canon"
)

const oldPage = `# nself urls

<!-- BEGIN PROSE:summary -->
> Print the service URLs.
<!-- END PROSE:summary -->

## Description

<!-- BEGIN PROSE:description -->
Hand written description with ` + "`code`" + `.
<!-- END PROSE:description -->

## Examples

<!-- BEGIN PROSE:examples -->
` + "```bash\nnself urls\n```" + `
<!-- END PROSE:examples -->

## See Also

<!-- BEGIN PROSE:see-also -->
- [[cmd-config]]
<!-- END PROSE:see-also -->

← [[Commands]] | [[Home]] →
`

func TestStubPage(t *testing.T) {
	dir := t.TempDir()
	page := filepath.Join(dir, "cmd-urls.md")
	if err := os.WriteFile(page, []byte(oldPage), 0o644); err != nil {
		t.Fatal(err)
	}
	rows := stubRows(canon.Rows{
		Moves: []canon.Row{{From: "urls", To: "config urls", Since: "v1.5.0", RemovalAt: "v1.6.0"}},
		Shims: []canon.Row{{From: "db old", To: "db", Since: "v1.5.0", RemovalAt: "v1.6.0"}, // depth 2: no stub
			{From: "nopage", To: "start", Since: "v1.5.0", RemovalAt: "v1.6.0"}},
	})
	if len(rows) != 2 {
		t.Fatalf("depth-1 rows = %+v", rows)
	}

	// -check on the old page reports it stale and writes nothing.
	stale, _, err := writeStubs(dir, rows, true)
	if err != nil || len(stale) != 1 || stale[0] != "cmd-urls.md" {
		t.Fatalf("check: stale=%v err=%v", stale, err)
	}
	if b, _ := os.ReadFile(page); string(b) != oldPage {
		t.Fatal("check wrote the page")
	}

	_, n, err := writeStubs(dir, rows, false)
	if err != nil || n != 1 {
		t.Fatalf("write: n=%d err=%v", n, err)
	}
	if _, err := os.Stat(filepath.Join(dir, "cmd-nopage.md")); err == nil {
		t.Fatal("stub created for a command with no page")
	}
	b, _ := os.ReadFile(page)
	got := string(b)
	for _, want := range []string{
		"GENERATED BY tools/wikigen",
		"> Moved to `nself config urls` in v1.5.0, removed in v1.6.0.",
		"[[cmd-config]]",
		"## Previous content",
		"> Print the service URLs.",
		"Hand written description with `code`.",
		"```bash\nnself urls\n```",
		"- [[cmd-config]]",
	} {
		if !strings.Contains(got, want) {
			t.Errorf("stub lacks %q", want)
		}
	}

	// Idempotent, and -check accepts the stub.
	stale, n, err = writeStubs(dir, rows, true)
	if err != nil || len(stale) != 0 || n != 0 {
		t.Fatalf("check on stub: stale=%v err=%v", stale, err)
	}
	if _, n, _ = writeStubs(dir, rows, false); n != 0 {
		t.Fatal("second write changed the stub")
	}
	// A hand edit of the generated part is caught.
	if err := os.WriteFile(page, []byte(strings.Replace(got, "Moved to", "Gone to", 1)), 0o644); err != nil {
		t.Fatal(err)
	}
	if stale, _, _ = writeStubs(dir, rows, true); len(stale) != 1 {
		t.Fatal("hand edit not detected")
	}
}

func TestHelpTopicStubLinksToExistingPage(t *testing.T) {
	page := renderStub(stubRow{Old: "help-topics", New: "help topics"}, proseBlocks{})
	if !strings.Contains(page, "See [[Commands]] for the current command list") || strings.Contains(page, "[[cmd-help]]") {
		t.Fatalf("help topic stub has an unresolved help link: %s", page)
	}
}
