// Package model holds the wire types of the plugin catalog generator
// (contract:plugins.catalog v1, contract:plugins.registry, contract:plugins.counts).
//
// Purpose: one definition of every document tools/catalog reads or writes, so
// tools/schemagen can generate schemas/catalog.v1.schema.json and
// schemas/releases.v1.schema.json from the same Go types the generator uses.
// Inputs: none (types only). Outputs: the types and enum values below.
// Constraints: standard library only; every optional key is omitempty and every
// nullable catalog key is a pointer, so a written document never carries a key
// the contract does not list.
package model

// Generated marker written as `_generated` in every output file.
const Generated = "GENERATED BY tools/catalog — DO NOT HAND EDIT"

// Schema versions and tier wire values.
const (
	CatalogVersion  = 1
	ReleasesVersion = 1
	CountsVersion   = 1
	RegistryVersion = "2.0.0"

	TierFree     = "free"     // catalog and bundles.json license axis
	TierLicensed = "licensed" // catalog license axis
	WireFree     = "free"     // registry `tier` wire value, free
	WirePro      = "pro"      // registry `tier` wire value, licensed (kept for released CLIs)
	SigAlg       = "ed25519"
)

// Tiers is the catalog `tier` enum.
var Tiers = []string{TierFree, TierLicensed}

// GeneratedFrom records the inputs of a run. GeneratedAt is the only timestamp
// in any output and is supplied by the caller, never read from a clock.
type GeneratedFrom struct {
	PluginsRef  string `json:"plugins_ref"`
	BundlesRef  string `json:"bundles_ref"`
	GeneratedAt string `json:"generated_at"`
}

// Signature is a release signature (contract:plugins.release-signature).
type Signature struct {
	KeyID string `json:"key_id"`
	Alg   string `json:"alg"`
	Sig   string `json:"sig"`
}

// Requires mirrors manifest v2 `requires`.
type Requires struct {
	Nself              string   `json:"nself,omitempty"`
	Plugins            []string `json:"plugins,omitempty"`
	PostgresExtensions []string `json:"postgres_extensions,omitempty"`
}

// Commands is the command surface of a plugin: the root command and every
// subcommand path.
type Commands struct {
	Command     string   `json:"command"`
	Subcommands []string `json:"subcommands"`
}

// Info is the manifest-only part of a catalog row. It travels inside each
// registry entry (key `catalog`) so a catalog can be built from registry.json
// alone: the public repo never parses licensed manifests (Epic D3).
type Info struct {
	Maturity    string    `json:"maturity"`
	ServiceKind string    `json:"service_kind"`
	Commands    *Commands `json:"commands,omitempty"`
	Schema      string    `json:"schema,omitempty"`
	Requires    *Requires `json:"requires,omitempty"`
	DocsURL     string    `json:"docs_url,omitempty"`
}
