package routemodel

import (
	"encoding/json"
	"sort"
)

const Generated = "GENERATED BY nself build - DO NOT HAND EDIT"

// Model is the versioned, provider-neutral description of generated proxy routes.
type Model struct {
	Generated        string        `json:"_generated"`
	SchemaVersion    string        `json:"schema_version"`
	Project          string        `json:"project"`
	Env              string        `json:"env"`
	BaseDomain       string        `json:"base_domain"`
	Defaults         Defaults      `json:"defaults"`
	DefaultServer    DefaultServer `json:"default_server"`
	UnmodelledGlobal []string      `json:"unmodelled_global"`
	Zones            []Zone        `json:"zones"`
	Routes           []Route       `json:"routes"`
	MaxBodyLiteral   string        `json:"-"`
}

type Defaults struct {
	MaxBodyBytes int64       `json:"max_body_bytes"`
	Gzip         Gzip        `json:"gzip"`
	TLS          TLSDefaults `json:"tls"`
	ServerTokens bool        `json:"server_tokens"`
}
type Gzip struct {
	Enabled   bool     `json:"enabled"`
	Types     []string `json:"types"`
	MinLength *int     `json:"min_length"`
}
type TLSDefaults struct {
	Protocols []string `json:"protocols"`
	Ciphers   *string  `json:"ciphers"`
}
type DefaultServer struct {
	HTTP  DefaultHTTP  `json:"http"`
	HTTPS DefaultHTTPS `json:"https"`
}
type DefaultHTTP struct {
	ACMEWebroot   *string `json:"acme_webroot"`
	HealthPath    *string `json:"health_path"`
	RedirectHTTPS bool    `json:"redirect_https"`
}
type DefaultHTTPS struct {
	Action string `json:"action"`
}
type Zone struct {
	Name string  `json:"name"`
	Kind string  `json:"kind"`
	Key  string  `json:"key"`
	Rate *string `json:"rate"`
}
type Route struct {
	ID                  string            `json:"id"`
	Source              string            `json:"source"`
	Owner               *string           `json:"owner"`
	File                string            `json:"file"`
	ServerNames         []string          `json:"server_names"`
	Listen              Listen            `json:"listen"`
	TLS                 *RouteTLS         `json:"tls"`
	HTTPToHTTPSRedirect bool              `json:"http_to_https_redirect"`
	SecurityHeaders     map[string]string `json:"security_headers"`
	BlockedPaths        []BlockedPath     `json:"blocked_paths"`
	RateLimit           *RateLimit        `json:"rate_limit"`
	Locations           []Location        `json:"locations"`
	ShadowedBy          *string           `json:"shadowed_by"`
	Unmodelled          []string          `json:"unmodelled"`
	LegacyServerName    string            `json:"-"`
	RouteName           string            `json:"-"`
	RawUpstream         string            `json:"-"`
}
type Listen struct {
	HTTP  bool `json:"http"`
	HTTPS bool `json:"https"`
}
type RouteTLS struct {
	SSLDir    string   `json:"ssl_dir"`
	Protocols []string `json:"protocols"`
	Ciphers   *string  `json:"ciphers"`
}
type BlockedPath struct {
	Regex  string `json:"regex"`
	Status int    `json:"status"`
}
type RateLimit struct {
	Zone      string `json:"zone"`
	Burst     int    `json:"burst"`
	ConnLimit int    `json:"conn_limit"`
}
type Location struct {
	Path             string            `json:"path"`
	Match            string            `json:"match"`
	Upstream         *Upstream         `json:"upstream"`
	RateLimit        *LocationRate     `json:"rate_limit"`
	WebSocket        bool              `json:"websocket"`
	ForwardedHeaders bool              `json:"forwarded_headers"`
	HeadersSet       map[string]string `json:"headers_set"`
	Timeouts         Timeouts          `json:"timeouts"`
	MaxBodyBytes     *int64            `json:"max_body_bytes"`
	AccessLog        bool              `json:"access_log"`
	DenyAll          bool              `json:"deny_all"`
	Methods          []string          `json:"methods"`
	Return           *Return           `json:"return"`
	StaticRoot       *string           `json:"static_root"`
	HealthProbe      bool              `json:"health_probe"`
}
type Upstream struct {
	Scheme string `json:"scheme"`
	Host   string `json:"host"`
	Port   int    `json:"port"`
}
type LocationRate struct {
	Zone    string `json:"zone"`
	Burst   int    `json:"burst"`
	Nodelay bool   `json:"nodelay"`
}
type Timeouts struct {
	ConnectS *int `json:"connect_s"`
	ReadS    *int `json:"read_s"`
	SendS    *int `json:"send_s"`
}
type Return struct {
	Status int     `json:"status"`
	To     *string `json:"to"`
}

// Marshal produces stable, indented contract bytes without mutating its caller.
func Marshal(m *Model) ([]byte, error) {
	copy := *m
	copy.Routes = append([]Route{}, m.Routes...)
	copy.Zones = append([]Zone{}, m.Zones...)
	copy.UnmodelledGlobal = append([]string{}, m.UnmodelledGlobal...)
	sort.Slice(copy.Zones, func(i, j int) bool { return copy.Zones[i].Name < copy.Zones[j].Name })
	sort.Slice(copy.Routes, func(i, j int) bool { return copy.Routes[i].ID < copy.Routes[j].ID })
	for i := range copy.Routes {
		copy.Routes[i].ServerNames = append([]string{}, copy.Routes[i].ServerNames...)
		sort.Strings(copy.Routes[i].ServerNames)
		copy.Routes[i].Locations = append([]Location{}, copy.Routes[i].Locations...)
		sort.Slice(copy.Routes[i].Locations, func(a, b int) bool {
			if copy.Routes[i].Locations[a].Match == copy.Routes[i].Locations[b].Match {
				return copy.Routes[i].Locations[a].Path < copy.Routes[i].Locations[b].Path
			}
			return copy.Routes[i].Locations[a].Match < copy.Routes[i].Locations[b].Match
		})
	}
	b, err := json.MarshalIndent(&copy, "", "  ")
	return append(b, '\n'), err
}
